.\" @(#)bcd.6 1.1 92/07/30 SMI; from UCB 4.2
.TH BCD 6 "16 February 1988"
.SH NAME
bcd, ppt \- convert to antique media
.SH SYNOPSIS
.B /usr/games/bcd
.I text
.LP
.B /usr/games/ppt
.SH DESCRIPTION
.IX  "bcd command"  ""  "\fLbcd\fP \(em convert to antique media"
.IX  "ppt command"  ""  "\fLbcd\fP \(em convert to antique media"
.B bcd
converts the literal
.I text
into a form familiar to old-timers.
.LP
.B ppt
converts the standard input into yet another form.
.SH "SEE ALSO"
.BR dd (1)
