.\" @(#)bdemos.6 1.1 92/07/30 SMI
.TH BDEMOS 6 "13 March 1984"
.SH NAME
bdemos \- demonstrate Sun Monochrome Bitmap Display
.SH SYNOPSIS
.B /usr/demo/bballs
.br
.B /usr/demo/bbounce
.br
.B /usr/demo/bdemos
.br
.B /usr/demo/bjump
.br
.BI /usr/demo/bphoto "  file"
.SH DESCRIPTION
.IX  "bballs command"  ""  "\fLbballs\fP \(em black and white demo"
.IX  "bbounce command"  ""  "\fLbbounce\fP \(em black and white demo"
.IX  "bdemos command"  ""  "\fLbdemos\fP \(em black and white demo"
.IX  "bjump command"  ""  "\fLbjump\fP \(em black and white demo"
.IX  "bphoto command"  ""  "\fLbphoto\fP \(em black and white demo"
.IX  "black and white demos"  bbounce  ""  \fLbbounce\fP
.IX  "black and white demos"  bdemos  ""  \fLbdemos\fP
.IX  "black and white demos"  bjump  ""  \fLbjump\fP
.IX  "black and white demos"  bphoto  ""  \fLbphoto\fP
.I Bdemos
is a collection of simple demonstration programs for the Sun Monochrome
Bitmap Display.  Each program is briefly described below.
Unless otherwise noted,
each program should be terminated by typing the appropriate key
(usually \s-2DELETE\s0 or ^C) to generate an interrupt signal.
.IP "\fBbballs\fP" 10
colliding balls demo
.IP "\fBbbounce\fP" 10
bouncing square demo
.IP "\fBbdemos\fP" 10
a collection of demos
.IP
This program has a menu for selection of several different demos. After typing
a key to select a particular demo, the user may type ^C to get back
the menu. Type `q' to quit.
.IP "\fBbjump\fP" 10
simulated jump to hyperspace
.IP "\fBbphoto\fP \fIfile\fR" 10
dither monochrome image \fIfile\fP to bitmap display
.IP
Image files suitable for display by this program are in
.IR /usr/demo/bwpix .
.SH FILES
.LP
.PD 0
.TP 20
.B /usr/demo/bwpix
.PD
.SH SEE ALSO
.BR bsuncube (6),
.BR draw (6)
