.\" @(#)buttontest.6 1.1 92/07/30 SMI; 
.TH BUTTONTEST 6 "09 May 1989"
.SH NAME
buttontest \- demonstration and testing program for SunButtons
.SH SYNOPSIS
.B /usr/demo/\s-1BUTTONBOX\s0/buttontest
.SH DESCRIPTION
.IX  "buttontest command"  ""  "\fLbuttontest\fP \(em SunButtons demo program "
.LP
.B buttontest
displays a window with
thirty two buttons, corresponding to those on SunButtons.
To determine if the button box
has been set up correctly, select the 
.B "Diagnostic"
button on the panel.  If the button box is correctly interfaced,
.B "buttonbox OK"
is displayed, and pressing a button on the box
highlights a button on the screen.  If
.B "No Response from Buttonbox"
is displayed,
repeat the button box install procedure.
