.\" @(#)cdplayer.6 1.1 92/07/30 SMI; by Edward Un
.TH CDPLAYER 6 "11 September 1989"
.SH NAME
cdplayer \- CD-ROM audio demo program
.SH SYNOPSIS
.B cdplayer
[-d 
.I device
] [
.I sunview options
]
.SH AVAILABILITY
.LP
This demo is available with the 
.I Games
software installation option. Refer to
.TX INSTALL
for information on how to install optional software.
.SH DESCRIPTION
.IX "cdplayer" "" "\fLcdplayer\fP \(em CD-ROM audio demo program"
.LP
.B cdplayer
demonstrate the
.SM CD
quality audio capability of the
.SM CD-ROM
drive. It
is a SunView program and plays any Audio Compact Discs. There are four
panels in the window. 
The top panel displays the all the available tracks
on the
.SM CD\s0.
The user can select the any tracks by clicking it with the
left mouse button. The second panel contains the play, pause, stop and
eject button. The third panel display the
.SM CD
music address and track number.
The bottom panel contains the volume control slider and close
button.
.LP
Refer to the
.SM CD-ROM
hardware documentation for connecting the speakers
or head-phones to the drive.
.SH OPTIONS
.TP 15
.BI \-d " device"
Use
.I device
as the
.SM CD-ROM device, rather than
.B /dev/rsr0
the default
.SM CD-ROM
device.
.SH FILES
.PD 0
.TP 20
.B /dev/rsr0
.SM CD-ROM
raw file
.PD
.SH SEE ALSO
.BR sr (4)
