.\" @(#)chess.6 1.1 92/07/30 SMI;
.TH CHESS 6 "18 February 1988"
.SH NAME
chess \- the game of chess
.SH SYNOPSIS
.B /usr/games/chess
.SH AVAILABILITY
.LP
This game is available for Sun-3 and Sun-4
systems with the
.I Games
software installation option.  Refer to
.TX INSTALL
for information on how to install optional software.
.SH DESCRIPTION
.IX  "chess"  ""  "\fLchess\fP \(em chess game"
.IX games chess "" "\fLchess\fP \(em chess game"
.LP
.B chess
is a computer program that plays class D chess.
Moves may be given either in standard (descriptive) notation
or in algebraic notation.
The symbol
.RB ` + '
is used to specify check;
.RB ` o-o '
and
.RB ` o-o-o '
specify castling.
To play black, type
.RB ` first ';
to print the board, type an empty line.
.LP
Each move is echoed in the appropriate
notation followed by the program's reply.
.SH DIAGNOSTICS
The most cryptic diagnostic is
.RB ` eh? '
which means that the input was syntactically incorrect.
.SH FILES
.PD 0
.TP 20
.B /usr/games/lib/chess.book
book of opening moves
.PD
.SH BUGS
Pawns may be promoted only to queens.
