.\" @(#)factor.6 1.1 92/07/30 SMI; from V7
.TH FACTOR 6 "16 February 1988"
.SH NAME
factor, primes \- factor a number, generate large primes
.SH SYNOPSIS
.B /usr/games/factor
[
.I number
]
.LP
.B /usr/games/primes
[
.I number
]
.SH DESCRIPTION
.IX "factor game" "" "\fLfactor\fP game"
.LP
.B factor
reads lines from its standard input.
If it reads a positive number,
.B factor
will factor the number and print its prime
factors, printing each one the proper number of times.
.B factor
exits when it reads zero, a negative number, or something other than a
number.
If a
.I number
is given,
.B factor
will factor the number, print its prime factors, and exit.
.LP
.B primes
reads a number from the standard input and
prints all primes larger than the given number and smaller than
2\u\s-232\s0\d (about 4.3\(mu10\u\s-29\s0\d).  If a
.I number
is given,
.B primes
will use that number rather than reading one from the standard input.
.SH DIAGNOSTICS
.TP 
.B Ouch.
Input out of range or for garbage input.
