.\" @(#)fortune.6 1.1 92/07/30 SMI; from UCB 4.2
.TH FORTUNE 6 "16 February 1988"
.SH NAME
fortune \- print a random, hopefully interesting, adage
.SH SYNOPSIS
.B /usr/games/fortune
[
.B \-
] [
.B \-alsw
]
[
.I filename
]
.SH DESCRIPTION
.IX  "fortune command"  ""  "\fLfortune\fP \(em get fortune"
.LP
.B fortune
with no arguments prints out a random adage. The flags mean:
.RS
.TP 5
.B \-a
Choose from either list of adages.
.TP 5
.B \-l
Long messages only.
.TP 5
.B \-s
Short messages only.
.TP 5
.B \-w
Waits before termination
for an amount of time calculated from the number 
of characters in the message.
This is useful if it is executed as part of the logout procedure
to guarantee that the message can be read before the screen is cleared.
.RE
.\"
.\".TP
.\".B \-o
.\"Choose from an alternate list of adages,
.\"often used for potentially offensive ones.
.\"
.SH FILES
.PD 0
.TP 20
.B /usr/games/lib/fortunes.dat
.PD
