.\" @(#)hack.6 1.1 92/07/30 SMI;
.TH HACK 6 "16 February 1988"
.SH NAME
hack \- replacement for rogue
.SH SYNOPSIS
.B hack
[
.B \-d
.I hackdir 
]  [
.B \-s
.B all
| 
.I player 
\&.\|.\|.  ]
.SH DESCRIPTION
.IX "hack game" "" "\fLhack\fP game"
.LP
.B hack
is a display-oriented dungeons & dragons type game.
Both display and command structure resemble
.IR rogue ,
although
.B hack
has twice as many monster types and requires three times as much memory.
.LP
Normally
.B hack
looks in
.B /usr/games/lib/hackdir
for the files listed below;
this directory can be changed with the
.B \-d
option.  The
.B \-s
option permits you to search the player record.
Given the keyword
.BR all ,
.B hack
lists all players;
given the login name of a player,
it lists all scores of that player.
.SH FILES
.PD 0
.TP 20
.B record	
top 100 list (start with an empty file)
.TP
.B news
changes or bugs (start with no news file)
.TP
.B data	
information about objects and monsters
.TP
.B help	
introductory information (no doubt outdated)
.TP
.B hh     	
compacted version of help
.TP
.B perm	
empty file used for locking
.TP
.B rumors	
texts for fortune cookies
.PD
.\".SH AUTHOR
.\"Andreas Bormann, Jay Fenlason
