#  @(#)Makefile 1.1 92/07/30 SMI;
#
#  Description file for making the section 6 manual page sources.
#
#  NOTE that the list of filenames in the description file must be
#  kept up to date with the actual manual pages, including ".so" files.
 
HERE=man6
  
# --------------------------------------------------------------- #

FILES= \
Intro.6 intro.6 List.6 list.6 \
adventure.6 arithmetic.6 backgammon.6 banner.6 battlestar.6 bcd.6 \
bdemos.6 bdraw.6 bj.6 boggle.6 boggletool.6 bouncedemo.6 brotcube.6 \
bsuncube.6 buttontest.6 canfield.6 canfieldtool.6 canvas_demo.6 \
cdplayer.6 cdraw.6 cframedemo.6 cfscores.6 chess.6 chesstool.6 ching.6 \
colordemos.6 craps.6 cribbage.6 cursor_demo.6 dialtest.6 draw.6 \
factor.6 fish.6 flight.6 fortune.6 framedemo.6 gaintool.6 gammontool.6 \
goban.6 gp_demos.6 graphics_demos.6 hack.6 hangman.6 hunt.6 jumpdemo.6 \
life.6 maze.6 mille.6 monop.6 moo.6 number.6 play.6 ppt.6 primes.6 \
quiz.6 rain.6 random.6 raw2audio.6 record.6 robots.6 rotcvph.6 rotobj.6 \
shaded.6 show.6 showmap.6 snake.6 snscore.6 soundtool.6 spheresdemo.6 \
stringart.6 suncoredemos.6 suncube.6 sunview_demos.6 trek.6 vwcvph.6 \
worm.6 worms.6 wump.6

# --------------------------------------------------------------- #

include ../Makefile.master
