.\" @(#)rain.6 1.1 92/07/30 SMI; from UCB 4.2
.TH RAIN 6 "16 February 1988"
.SH NAME
rain \- animated raindrops display
.SH SYNOPSIS
.B /usr/games/rain
.SH DESCRIPTION
.IX  "rain command"  ""  "\fLrain\fP \(em display raindrops"
.LP
.BR rain 's
display is modeled after the 
.SM VAX/VMS 
program of the same name.
The terminal has to be set for 9600 baud to obtain the proper effect.
.LP
As with all programs that use
.BR termcap ,
the 
.SM TERM 
environment
variable must be set (and exported) to the type of the terminal being used.
.SH FILES
.PD 0 
.TP 20
.B /etc/termcap
.PD
