.\" @(#)sunview_demos.6 1.1 92/07/30 SMI; 
.TH SUNVIEW_DEMOS 6 "16 February 1988"
.SH NAME
sunview_demos, canvas_demo, cursor_demo \- Window-System demonstration programs
.SH SYNOPSIS
.B /usr/demo/canvas_demo
.LP
.B /usr/demo/cursor_demo
.SH AVAILABILITY
.LP
These demos are available with the
.I SunView Demos
software installation option.  Refer to
.TX INSTALL
for information on how to install optional software.
.SH DESCRIPTION
.IX demos "SunView demos"
.IX demos canvas_demo "" "\fLcanvas_demo\fR \(em canvas subwindow demo"
.IX canvas_demo "" "\fLcanvas_demo\fR \(em canvas subwindow demo"
.IX demos cursor_demo "" "\fLcursor_demo\fR \(em cursor attributes demo"
.IX cursor_demo "" "\fLcursor_demo\fR \(em cursor attributes demo"
.LP
.SS canvas_Demo
.B canvas_demo 
demonstrates the capabilities of the canvas subwindow
package.  It consists of two subwindows:  a control panel and a
canvas.  By adjusting the items on the control panel, you can 
manipulate the attributes of the canvas, and see the results.
.SS cursor_Demo
.B cursor_demo 
demonstrates what you can do with cursors.  A single control 
panel is provide for adjusting the various cursor attributes.
As you adjust the items on the control panel, the panel's cursor 
changes in appearance.  
