FILES=	B.10 B.10r B.11 B.11r B.12 B.12r B.14 B.14r B.16 B.16r B.18 B.18r \
	B.20 B.20r B.22 B.22r B.24 B.24r B.28 B.28r B.36 B.36r B.6 B.6r B.7 \
	B.7r B.8 B.8r B.9 B.9r I.10 I.10r I.11 I.11r I.12 I.12r I.14 I.14r \
	I.16 I.16r I.18 I.18r I.20 I.20r I.22 I.22r I.24 I.24r I.28 I.28r \
	I.36 I.36r I.6 I.6r I.7 I.7r I.8 I.8r I.9 I.9r I.sr.36 R.10 R.10r \
	R.10r.tef R.11 R.11r R.12 R.12r R.14 R.14r R.16 R.16r R.18 R.18r \
	R.20 R.20r R.22 R.22r R.24 R.24r R.28 R.28r R.36 R.36r R.6 R.6r \
	R.7 R.7r R.8 R.8r R.9 R.9r S.10 S.10r S.11 S.11r S.12 S.12r S.14 \
	S.14r S.16 S.16r S.18 S.18r S.20 S.20r S.22 S.22r S.24 S.24r S.28 \
	S.28r S.36 S.36r S.6 S.6r S.7 S.7r S.8 S.8r S.9 S.9r apl.10 apl.10r \
	basker.b.12 basker.b.12r basker.i.12 basker.i.12r basker.r.12 \
	basker.r.12r bocklin.14 bocklin.14r bocklin.28 bocklin.28r \
	bodoni.b.10 bodoni.b.10r bodoni.i.10 bodoni.i.10r bodoni.r.10 \
	bodoni.r.10r chess.18 chess.18r clarendon.14 clarendon.14r \
	clarendon.18 clarendon.18r cm.b.10 cm.b.10r cm.b.11 cm.b.11r cm.b.12 \
	cm.b.12r cm.b.6 cm.b.6r cm.b.7 cm.b.7r cm.b.8 cm.b.8r cm.b.9 \
	cm.b.9r cm.i.10 cm.i.10r cm.i.11 cm.i.11r cm.i.12 cm.i.12r cm.i.6 \
	cm.i.6r cm.i.7 cm.i.7r cm.i.8 cm.i.8r cm.i.9 cm.i.9r cm.r.10 cm.r.10r \
	cm.r.11 cm.r.11r cm.r.12 cm.r.12r cm.r.6 cm.r.6r cm.r.7 cm.r.7r \
	cm.r.8 cm.r.8r cm.r.9 cm.r.9r countdown.22 countdown.22r cyrillic.12 \
	cyrillic.12.r cyrillic.12r delegate.b.12 delegate.b.12. \
	delegate.b.12r delegate.i.12 delegate.i.12r delegate.r.12 \
	delegate.r.12r fix.10 fix.10r fix.12 fix.12r fix.14 fix.14r \
	fix.6 fix.6r fix.8 fix.8r fix.9 fix.9r fontmap gacham.b.10 \
	gacham.b.10r gacham.i.10 gacham.i.10r gacham.r.10 gacham.r.10r \
	graphics.14 graphics.14r greek.10 greek.10r h19.10 h19.10r hebrew.16 \
	hebrew.16r hebrew.17 hebrew.17r hebrew.24 hebrew.24r hebrew.36 \
	hebrew.36r meteor.b.10 meteor.b.10r meteor.b.12 meteor.b.12r \
	meteor.b.8 meteor.b.8r meteor.i.10 meteor.i.10r meteor.i.8 \
	meteor.i.8r meteor.r.10 meteor.r.10r meteor.r.12 meteor.r.12r \
	meteor.r.8 meteor.r.8r mona.24 mona.24r nonie.b.10 nonie.b.10r \
	nonie.b.12 nonie.b.12r nonie.b.8 nonie.b.8r nonie.i.10 nonie.i.10r \
	nonie.i.12 nonie.i.12r nonie.i.8 nonie.i.8r nonie.r.10 nonie.r.10r \
	nonie.r.12 nonie.r.12r nonie.r.8 nonie.r.8r oldenglish.14 \
	oldenglish.14r oldenglish.18 oldenglish.18r oldenglish.8 \
	oldenglish.8r otimes.b.10 otimes.b.10r otimes.i.10 otimes.i.10r \
	otimes.r.10 otimes.r.10r otimes.s.10 otimes.s.10r pip.16 pip.16r \
	playbill.10 playbill.10r railmag script.18 script.18r seal.10 \
	seal.11 seal.12 seal.12r seal.20 seal.6 seal.7 seal.8 seal.9 shadow.16 \
	shadow.16r sign.22 sign.22r st.b.10r st.i.10r st.r.10r stare.b.10 \
	stare.b.10r stare.b.11 stare.b.11r stare.b.12 stare.b.12r stare.b.14 \
	stare.b.14r stare.b.16 stare.b.16r stare.b.8 stare.b.8r stare.b.9 \
	stare.b.9r stare.i.10 stare.i.10r stare.i.11 stare.i.11r stare.i.12 \
	stare.i.12r stare.i.14 stare.i.14r stare.i.16 stare.i.16r stare.i.8 \
	stare.i.8r stare.i.9 stare.i.9r stare.r.10 stare.r.10r stare.r.11 \
	stare.r.11r stare.r.12 stare.r.12r stare.r.14 stare.r.14r stare.r.16 \
	stare.r.16r stare.r.8 stare.r.8r stare.r.9 stare.r.9r times.b.10 \
	times.b.10r times.b.11 times.b.12 times.b.12r times.b.14 times.b.14r \
	times.b.16 times.b.16r times.b.18 times.b.18r times.b.20 times.b.20r \
	times.b.22 times.b.22r times.b.24 times.b.24r times.b.28 times.b.28r \
	times.b.36 times.b.36r times.b.6 times.b.6r times.b.7 times.b.7r \
	times.b.8 times.b.8r times.b.9 times.b.9r times.i.10 times.i.10r \
	times.i.11 times.i.12 times.i.12r times.i.14 times.i.14r times.i.16 \
	times.i.16r times.i.18 times.i.18r times.i.20 times.i.20r times.i.22 \
	times.i.22r times.i.24 times.i.24r times.i.28 times.i.28r times.i.36 \
	times.i.36r times.i.6 times.i.6r times.i.7 times.i.7r times.i.8 \
	times.i.8r times.i.9 times.i.9r times.r.10 times.r.10r times.r.11 \
	times.r.12 times.r.12r times.r.14 times.r.14r times.r.16 times.r.16r \
	times.r.18 times.r.18r times.r.20 times.r.20r times.r.22 times.r.22r \
	times.r.24 times.r.24r times.r.28 times.r.28r times.r.36 times.r.36r \
	times.r.6 times.r.6r times.r.7 times.r.7r times.r.8 times.r.8r \
	times.r.9 times.r.9r times.s.10 times.s.10r times.s.11 times.s.12 \
	times.s.12r times.s.14 times.s.14r times.s.16 times.s.16r times.s.18 \
	times.s.18r times.s.20 times.s.20r times.s.22 times.s.22r times.s.24 \
	times.s.24r times.s.28 times.s.28r times.s.36 times.s.36r times.s.6 \
	times.s.6r times.s.7 times.s.7r times.s.8 times.s.8r times.s.9 \
	times.s.9r ugramma.10 ugramma.10r
HERE=vfont

include ../Makefile.master
