FILES=	ftB ftCW ftI ftR ftS ftap ftbb ftbi ftbk ftbr ftcb ftch ftci \
	ftcl ftco ftcr ftcy ftdb ftdi ftdr ftgb ftgf ftgi ftgk ftgr fthb \
	fthn ftm ftmb ftmi ftmn ftmr ftnb ftni ftnr ftob ftoe ftoi ftor \
	ftpb ftpp ftsb ftsc ftsg ftsh ftsi ftsl ftsr fttB fttI fttR fttS \
	fttb ftti fttr ftts

HERE=font

include ../Makefile.master
