.\" %Z%%M% %I% %E% SMI;
.TH AUDIT_DATA 5 "19 October 1987"
.SH NAME
audit_data \- current information on audit daemon
.SH SYNOPSIS
.B /etc/security/audit/audit_data
.IX  "audit file"  ""  "\fLaudit\fP \(em audit data file"
.SH DESCRIPTION
.LP
The
.B audit_data
file contains information about the audit daemon.
The file contains the process
.SM ID
of the audit daemon,
and the pathname of the current audit log file.
The format of the file is:
.RS
.BI < pid >:< pathname >
.RE
Where
.I pid
is the process
.SM ID
for the audit daemon, and
.I pathname
is the full pathname for the current audit log file.
.SH EXAMPLE
.B 64:/etc/security/audit/auditserv/auditclient/2df0504
.SH FILES
.PD 0
.TP 20
.B /etc/security/audit/audit_data
.PD
.SH "SEE ALSO"
.BR audit (2),
.BR audit.log (5),
.BR audit (8),
.BR auditd (8)
