.\" @(#)bootparams.5 1.1 92/07/30 SMI;
.TH BOOTPARAMS 5 "16 February 1988"
.SH NAME
bootparams \- boot parameter data base
.SH SYNOPSIS
.B /etc/bootparams
.SH DESCRIPTION
.IX  "bootparams file"  ""  "\fLbootparams\fP \(em boot parameter database"
.IX  "boot parameter database"  ""  "boot parameter database \(em \fLbootparams\fP"
.LP
The
.B bootparams
file contains the list of client entries that diskless clients use for booting.
For each diskless client the entry should contain the following information:
.LP
.nf
	name of client
	a list of keys, names of servers, and pathnames.
.fi
.LP
The first item of each entry is the name of the diskless client.
The subsequent item is a list of keys,
names of servers, and pathnames.
.LP
Items are separated by
.SM TAB
characters.
.LP
A client entry in the local
.B /etc/bootparams
file supersedes an entry in the corresponding
Network Information Service
(\s-1NIS\s0)
map.
.SH EXAMPLE
.LP
Here is an example of the
.B /etc/bootparams
taken from a Sun\s-1OS\s0 system.
.sp
.ft B
.nf
myclient	root=myserver:/nfsroot/myclient \e
	swap=myserver:/nfsswap/myclient \e
	dump=myserver:/nfsdump/myclient
.fi
.SH FILES
.PD 0
.TP 20
.B /etc/bootparams
.PD
.SH "SEE ALSO"
.BR bootparamd (8)
.SH NOTES
.LP
The Network Information Service
(\s-1NIS\s0)
was formerly known as Sun Yellow Pages
(\s-1YP\s0). 
The functionality of the two remains the same;
only the name has changed.
