.\" @(#)ethers.5 1.1 92/07/30 SMI; new on release 3.0
.TH ETHERS 5 "19 October 1987"
.SH NAME
ethers \- Ethernet address to hostname database or NIS domain
.SH DESCRIPTION
.IX "ethers file" "" "\fLethers\fR file \(em Ethernet addresses"
.LP
The
.B ethers
file contains information regarding the
known (48 bit) Ethernet addresses of hosts on the Internet.
For each host on an Ethernet,
a single line should be present with the following information:
.IP
.I Ethernet-address	official-host-name
.LP
Items are separated by any number of blanks and/or
.SM TAB
characters.  A
.RB ` # '
indicates the beginning of a comment
extending to the end of line.
.LP
The standard form for Ethernet addresses is
``\fIx\fB:\fIx\fB:\fIx\fB:\fIx\fB:\fIx\fB:\fIx\fR'' where
.I x
is a hexadecimal number between 0 and ff, representing one byte.
The address bytes are always in network order.
Host names may contain any printable character other than
a
.SM SPACE\s0,
.SM TAB\s0,
.SM NEWLINE\s0,
or comment character.
It is intended that host names in the
.B ethers
file correspond to the host names in the
.BR hosts (5)
file.
.LP
The
.BR ether_line (\|)
routine from the Ethernet address manipulation library,
.BR ethers (3N)
may be used to scan lines of the
.B ethers
file.
.SH FILES
.PD 0
.TP 20
.B /etc/ethers
.PD
.SH "SEE ALSO"
.BR ethers (3N),
.BR hosts (5)
.SH NOTES
.LP
The Network Information Service
(\s-1NIS\s0)
was formerly known as Sun Yellow Pages
(\s-1YP\s0). 
The functionality of the two remains the same;
only the name has changed.
