.\" @(#)ftpusers.5 1.1 92/07/30 SMI;
.TH FTPUSERS 5 "17 June 1988"
.SH NAME
ftpusers \- list of users prohibited by FTP
.SH SYNOPSIS
.B /etc/ftpusers
.SH DESCRIPTION
.IX  "ftpusers file"  ""  "\fLftpusers\fP \(em ftp prohibited users list"
.LP
.B ftpusers
contains a list of users who cannot access this system using the
File Transfer Protocol (\s-1FTP\s0).
.B ftpusers
contains one user name per line.
.LP
If this file is missing, the list of users is considered to be empty, so that
any user may use
.SM FTP
to access the system if the other criteria for access are met (see
.BR ftpd (8C)).
.SH "SEE ALSO"
.BR ftp (1C),
.BR ftpd (8C)
