.\" @(#)help_viewer.5	1.1 92/07/30 SMI;
.TH HELP_VIEWER 5 "19 February 1988"
.SH NAME
help_viewer \- help viewer file format
.SH SYNOPSIS
.B /usr/lib/help/*/*
.SH AVAILABILITY
.LP
Available only on Sun 386i systems running a SunOS 4.0.\fIx\fR
release or earlier.  Not a SunOS 4.1 release feature.
.SH DESCRIPTION
.IX "help_viewer"  ""  "\fLhelp_viewer\fP \(em help viewer file format"
.IX "datafile"  "help_viewer" ""  "\fLhelp_viewer\fP \(em help viewer file format"
The
.B help_viewer
reads files of various types.
The Top Level list of applications documented is
.BR /usr/lib/help/Top_Level .
The Master Index shown at the top level is
.BR /usr/lib/help/Master_Index .
These files are FrameMaker files. To add or remove a heading from this list,
use FrameMaker (1.1 or later).
.LP
Each directory within
.B /usr/lib/help
that corresponds to a SunView 
application name contains detailed information about
that application. These are also FrameMaker files.
The
.B *.rf
files are rasterfiles, of standard image format created by FrameMaker.
These are the pictures that are interleaved into the text.
.LP
The
.B Frame/
subdirectory of
.B /usr/lib/help
contains topic, contents, and
index templates which can be used to create new Help Viewer handbooks.
The
.B Interleaf/
subdirectory
contains Interleaf templates, fonts, and initialization files.
.SH FILES
.LP
.TP 20
.B /usr/lib/help/*/*
.SH SEE ALSO
.BR help (5),
.BR help_viewer (1)
