.\" @(#)hosts.5 1.1 92/07/30 SMI; from UCB 4.2
.TH HOSTS 5  "18 December 1989"
.SH NAME
hosts \- host name data base
.SH SYNOPSIS
.B /etc/hosts
.SH DESCRIPTION
.IX  "hosts file"  ""  "\fLhosts\fP \(em host name data base"
.LP
The
.B hosts
file contains information regarding the known hosts on the
.SM TCP/IP.
For each host a single line should be present
with the following information:
.IP
.I Internet-address	official-host-name	aliases
.LP
Items are separated by any number of blanks and/or
.SM TAB
characters.  A
.RB ` # '
indicates the beginning of a comment;
characters up to the end of the line are not
interpreted by routines which search the file.  This
file is normally created from the official
host data base maintained at the Network Information
Control Center (\s-1NIC\s0), though local changes may
be required to bring it up to date
regarding unofficial aliases and/or unknown hosts.
.LP
Network addresses are specified in the conventional
.RB ` . '
notation using the
.B inet_addr (\|)
routine from the Internet address manipulation library,
.BR inet (3N).
Host names may contain any printable
character other than an upper case character, a field
delimiter,
.SM NEWLINE\s0,
or comment character.
.SH EXAMPLE
.LP
Here is a typical line from the
.B /etc/hosts
file:
.RS
.nf
.ft B
192.9.1.20        gaia                        # John Smith
.fi
.ft R
.RE
.SH FILES
.PD 0
.TP 20
.B /etc/hosts
.PD
.SH "SEE ALSO"
.BR gethostent (3N),
.BR inet (3N)
