.\" @(#)indent.pro.5 1.1 92/07/30 SMI;
.TH INDENT.PRO 5 "16 February 1988"
.SH NAME
indent.pro \- default options for indent
.SH DESCRIPTION
.IX  indent  ""  "\&\fL\&.indent.pro\fP \(em default options database"
The
.B \&.indent.pro
file in either the current or home directory contains default command
line options for the
.BR indent (1)
program.
It is a text file that contains space-separated command line options.
For a description of these options, see
.BR indent (1).
.LP
Explicit command line options override options taken from
.BR .indent.pro .
.LP
Here is a sample
.B .indent.pro
file:
.IP
.ft B
\-bap \-nbad \-nbbb \-bc \-br \-cdb \-nce
.br
\-fc1 \-ip \-lp \-npcs \-psl \-sc \-nsob \-cli0
.br
\-di12 \-l79 \-i4  \-d0 \-c33
.in
.ft R
.SH FILES
.TP
.B \&./.indent.pro
.PD 0
.br
.TP
.B ~/.indent.pro
.PD
.SH "SEE ALSO"
.LP
.BR indent (1)
