#  @(#)Makefile 1.1 92/07/30 SMI;
#
#  Description file for making the section 5 manual page sources.
#
#  NOTE that the list of filenames in the description file must be
#  kept up to date with the actual manual pages, including ".so" files.

HERE=man5

# --------------------------------------------------------------- #

# indent.pro defaults.5 textswrc.5
FILES= \
Intro.5 intro.5 List.5 list.5 \
a.out.5 acct.5 addresses.5 aliases.5 ar.5 audit.log.5 audit_control.5 \
audit_data.5 auto.home.5 auto.vol.5 backup.5 bar.5 boards.pc.5 \
bootparams.5 bootservers.5 coff.5 core.5 cpio.5 crontab.5 current.5 \
dir.5 dump.5 dumpdates.5 environ.5v ethers.5 exports.5 ext_ports.5 fbtab.5\
fcntl.5 filetype.5 forward.5 fs.5 fspec.5 fstab.5 ftpusers.5 gettytab.5 \
group.5 group.adjunct.5 help.5 help_viewer.5 hosts.5 hosts.equiv.5 \
indent.pro.5 inetd.conf.5 inode.5 internat.5 ipalloc.netrange.5 \
keytables.5 lastlog.5 link.5 locale.5 magic.5 mailaddr.5 mtab.5 \
netgroup.5 netmasks.5 netrc.5 networks.5 orgrc.5 passwd.5 \
passwd.adjunct.5 phones.5 plot.5 pnp.sysnames.5 policies.5 printcap.5 \
proto.5 protocols.5 publickey.5 queuedefs.5 rasterfile.5 remote.5 \
resolv.conf.5 rfmaster.5 rgb.5 rhosts.5 rmtab.5 rootmenu.5 rpc.5 sccsfile.5 \
services.5 setup.pc.5 sm.5 sm.bak.5 sm.state.5 state.5 statmon.5 \
sunview.5 svdtab.5 syslog.conf.5 systems.5 tar.5 term.5 term.5v \
termcap.5 terminfo.5v toc.5 translate.5 ttys.5 ttytab.5 ttytype.5 \
types.5 tzfile.5 ugid_alloc.range.5 updaters.5 utmp.5v uuencode.5 \
vfont.5 vgrindefs.5 wtmp.5 xtab.5 ypaliases.5 ypfiles.5 ypgroup.5 \
yppasswd.5 ypprintcap.5

# --------------------------------------------------------------- #

include ../Makefile.master
