.\" @(#)mtab.5 1.1 92/07/30 SMI;
.TH MTAB 5 "19 October 1987"
.SH NAME
mtab \- mounted file system table
.SH SYNOPSIS
.B /etc/mtab
.LP
.B #include <mntent.h>
.SH DESCRIPTION
.IX  "mtab file"  ""  "\fLmtab\fP \(em mounted file system table"
.IX  "mounted file system table"  ""  "mounted file system table \(em \fLmtab\fP"
.IX  "file system"  "mounted table"  ""  "mounted table \(em \fLmtab\fP"
.LP
.B mtab
resides in the
.B /etc
directory, and contains a table of filesystems
currently mounted by the
.BR mount (8)
command.
.B umount
removes entries from this file.
.LP
The file contains a line of information for each mounted filesystem,
structurally identical to the contents of
.BR /etc/fstab ,
described in
.BR fstab (5).
There are a number of lines of the form:
.IP
.I fsname dir type opts freq passno
.LP
for example:
.IP
.ft B
/dev/xy0a / 4.2 rw,noquota 1 2
.ft R
.LP
The file is accessed by programs using
.BR getmntent (3),
and by the system administrator using a text editor.
.SH FILES
.PD 0
.TP 20
.B /etc/mtab
.TP
.B /etc/fstab
.PD
.SH "SEE ALSO"
.BR getmntent (3),
.BR fstab (5),
.BR mount (8)
