.\" @(#)netmasks.5 1.1 92/07/30 SMI;
.TH NETMASKS 5 "19 October 1987"
.SH NAME
netmasks \- network mask data base
.SH DESCRIPTION
.IX  "netmasks file"  ""  "\fLnetmasks\fP \(em netmask data base"
.LP
The
.B netmasks
file contains network masks used to implement
.SM IP
standard subnetting.
For each network that is subnetted,
a single line should exist
in this file with the network number, any number of
.SM SPACE
or
.SM TAB
characters,
and the network mask to use on that network.
Network numbers and masks may be specified
in the conventional 
.SM IP
.RB ` . '
notation (like 
.SM IP
host addresses, but with zeroes for the host
part).  For example,
.IP
\fB128.32.0.0 255.255.255.0\fR
.LP
can be used to specify the Class B
network 128.32.0.0 should have
eight bits of subnet field and eight
bits of host field, in addition to
the standard sixteen bits in the network field.
When running the 
Network Information Service
(\s-1NIS\s0),
this file on the master is used for the
.B netmasks.byaddr
map.
.SH FILES
.PD 0
.TP 20
.B /etc/netmasks
.PD
.SH "SEE ALSO"
.BR ifconfig (8C)
.LP
Postel, Jon, and Mogul, Jeff,
.IR "Internet Standard Subnetting Procedure" ,
.SM RFC
950,
Network Information Center,
.SM SRI
International, Menlo Park, Calif.,
August 1985.
.SH NOTES
.LP
The Network Information Service
(\s-1NIS\s0)
was formerly known as Sun Yellow Pages
(\s-1YP\s0). 
The functionality of the two remains the same;
only the name has changed.
