.\" @(#)networks.5 1.1 92/07/30 SMI; from UCB 4.2
.TH NETWORKS 5 "18 December 1989"
.SH NAME
networks \- network name data base
.SH DESCRIPTION
.IX  "networks file"  ""  "\fLnetworks\fP \(em network name data base"
.LP
The
.B networks
file contains information regarding
the known networks which comprise the
.SM TCP/IP.
For each network a single line
should be present with the following information:
.IP
.I official-network-name	network-number	aliases
.LP
Items are separated by any number of blanks and/or
.SM TAB
characters.  A
.RB ` # '
indicates the beginning of a comment;
characters up to the end of the line are not
interpreted by routines which search the file.
This file is normally created from the
official network data base maintained at the
Network Information Control Center (\s-1NIC\s0),
though local changes may be required to bring
it up to date regarding unofficial aliases
and/or unknown networks.
.LP
Network number may be specified in the conventional
.RB ` . '
notation using the
.B inet_network (\|)
routine from the Internet address manipulation library,
.BR inet (3N).
Network names may contain any printable
character other than a field delimiter,
.SM NEWLINE\s0,
or comment character.
.SH FILES
.PD 0
.TP 20
.B /etc/networks
.PD
.SH "SEE ALSO"
.BR getnetent (3N),
.BR inet (3N)
.SH BUGS
A name server should be used instead of a static file.
A binary indexed file format should be
available for fast access.
