.\" @(#)phones.5 1.1 92/07/30 SMI; from UCB 4.2
.TH PHONES 5 "19 October 1987"
.SH NAME
phones \- remote host phone number data base
.SH SYNOPSIS
.B /etc/phones
.SH DESCRIPTION
.IX  "phones file"  ""  "\fLphones\fP \(em remote host phone numbers"
.IX  "remote host" "phone numbers \(em \fLphones\fP"
.IX  host "phone numbers file \(em \fLphones\fP"
.LP
The file
.B /etc/phones
contains the system-wide private phone numbers for the
.BR tip (1C)
program.
.B /etc/phones
is normally unreadable, and so may contain
privileged information.  The format of
.B /etc/phones
is a series of lines of the form:
.IP
.BI < system-name >[\ \et]*< phone-number >\fR.
.LP
The system name is one of those defined in the
.BR remote (5)
file and the phone number is constructed from
.BR [0123456789\-=*%] .
The
.RB ` = '
and
.RB ` * '
characters are indicators to the auto
call units to pause and wait for a second dial
tone (when going through an exchange).  The
.RB ` = '
is required by the
.SM DF02-AC
and the
.RB ` * '
is required by the
.SM BIZCOMP
1030.
.LP
Comment lines are lines containing a
.RB ` # '
sign in the first column of the line.
.LP
Only one phone number per line is permitted.
However, if more than
one line in the file contains the same system name
.BR tip (1C)
will attempt to dial each one in turn,
until it establishes a connection.
.SH FILES
.PD 0
.TP 20
.B /etc/phones
.PD
.SH "SEE ALSO"
.BR tip (1C),
.BR remote (5)
