.\" @(#)policies.5 1.1 92/07/30 SMI; 
.TH POLICIES 5 "19 February 1988"
.SH NAME
policies \- network administration policies
.SH AVAILABILITY
.LP
Available only on Sun 386i systems running a SunOS 4.0.\fIx\fR
release or earlier.  Not a SunOS 4.1 release feature.
.SH DESCRIPTION
.IX "policies file" "" "\fLpolicies\fP file"
.LP
The
.B policies
file contains information relevant to domain-wide
administration policies.
Each line contains two tokens, separated by white space; the first
token is the name of an administrative policy, and the second is the
value of that policy.
.SH FILES
.PD 0
.TP 20
.B /etc/policies
.TP
.B /var/yp/\fIdomainname\fB/policies.{dir,pag}
.PD
.SH "SEE ALSO"
.BR pnpd (8C),
.BR rarpd (8C),
.BR logintool (8)
