.\" @(#)protocols.5 1.1 92/07/30 SMI; from UCB 4.2
.TH PROTOCOLS 5 "18 December 1989"
.SH NAME
protocols \- protocol name data base
.SH SYNOPSIS
.B /etc/protocols
.SH DESCRIPTION
.IX  "protocols file"  ""  "\fLprotocols\fP \(em protocol name data base"
.LP
The
.B protocols
file contains information regarding
the known protocols used in the
.SM TCP/IP.
For each protocol a single line
should be present with the following information:
.IP
.I official-protocol-name	protocol-number	aliases
.LP
Items are separated by any number of blanks and/or
.SM TAB
characters.  A
.RB ` # '
indicates the beginning of a comment;
characters up to the end of the line are
not interpreted by routines which search the file.
.LP
Protocol names may contain any printable
character other than a field delimiter,
.SM NEWLINE\s0,
or comment character.
.SH EXAMPLE
.LP
The following example is taken from Sun\s-1OS\s0.
.LP
.nf
.ft B
.ta +1.0i +1.0i +1.0i
#
# Internet (\s-1IP\s0) protocols
#
ip	0	\s-1IP\s0	# internet protocol, pseudo protocol number
icmp	1	\s-1ICMP\s0	# internet control message protocol
ggp	3	\s-1GGP\s0	# gateway-gateway protocol
tcp	6	\s-1TCP\s0	# transmission control protocol
pup	12	\s-1PUP\s0	# \s-1PARC\s0 universal packet protocol
udp	17	\s-1UDP\s0	# user datagram protocol
.fi
.ft R
.SH FILES
.PD 0
.TP 20
.B /etc/protocols
.PD
.SH "SEE ALSO"
.BR getprotoent (3N)
.SH BUGS
A name server should be used instead of a static file.
A binary indexed file format should be available for fast access.
