.\" @(#)rgb.5 1.1 92/07/30 SMI;
.TH RGB 5 "19 February 1988"
.SH NAME
rgb \- available colors (by name) for coloredit
.SH SYNOPSIS
.IX "rgb file" "" "\fL.rgb\fP file"
.LP
.B .rgb
.LP
.B $HOME/.rgb
.LP
.B /usr/lib/.rgb
.SH AVAILABILITY
.LP
Available only on Sun 386i systems running a SunOS 4.0.\fIx\fR
release or earlier.  Not a SunOS 4.1 release feature.
.SH DESCRIPTION
.B \&.rgb
is an 
.SM ASCII
file containing consecutive lines terminated by newlines.
Each line starts with three integers, each in the range 0-255. 
These integers are the 
.SM RGB 
equivalent for the color named on the 
same line.  At least one tab character delimits the 
last integer from the name field. 
The coloreditor searches for this file, first in the current
directory; next, in the users home directory; and finally, in \fB/usr/lib\fR.
The user can add to or delete from the 
.B \&.rgb 
file that he or she has access to, thus
changing the available color table for subsequent invocations of coloredit.
.SH EXAMPLES
The following is an example of a 
.B \&.rgb
file.
.LP
.RS
.ft B
.nf
0 0 0		Black
0 0 255		Blue
95 159 159	Cadet Blue
66 66 111	Cornflower Blue
107 35 142	Dark Slate Blue
.fi
.ft R
.RE
.SH SEE ALSO
.BR coloredit (1)
