'\" t
.ds ~ ~
.\" @(#)rpc.5 1.1 92/07/30 SMI;
.TH RPC 5 "26 September 1985"
.SH NAME
rpc \- rpc program number data base
.SH SYNOPSIS
.B /etc/rpc
.SH DESCRIPTION
.IX  "rpc program number file"  ""  "\fLrpc\fP \(em rpc name data base"
The
.B rpc
file contains user readable names that
can be used in place of rpc program numbers.
Each line has the following information:
.IP
.I rpc-program-server	rpc-program-number	aliases
.LP
Items are separated by any number of blanks and/or
tab characters.
A ``#'' indicates the beginning of a comment; characters up to the end of
the line are not interpreted by routines which search the file.
.SH EXAMPLE
.LP
Here is an example of the 
.B /etc/rpc
file from the 
Sun\s-1OS\s0 System.
.br
.ne 4i
.if t .ft B
.TS
center;
l s s
l s s
l s s
l l l .
#
#            rpc   1.10   87/04/10
#
portmapper	100000	portmap sunrpc
rstatd	100001	rstat rup perfmeter
rusersd	100002	rusers
nfs	100003	nfsprog
ypserv	100004	ypprog
mountd	100005	mount showmount
ypbind	100007
walld	100008	rwall shutdown
yppasswdd	100009	yppasswd
etherstatd	100010	etherstat
rquotad	100011	rquotaprog quota rquota
sprayd	100012	spray
3270_mapper	100013
rje_mapper	100014
selection_svc	100015	selnsvc
database_svc	100016
rexd	100017	rex
alis	100018
sched	100019
llockmgr	100020
nlockmgr	100021
x25.inr	100022
statmon	100023
status	100024
bootparam	100026
ypupdated	100028	ypupdate
keyserv	100029	keyserver
.TE
.ft R
.DT
.LP
.SH FILES
.B /etc/rpc
.SH "SEE ALSO"
.BR getrpcent (3N)
