.\" @(#)sunview.5 1.1 92/07/30 SMI;
.TH SUNVIEW 5 "31 January 1990"
.SH NAME
sunview \- initialization file for SunView
.SH SYNOPSIS
.B ~/.sunview
.br
.B ~/.suntools
.br
.B /usr/lib/.sunview
.SH DESCRIPTION
.IX "sunview init" "" "\fLsunview\fP \(em initialization file for SunView" ""
.IX SunView "initialization file for"
.IX initial "SunView initialization file"
.IX start "SunView initialization file"
.LP
If the file
.B .sunview
or
.B .suntools
is present in a user's home directory when the user starts up
.BR sunview (1),
.B sunview
starts up the \*(lqtools\*(rq, or window-based applications
listed in this file.  You can use a
.B .sunview
or
.B .suntools
file to customize your desktop layout.
If a
.B .sunview
or
.B .suntools
file is not present in the user's home directory,
.B sunview
starts up the tools listed in
.BR /usr/lib/.sunview .
.LP
Each line of a
.B .sunview
or
.B .suntools
file has the format:
.LP
.RS
.I SunView-tool
[
.I options
]
.RE
.LP
.I SunView-tool
is in the form of a command line, although no shell interpretation is done.
.I options
are command line options which may include SunView generic tool arguments
(see
.BR sunview (1)
for a description of generic tool arguments).
Lines beginning with the
.RB ` # '
character are considered comments and are ignored.
.SH EXAMPLES
.LP
Here is a sample
.B .sunview
file:
.LP
.nf
.ft B
#
#	sample .sunview file
#	
cmdtool    -Wp   0   0 -WP    0   0 -Wh  3 -Ww 80 -Wl "<< CONSOLE >>" -WL "console" -C 
clock      -Wp 497  32 -WP  704   0 -Wi -Wh 1
cmdtool    -Wp   0  71 -WP  772   0 -Wi -Wh 44 -Ww 80
textedit   -Wp 259  98 -WP  840   0 -Wi
mailtool   -Wp 492  71 -WP  908   0 -Wi
.ft
.fi
.SH SEE ALSO
.BR sunview (1),
.BR toolplaces (1)
