#
# @(#)Makefile 1.1 92/07/30 Copyr 1987 Sun Micro
#
DESTDIR=

LISTS=	lost.found root.usr usr.debug usr.demo \
	usr.diag.sun3 usr.diag.sun3x usr.diag.sun4 usr.diag.sun4c \
	usr.games usr.install usr.kvm \
	usr.man usr.net usr.secure \
	kvm.sys kvm.exclude install.exclude usr.src usr.shlib \
	usr.sunview_prog usr.sunview_users \
	usr.text usr.vsys usr.uucp usr.vtroff usr.graphics.sun2 \
	usr.graphics.sun3 usr.graphics.sun3x usr.graphics.sun4 \
	usr.graphics.sun4c usr.tli usr.rfs

all: ${LISTS}

clean:

install: ${LISTS}

${LISTS}:
