#
# @(#)Makefile.arch 1.1 92/07/30 SMI
#
#Copyright (c) 1987 by Sun Microsystems, Inc.
#

m-mc68010 = m68k
m-mc68020 = m68k
m-sparc = sparc
m-sunrise = sparc

ARCH = $(m$(TARGET_MACH))
MACH = $(ARCH)

a-sun2 = sun2
a-sun3 = sun3
a-sun3x = sun3x
a-sun4 = sun4

TARGET = $(a$(TARGET_ARCH))

