.\" @(#)getpagesize.2 1.1 92/07/30 SMI; from UCB 4.2
.TH GETPAGESIZE 2 "21 January 1990"
.SH NAME
getpagesize \- get system page size
.SH SYNOPSIS
.nf
.ft B
int getpagesize(\|)
.ft R
.fi
.IX  getpagesize()  "" "\fLgetpagesize()\fP \(em get system page size"
.IX  "memory management"  getpagesize()  ""  \fLgetpagesize()\fP
.IX  "page size, get \(em \fLgetpagesize()\fR"
.IX  "system page size, get \(em \fLgetpagesize()\fR"
.SH DESCRIPTION
.LP
.B getpagesize(\|)
returns the number of bytes in a page.
Page granularity is the granularity of many of the memory
management calls.
.LP
The page size is a
.I system
page size and may not be the same as the underlying
hardware page size.
.SH SEE ALSO
.BR pagesize (1),
.BR brk (2)
