#  @(#)Makefile 1.1 92/07/30 SMI;
#
#  Description file for making the section 2 manual page sources.
#
#  NOTE that the list of filenames in the description file must be
#  kept up to date with the actual manual pages, including ".so" files.
 
HERE=man2
  
# --------------------------------------------------------------- #

FILES=	\
Intro.2 intro.2 List.2 list.2 \
WEXITSTATUS.2v WIFEXITED.2v WIFSIGNALED.2v WIFSTOPPED.2v WSTOPSIG.2v \
WTERMSIG.2v _exit.2v accept.2 access.2v acct.2v adjtime.2 \
async_daemon.2 audit.2 auditon.2 auditsvc.2 bind.2 brk.2 chdir.2v \
chmod.2v chown.2v chroot.2 close.2v connect.2 creat.2v dup.2v dup2.2v \
execve.2v exit.2v fchdir.2v fchmod.2v fchown.2v fchroot.2 fcntl.2v \
flock.2 fork.2v fpathconf.2v fstat.2v fstatfs.2 fsync.2 ftruncate.2 \
getauid.2 getdents.2 getdirentries.2 getdomainname.2 getdtablesize.2 \
getegid.2v geteuid.2v getgid.2v getgroups.2v gethostid.2 gethostname.2 \
getitimer.2 getmsg.2 getpagesize.2 getpeername.2 getpgrp.2v getpid.2v \
getppid.2v getpriority.2 getrlimit.2 getrusage.2 getsockname.2 \
getsockopt.2 gettimeofday.2 getuid.2v ioctl.2 kill.2v killpg.2 link.2v \
listen.2 lseek.2v lstat.2v mctl.2 mincore.2 mkdir.2v mkfifo.2v mknod.2v \
mmap.2 mount.2v mprotect.2 msgctl.2 msgget.2 msgop.2 msgrcv.2 msgsnd.2 \
msync.2 munmap.2 nfssvc.2 open.2v pathconf.2v pipe.2v poll.2 profil.2 \
ptrace.2 putmsg.2 quotactl.2 read.2v readlink.2 readv.2v reboot.2 \
recv.2 recvfrom.2 recvmsg.2 rename.2v rmdir.2v sbrk.2 select.2 semctl.2 \
semget.2 semop.2 send.2 sendmsg.2 sendto.2 setaudit.2 setauid.2 \
setdomainname.2 setgroups.2v sethostname.2 setitimer.2 setpgid.2v \
setpgrp.2v setpriority.2 setregid.2 setreuid.2 setrlimit.2 setsid.2v \
setsockopt.2 settimeofday.2 setuseraudit.2 shmat.2 shmctl.2 shmdt.2 \
shmget.2 shmop.2 shutdown.2 sigblock.2 sigmask.2 sigpause.2v \
sigpending.2v sigprocmask.2v sigsetmask.2 sigstack.2 sigsuspend.2v \
sigvec.2 socket.2 socketpair.2 stat.2v statfs.2 swapon.2 symlink.2 \
sync.2 syscall.2 sysconf.2v tell.2v truncate.2 umask.2v umount.2v \
uname.2v unlink.2v unmount.2v ustat.2 utimes.2 vadvise.2 vfork.2 \
vhangup.2 wait.2v wait3.2v wait4.2v waitpid.2v write.2v writev.2v

# --------------------------------------------------------------- #

include ../Makefile.master
