.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\" @(#)sigsetmask.2 1.1 92/07/30 SMI; from UCB 6.3 5/14/86
.TH SIGSETMASK 2 "21 January 1990"
.SH NAME
sigsetmask \- set current signal mask
.SH SYNOPSIS
.LP
.nf
.ft B
#include <signal.h>
.ft
.fi
.LP
.nf
.ft B
int sigsetmask(mask)
int mask;
.ft
.fi
.IX  sigsetmask()  ""  "\fLsigsetmask()\fP \(em set current signal mask"
.IX  signals  sigsetmask()  ""  \fLsigsetmask()\fP
.IX  set "current signal mask \(em \fLsigsetmask()\fP"
.IX  "mask, set current signal \(em \fLsigsetmask()\fP"
.SH DESCRIPTION
.LP
.B sigsetmask(\|)
sets the set of signals currently being blocked from delivery according to
.IR mask .
A signal is blocked if the appropriate bit in
.I mask
is set.  The macro
.BR sigblock (2)
is provided to construct the mask for a given
.IR signum .
.LP
The system silently disallows blocking
.SB SIGKILL
and
.BR \s-1SIGSTOP\s0 .
.SH RETURN VALUES
.LP
.B sigsetmask(\|)
returns
the previous signal mask.
.SH SEE ALSO
.BR kill (2V),
.BR sigblock (2),
.BR sigpause (2V),
.BR sigvec (2),
.BR signal (3V)
