.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\" @(#)sync.2 1.1 92/07/30 SMI; from UCB 6.2 6/30/85
.TH SYNC 2 "21 January 1990"
.SH NAME
sync \- update super-block
.SH SYNOPSIS
.B sync()
.IX  sync()  ""  "\fLsync()\fP \(em update super block"
.IX  "system operation support"  sync()  ""  \fLsync()\fP
.IX  "super block, update \(em \fLsync()\fR"
.IX  "update super block \(em \fLsync()\fR"
.SH DESCRIPTION
.LP
.B sync(\|)
writes out all information in core
memory that should be on disk.
This includes modified super blocks,
modified inodes, and delayed block I/O.
.LP
.B sync(\|)
should be used by programs that examine a file system,
for example
.BR fsck (8),
.BR df (1V),
etc.
.B sync(\|)
is mandatory before a boot.
.SH "SEE ALSO"
.BR fsync (2),
.BR cron (8)
.SH BUGS
.LP
The writing, although scheduled, is not necessarily
complete upon return from
.BR sync(\|) .
