#
# @(#)Makefile 1.1 92/07/30 SMI
#

HDRS =	err.h file_err.h hash.h isafile.h list.h mount.h nse_rpc.h \
	param.h rev_tree.h searchlink.h stdio.h tfs_calls.h tfs_mount.h \
	types.h util.h

all:	${HDRS}
