#
# @(#)Makefile 1.1 92/07/30 SMI
#
# Copyright (c) 1987 by Sun Microsystems, Inc.
#

CPPFLAGS$(TARGET_MACH) += -DLOCORE -I../../sys/common/m68k
MD_HDRS =
CSRCS =
MD_CSRC = $(CSRCS:%.c=$(ARCH)/%.c)
ASSRCS =
MD_ASSRC =
