#!/bin/csh -f
#
#
#  	%Z%%M% %I% %E% %U%
#
#  	Copyright (c) 1990 by Sun Microsystems, Inc.
#
set RELEASE_DIR = /usr/shbam2/sim/release
set RELEASE_SRC = $RELEASE_DIR/src
set RELEASE_LIB = $RELEASE_DIR/sun4
set HAWK2_DIAG_DIR = /usr/hawk2/diags/hk2_fe/lib
set TOOLS_DIR = /usr/hawk2/firmware/fw_tools/sun4/src/bin/intel/include
#
# SCCS edit files
#
echo "sccs edit -k gtmcb.h hk_comm.h hk_public.h libhcom.a"
sccs edit -k gtmcb.h hk_comm.h hk_public.h libhcom.a
#
# copy files from the /usr/shbam2/sim directory
#
echo "cp $RELEASE_SRC/gtmcb.h ."
cp $RELEASE_SRC/gtmcb.h .
echo "cp $RELEASE_SRC/hk_comm.h ."
cp $RELEASE_SRC/hk_comm.h .
echo "cp $RELEASE_SRC/hk_public.h ."
cp $RELEASE_SRC/hk_public.h .
#
# copy libraries from /usr/shbam2/sim directory
#
echo "chmod +w libhcom.a"
chmod +w libhcom.a
echo "cp $RELEASE_LIB/libhcom.a ."
cp $RELEASE_LIB/libhcom.a .
#
# SCCS edit intel header files
#
#echo "sccs get -k n10aouth.h scnhdr.h"
#sccs get -k n10aouth.h scnhdr.h
#
# copy from the /usr/hawk2/firmware/fw_tools/sun4/src/bin/intel/include
# directory
#
#echo "cp $TOOLS_DIR/n10aouth.h ."
#cp $TOOLS_DIR/n10aouth.h .
#echo "cp $TOOLS_DIR/scnhdr.h ."
#cp $TOOLS_DIR/scnhdr.h .

