#
# @(#)Makefile 1.1 92/07/30 SMI
#
# This makefile creates the distributed kernel objects and
# configuration files.

ARCH=	sun4
MACH=	sparc
CONFDIR= ../../conf.common
MACHINES= DL DL110 SDST110 XYXT260 XDXT260 GENERIC_SMALL \
	DL330 SDST330 SDST470 IDST390 IDST490
include ../../conf.common/Makefile.install
