#!/bin/sh

# @(#)evqload.sh 1.2 91/09/14
#
# Copyright (c) 1991 by Sun Microsystems, Inc.

#  Executed by loadmodule to create the /dev/evq device entry

if [ $4 != 0 ]; then
	if [ -f /dev/evq ]; then
		rm /dev/evq
	fi
		
	/etc/mknod /dev/evq c $4 0
	chmod 666 /dev/evq
fi
