#!/bin/sh

# @(#)winlockload.sh 1.2 91/09/14
#
# Copyright (c) 1991 by Sun Microsystems, Inc.

#  Executed by loadmodule to create the /dev/winlock device entry

if [ $4 != 0 ]; then
	if [ -f /dev/winlock ]; then
		rm /dev/winlock
	fi
		
	/etc/mknod /dev/winlock c $4 0
	chmod 666 /dev/winlock
fi
