#
# @(#)Makefile 1.1 92/07/30 SMI
#
# This makefile creates the distributed kernel objects and
# configuration files.

ARCH=	sun3x
MACH=	mc68020
CONFDIR= ../../conf.common
MACHINES= DL80 DL470 SDST80 XYXT470 XDXT470 GENERIC_SMALL
include ../../conf.common/Makefile.install
