# @(#)Makefile	1.1 7/30/92 SMI	
#
# Arch-specific kadb makefile
#
ARCH =	sun4m
MACH=	sparc
ARCHLIBS=${LIBPROM}

include ../common/Makefile.com

# DO NOT DELETE THIS LINE -- make depend uses it

kadb.o: ../common/kadb.c
kadb.o: ../../../lang/adb/common/adb.h
kadb.o: ../../sun4m/a.out.h
kadb.o: ../../sys/exec.h
kadb.o: /usr/include/stab.h
kadb.o: ../../sys/param.h
kadb.o: ../../sun4m/machine/param.h
kadb.o: ../../sys/signal.h
kadb.o: ../../vm/faultcode.h
kadb.o: ../../sys/stdtypes.h
kadb.o: ../../sys/types.h
kadb.o: ../../sys/stdtypes.h
kadb.o: ../../sys/sysmacros.h
kadb.o: ../../sys/dir.h
kadb.o: ../../sun4m/machine/psl.h
kadb.o: ../../sun4m/machine/pte.h
kadb.o: ../../sys/types.h
kadb.o: /usr/include/vfork.h
kadb.o: ../../sys/core.h
kadb.o: ../../sys/exec.h
kadb.o: ../../sun4m/machine/reg.h
kadb.o: /usr/include/ctype.h
kadb.o: /usr/include/malloc.h
kadb.o: ../../../lang/adb/common/../sparc/sparc.h
kadb.o: ../../sys/vmparam.h
kadb.o: ../../sun4m/machine/vmparam.h
kadb.o: ../../sun4m/machine/param.h
kadb.o: ../../sun4m/machine/mmu.h
kadb.o: ../../sys/types.h
kadb.o: ../../../lang/adb/common/process.h
kadb.o: ../../../lang/adb/common/symtab.h
kadb.o: ../common/pf.h
kadb.o: ../../debug/debugger.h
kadb.o: /usr/include/setjmp.h
kadb.o: /usr/include/machine/setjmp.h
kadb.o: ../../debug/debug.h
kadb.o: ../../mon/sunromvec.h
kadb.o: ../../sys/types.h
kadb.o: ../../sys/param.h
kadb.o: ../../mon/openprom.h
kadb.o: ../../sys/types.h
kadb.o: ../../sun4m/machine/romvec.h
kadb.o: ../../sys/errno.h
kadb.o: ../../sys/file.h
kadb.o: ../../sys/types.h
kadb.o: ../../sys/fcntlcom.h
kadb.o: ../../sys/stdtypes.h
kadb.o: ../../sys/stat.h
kadb.o: ../../sys/types.h
kadb.o: ../../sys/ptrace.h
kadb.o: ../../sun4m/machine/cpu.h
kadb.o: ../../mon/sunromvec.h
genpf.o: ../common/genpf.c
genpf.o: ../common/pf.h
genpf.o: /usr/include/stdio.h
genpf.o: /usr/include/ctype.h
