#! /bin/sh
#
#	%Z%%M% %I% %E% SMI; from S5R3 1.3
#
echo "`2>/dev/null cat errs|wc -l` entries have been compiled"
echo
2>/dev/null cat errs|grep -iv "^mkdir"|grep -iv "^create"|grep -iv "^link"|grep -vi terminfo.src|grep -vi touch|grep -vi "working"
if [ $? -ne 0 ] ;
	then
		echo "	No Errors"
fi
