.\" @(#)getpw.3 1.1 92/07/30 SMI; from UCB 6.2 5/27/86
.TH GETPW 3  "6 October 1987"
.SH NAME
getpw \- get name from uid
.SH SYNOPSIS
.LP
.nf
.ft B
getpw(uid, buf)
char *buf;
.ft 
.fi
.IX  "getpw()"  ""  "\fLgetpw()\fP \(em get name from uid"
.SH DESCRIPTION
.LP
.B getpw(\|)
is obsoleted by
.BR getpwent (3V).
.ft R
.LP
.B getpw(\|)
searches the password file for
the (numerical)
.IR uid ", and fills in " "buf"
with the corresponding line;
it returns non-zero if
.IR uid ""
could not
be found.
The line is
null-terminated.
.SH FILES
.PD 0
.TP 20
.B /etc/passwd
.PD
.SH "SEE ALSO"
.BR getpwent (3V),
.BR passwd (5)
.SH DIAGNOSTICS
Non-zero
return on error.
