.\" @(#)getwd.3 1.1 92/07/30 SMI; from UCB 4.2
.TH GETWD 3 "18 January 1988"
.SH NAME
getwd \- get current working directory pathname
.SH SYNOPSIS
.nf
.B "#include <sys/param.h>"
.sp
.B char *getwd(pathname)
.B char pathname[\s-1MAXPATHLEN\s0];
.fi
.IX  "getwd()"  ""  "\fLgetwd()\fP \(em get current working directory pathname"
.IX  get "current working directory pathname \(em \fLgetwd()\fP"
.IX  "current directory"  "get pathname"  ""  "get pathname \(em \fLgetwd()\fP"
.IX  "working directory"  "get pathname"  ""  "get pathname \(em \fLgetwd()\fP"
.SH DESCRIPTION
.LP
.B getwd(\|)
copies the absolute pathname of the current working directory to
.I pathname
and returns a pointer to the result.
.SH DIAGNOSTICS
.B getwd(\|)
returns zero and places a message in
.I pathname
if an error occurs.
