#  @(#)Makefile 1.1 92/07/30 SMI;
#
#  Description file for making the section 3 manual page sources.
#
#  NOTE that the list of filenames in the description file must be
#  kept up to date with the actual manual pages, including ".so" files.

HERE=man3

# --------------------------------------------------------------- #

FILES= \
Intro.3 intro.3 List.3 list.3 \
Intro.3l intro.3l List.3l list.3l \
Intro.3m intro.3m List.3m list.3m \
Intro.3r intro.3r List.3r list.3r \
CHECK.3l HUGE.3m HUGE_VAL.3m MINSTACKSZ.3l MONITOR.3l MSG_RECVALL.3l \
SAMECV.3l SAMEMON.3l SAMETHREAD.3l STKTOP.3l _crypt.3 _tolower.3v \
_toupper.3v a64l.3 abort.3 abs.3 acos.3m acosh.3m addch.3v addch.3x \
addexportent.3 addmntent.3 addstr.3v addstr.3x agt_create.3l \
agt_enumerate.3l agt_trap.3l aint.3m aiocancel.3 aioread.3 aiowait.3 \
aiowrite.3 alarm.3c alarm.3v alloca.3 alphasort.3 anint.3m annuity.3m \
arc.3x asctime.3 asctime.3v asin.3m asinh.3m assert.3v atan.3m atan2.3m \
atanh.3m atof.3 atoi.3 atol.3 attroff.3v attron.3v attrset.3v audit.3 \
audit_args.3 audit_text.3 auth_destroy.3n authdes_create.3n \
authdes_getcred.3n authdes_getucred.3n authnone_create.3n \
authunix_create.3n authunix_create_default.3n baudrate.3v bcmp.3 \
bcopy.3 beep.3v bessel.3m bindresvport.3n bootparam.3r box.3v box.3x \
bsearch.3 bstring.3 byteorder.3n bzero.3 cabs.3m calloc.3 callrpc.3n \
catclose.3c catgetmsg.3c catgets.3c catopen.3c cbreak.3v \
cbrt.3m ceil.3m cfgetispeed.3v cfgetospeed.3v cfree.3 cfsetispeed.3v \
cfsetospeed.3v circle.3x class.3m clear.3v clear.3x clearerr.3s \
clearerr.3v clearok.3v clearok.3x clnt_broadcast.3n clnt_call.3n \
clnt_control.3n clnt_create.3n clnt_create_vers.3n clnt_destroy.3n \
clnt_freeres.3n clnt_geterr.3n clnt_pcreateerror.3n clnt_perrno.3n \
clnt_perror.3n clnt_spcreateerror.3n clnt_sperrno.3n clnt_sperror.3n \
clntraw_create.3n clnttcp_create.3n clntudp_bufcreate.3n \
clntudp_create.3n clock.3c closedir.3v closelog.3 closepl.3x \
clrtobot.3v clrtobot.3x clrtoeol.3v clrtoeol.3x compound.3m cont.3x \
control.3 conv.3v copysign.3m cos.3m cosh.3m crmode.3x crypt.3 \
ctermid.3s ctermid.3v ctime.3v ctype.3v curses.3v curses.3x \
curses_functions.3v curses_functions.3x cuserid.3s cuserid.3v \
cv_broadcast.3l cv_create.3l cv_destroy.3l cv_enumerate.3l cv_notify.3l \
cv_send.3l cv_wait.3l cv_waiters.3l dbm.3x dbm_clearerr.3 dbm_close.3 \
dbm_delete.3 dbm_error.3 dbm_fetch.3 dbm_firstkey.3 dbm_nextkey.3 \
dbm_open.3 dbm_store.3 dbmclose.3x dbminit.3x decimal_to_double.3 \
decimal_to_extended.3 decimal_to_floating.3 decimal_to_single.3 \
delay_output.3v delch.3v delch.3x delete.3x deleteln.3v deleteln.3x \
delwin.3v delwin.3x directory.3v dlclose.3x \
dlerror.3x dlopen.3x dlsym.3x dn_comp.3 dn_expand.3 double_to_decimal.3 \
doupdate.3v drand48.3 dysize.3 dysize.3v echo.3v echo.3x \
econvert.3 ecvt.3 edata.3 encrypt.3 end.3 endac.3 endexportent.3 \
endfsent.3 endgraent.3 endgrent.3v endhostent.3n endmntent.3 \
endnetent.3n endnetgrent.3n endprotoent.3n endpwaent.3 endpwent.3v \
endrpcent.3n endservent.3n endttyent.3 endusershell.3 endwin.3v \
endwin.3x environ.3 erand48.3 erase.3v erase.3x erasechar.3v erf.3m \
erfc.3m errno.3 etext.3 ether.3r ether_aton.3n ether_hostton.3n \
ether_line.3n ether_ntoa.3n ether_ntohost.3n ethers.3n exc_bound.3l \
exc_handle.3l exc_notify.3l exc_on_exit.3l exc_raise.3l exc_unhandle.3l \
exc_uniqpatt.3l execl.3v execle.3v execlp.3v execv.3v execvp.3v exit.3 \
exp.3m exp10.3m exp2.3m expm1.3m exportent.3 extended_to_decimal.3 \
fabs.3m fclose.3v fconvert.3 fcvt.3 fdopen.3s fdopen.3v feof.3s feof.3v \
ferror.3s ferror.3v fetch.3x fflush.3s fflush.3v ffs.3 fgetc.3s \
fgetc.3v fgetgraent.3 fgetgrent.3v fgetpwaent.3 fgetpwent.3 \
fgetpwent.3v fgets.3s file.3 file_to_decimal.3 fileno.3s fileno.3v \
finite.3m firstkey.3x fixterm.3v flash.3v floating_to_decimal.3 \
floatingpoint.3 floor.3m flushinp.3v fmod.3m fopen.3s fopen.3v \
fp_class.3m fprintf.3s fprintf.3v fputc.3s fputs.3s fread.3s free.3 \
freopen.3s freopen.3v frexp.3m fscanf.3s fscanf.3v fseek.3s ftell.3s \
ftime.3c ftime.3v ftok.3 ftw.3 func_to_decimal.3 fwrite.3s gamma.3m \
gcd.3x gconvert.3 gcvt.3 get.3 get.3r get_myaddress.3n getacdir.3 \
getacflg.3 getacinfo.3 getacmin.3 getauditflags.3 getauditflagsbin.3 \
getauditflagschar.3 getc.3s getc.3v getcap.3x getch.3v getch.3x \
getchar.3s getchar.3v getcwd.3v getenv.3v getexportent.3 getexportopt.3 \
getfaudflgs.3 getfauditflags.3 getfsent.3 getfsfile.3 getfsspec.3 \
getfstype.3 getgraent.3 getgranam.3 getgrent.3v getgrgid.3v getgrnam.3v \
gethostbyaddr.3n gethostbyname.3n gethostent.3n getlogin.3v getmntent.3 \
getnetbyaddr.3n getnetbyname.3n getnetent.3n getnetgrent.3n \
getnetname.3n getopt.3 getpass.3v getprotobyname.3n getprotobynumber.3n \
getprotoent.3n getpublickey.3r getpw.3 getpwaent.3 getpwanam.3 \
getpwent.3v getpwnam.3v getpwuid.3v getrpcbyname.3n getrpcbynumber.3n \
getrpcent.3n getrpcport.3r gets.3s getsecretkey.3r getservbyname.3n \
getservbyport.3n getservent.3n getstr.3v getstr.3x getsubopt.3 \
gettext.3 gettmode.3v gettmode.3x getttyent.3 getttynam.3 \
getusershell.3 getw.3s getw.3v getwd.3 getyx.3v getyx.3x gmtime.3v \
grpauth.3 gsignal.3 gtty.3c has_ic.3v has_il.3v hasmntopt.3 havedisk.3r \
hcreate.3 hdestroy.3 host2netname.3n hsearch.3 htonl.3n htons.3n \
hyperbolic.3m hypot.3m idlok.3v ieee_flags.3m ieee_functions.3m \
ieee_handler.3m ieee_test.3m ieee_values.3m ilogb.3m inch.3v inch.3x \
index.3 inet.3n inet_addr.3n inet_lnaof.3n inet_makeaddr.3n \
inet_netof.3n inet_network.3n inet_ntoa.3n infinity.3m initgroups.3 \
initscr.3v initscr.3x initstate.3 innetgr.3n insch.3v insch.3x \
insertln.3v insertln.3x insque.3 intrflush.3v ipalloc.3r irint.3m \
isalnum.3v isalpha.3v isascii.3v isatty.3v iscntrl.3v isdigit.3v \
isgraph.3v isinf.3m islower.3v isnan.3m isnormal.3m isprint.3v \
ispunct.3v issecure.3 isspace.3v issubnormal.3m isupper.3v isxdigit.3v \
iszero.3m itom.3x j0.3m j1.3m jn.3m jrand48.3 key.3r \
key_decryptsession.3n key_encryptsession.3n key_gendes.3n \
key_setsecret.3n keypad.3v killchar.3v klm_prot.3r kvm_close.3k \
kvm_getcmd.3k kvm_getproc.3k kvm_getu.3k kvm_nextproc.3k kvm_nlist.3k \
kvm_open.3k kvm_read.3k kvm_setproc.3k kvm_write.3k l3tol.3c l64a.3 \
label.3x lcong48.3 ldaclose.3x ldahread.3x ldaopen.3x ldclose.3x \
ldexp.3m ldfcn.3 ldfhread.3x ldgetname.3x ldlinit.3x ldlitem.3x \
ldlread.3x ldlseek.3x ldnlseek.3x ldnrseek.3x ldnshread.3x ldnsseek.3x \
ldohseek.3x ldopen.3x ldrseek.3x ldshread.3x ldsseek.3x ldtbindex.3x \
ldtbread.3x ldtbseek.3x leaveok.3v leaveok.3x lfind.3 lgamma.3m line.3x \
linemod.3x localdtconv.3 localeconv.3 localtime.3v lockf.3 log.3m \
log10.3m log1p.3m log2.3m logb.3m longjmp.3 longjmp.3v longname.3v \
longname.3x lrand48.3 lsearch.3 ltol3.3c lwp_checkstkset.3l \
lwp_create.3l lwp_ctxinit.3l lwp_ctxmemget.3l lwp_ctxmemset.3l \
lwp_ctxremove.3l lwp_ctxset.3l lwp_datastk.3l lwp_destroy.3l \
lwp_enumerate.3l lwp_errstr.3l lwp_fpset.3l lwp_geterr.3l \
lwp_getregs.3l lwp_getstate.3l lwp_join.3l lwp_libcset.3l lwp_newstk.3l \
lwp_perror.3l lwp_ping.3l lwp_resched.3l lwp_resume.3l lwp_self.3l \
lwp_setpri.3l lwp_setregs.3l lwp_setstate.3l lwp_setstkcache.3l \
lwp_sleep.3l lwp_status.3l lwp_stkcswset.3l lwp_suspend.3l lwp_yield.3l \
madd.3x madvise.3 malloc.3v malloc_debug.3 malloc_verify.3 mallocmap.3 \
matherr.3m max_normal.3m max_subnormal.3m mblen.3 mbstowcs.3 mbtowc.3 \
mcmp.3x mdiv.3x memalign.3 memccpy.3 memchr.3 memcmp.3 memcpy.3 \
memory.3 memset.3 meta.3v mfree.3x min.3x min_normal.3m \
min_subnormal.3m mkstemp.3 mktemp.3 mlock.3 mlockall.3 modf.3m \
mon_break.3l mon_cond_enter.3l mon_create.3l mon_destroy.3l \
mon_enter.3l mon_enumerate.3l mon_exit.3l mon_waiters.3l moncontrol.3 \
monitor.3 monstartup.3 mount.3r mout.3x move.3v move.3x mp.3x mrand48.3 \
msg_enumrecv.3l msg_enumsend.3l msg_recv.3l msg_reply.3l msg_send.3l \
msub.3x msync.3 mtox.3x mult.3x munlock.3 munlockall.3 mvaddch.3v \
mvaddstr.3v mvcur.3v mvcur.3x mvdelch.3v mvgetch.3v mvgetstr.3v \
mvinch.3v mvinsch.3v mvprintw.3v mvscanw.3v mvwaddch.3v mvwaddstr.3v \
mvwdelch.3v mvwgetch.3v mvwgetstr.3v mvwin.3v mvwinch.3v mvwinsch.3v \
mvwprintw.3v mvwscanw.3v ndbm.3 netname2host.3n netname2user.3n \
newpad.3v newterm.3v newwin.3v newwin.3x nextafter.3m nextkey.3x \
nice.3c nice.3v nint.3m nis.3r nl.3v nl.3x nl_init.3v nl_lang.3c \
nl_langinfo.3c nlist.3v nlm_prot.3r nocbreak.3v nocrmode.3x nodelay.3v \
noecho.3v noecho.3x nonl.3v nonl.3x noraw.3v noraw.3x nrand48.3 \
ntohl.3n ntohs.3n on_exit.3 opendir.3v openlog.3 openpl.3x optarg.3 \
optind.3 overlay.3v overlay.3x overwrite.3v overwrite.3x passwd2des.3r \
pause.3c pause.3v pclose.3s perror.3 plock.3 plot.3x pmap_getmaps.3n \
pmap_getport.3n pmap_rmtcall.3n pmap_set.3n pmap_unset.3n \
pnoutrefresh.3v pnp.3r pod_exit.3l pod_getexit.3l pod_getmaxpri.3l \
pod_getmaxsize.3l pod_setexit.3l pod_setmaxpri.3l point.3x popen.3s \
portmap.3n pow.3m pow.3x printf.3s printf.3v printw.3x prof.3 psignal.3 \
public.3r publickey.3r putc.3s putchar.3s putenv.3 putpwent.3 puts.3s \
putw.3s pwdauth.3 qsort.3 quiet_nan.3m rand.3c rand.3v random.3 raw.3v \
raw.3x rcmd.3n re_comp.3 re_exec.3 readdir.3v realloc.3 realpath.3 \
refresh.3v refresh.3x regex.3 regexp.3 registerrpc.3n remainder.3m \
remexportent.3 remque.3 res_init.3 res_mkquery.3 res_send.3 \
resetterm.3v resetty.3v resetty.3x resolver.3 rewind.3s rewinddir.3v \
rex.3r rexec.3n rindex.3 rint.3m rnusers.3r rpc.3n rpc_clnt_auth.3n \
rpc_clnt_calls.3n rpc_clnt_create.3n rpc_createrr.3n rpc_svc_calls.3n \
rpc_svc_create.3n rpc_svc_err.3n rpc_svc_reg.3n rpc_xdr.3n rpow.3x \
rquota.3r rresvport.3n rstat.3r rtime.3n ruserok.3n rusers.3r rwall.3r \
saveterm.3v savetty.3v savetty.3x scalb.3m scalbn.3m scandir.3 scanf.3s \
scanf.3v scanw.3v scanw.3x scroll.3v scroll.3x scrollok.3v scrollok.3x \
seconvert.3 secret.3r secure_rpc.3n seed48.3 seekdir.3v set_term.3v \
setac.3 setbuf.3s setbuf.3v setbuffer.3s setbuffer.3v setegid.3 \
setegid.3v seteuid.3 seteuid.3v setexportent.3 setfsent.3 setgid.3v \
setgraent.3 setgrent.3v sethostent.3n setjmp.3v setkey.3 setlinebuf.3s \
setlinebuf.3v setlocale.3v setlogmask.3 setmntent.3 setnetent.3n \
setnetgrent.3n setprotoent.3n setpwaent.3 setpwent.3v setpwfile.3v \
setrgid.3 setrgid.3v setrpcent.3n setruid.3 setruid.3v setscrreg.3v \
setservent.3n setstate.3 setterm.3v setterm.3x setttyent.3 setuid.3v \
setupterm.3v setusershell.3 setvbuf.3s setvbuf.3v sfconvert.3 \
sgconvert.3 sgetl.3v sigaction.3v sigaddset.3v sigdelset.3v \
sigemptyset.3v sigfillset.3v sigfpe.3 siginterrupt.3v sigismember.3v \
siglongjmp.3v signal.3v signaling_nan.3m signbit.3m significand.3m \
significant.3m sigsetjmp.3v sigsetops.3v sin.3m single_precision.3m \
single_to_decimal.3 sinh.3m sleep.3v sm_inter.3r space.3x spray.3r \
sprintf.3s sprintf.3v sputl.3v sqrt.3m srand.3c srand.3v srand48.3 \
srandom.3 sscanf.3s sscanf.3v ssignal.3 standend.3v standend.3x \
standout.3v standout.3x stdio.3s stdio.3v store.3x strcasecmp.3 \
strcat.3 strchr.3 strcmp.3 strcoll.3 strcpy.3 strcspn.3 strdup.3 \
strftime.3v string.3 string_to_decimal.3 strings.3 strlen.3 \
strncasecmp.3 strncat.3 strncmp.3 strncpy.3 strpbrk.3 strptime.3v \
strrchr.3 strspn.3 strstr.3 strtod.3 strtok.3 strtol.3 strxfrm.3 \
stty.3c subwin.3v subwin.3x svc_destroy.3n svc_fds.3n svc_fdset.3n \
svc_freeargs.3n svc_getargs.3n svc_getcaller.3n svc_getreq.3n \
svc_getreqset.3n svc_register.3n svc_run.3n svc_sendreply.3n \
svc_unregister.3n svcerr_auth.3n svcerr_decode.3n svcerr_noproc.3n \
svcerr_noprog.3n svcerr_progvers.3n svcerr_systemerr.3n \
svcerr_weakauth.3n svcfd_create.3n svcraw_create.3n svctcp_create.3n \
svcudp_bufcreate.3n svcudp_create.3n swab.3 sys_errlist.3 sys_nerr.3 \
sys_siglist.3 syslog.3 system.3 t_accept.3n t_alloc.3n t_bind.3n \
t_close.3n t_connect.3n t_error.3n t_free.3n t_getinfo.3n t_getstate.3n \
t_listen.3n t_look.3n t_open.3n t_optmgmt.3n t_rcv.3n t_rcvconnect.3n \
t_rcvdis.3n t_rcvrel.3n t_rcvudata.3n t_rcvuderr.3n t_snd.3n \
t_snddis.3n t_sndrel.3n t_sndudata.3n t_sync.3n t_unbind.3n tan.3m \
tanh.3m tcdrain.3v tcflow.3v tcflush.3v tcgetattr.3v tcgetpgrp.3v \
tcsendbreak.3v tcsetattr.3v tcsetpgrp.3v tdelete.3 telldir.3v \
tempnam.3s termcap.3x termios.3v textdomain.3 tfind.3 tgetent.3x \
tgetflag.3x tgetnum.3x tgetstr.3x tgoto.3x time.3c time.3v timegm.3v \
timelocal.3v times.3c times.3v timezone.3c tmpfile.3s tmpnam.3s \
toascii.3v tolower.3v touchwin.3v touchwin.3x toupper.3v tputs.3x \
traceoff.3v traceon.3v trig.3m tsearch.3 ttyname.3v ttyslot.3v twalk.3 \
typeahead.3v tzset.3v tzsetwall.3v ualarm.3 ulimit.3c unctrl.3v \
unctrl.3x ungetc.3s user2netname.3n usleep.3 utime.3v valloc.3 values.3 \
varargs.3 vfprintf.3s vfprintf.3v vlimit.3c vprintf.3s vprintf.3v \
vsprintf.3s vsprintf.3v vsyslog.3 vtimes.3c waddch.3v waddch.3x \
waddstr.3v waddstr.3x wattroff.3v wattron.3v wattrset.3v wclear.3v \
wclear.3x wclrtobot.3v wclrtobot.3x wclrtoeol.3v wclrtoeol.3x \
wcstombs.3 wctomb.3 wdelch.3v wdelch.3x wdeleteln.3v wdeleteln.3x \
werase.3v werase.3x wgetch.3v wgetch.3x wgetstr.3v wgetstr.3x winch.3v \
winch.3x winsch.3v winsch.3x winsertln.3v winsertln.3x wmove.3v \
wmove.3x wnoutrefresh.3v wprintw.3v wprintw.3x wrefresh.3v wrefresh.3x \
wscanw.3v wscanw.3x wsetscrreg.3v wstandend.3v wstandend.3x \
wstandout.3v wstandout.3x xdecrypt.3r xdr.3n \
xdr_accepted_reply.3n xdr_admin.3n xdr_array.3n xdr_authunix_parms.3n \
xdr_bool.3n xdr_bytes.3n xdr_callhdr.3n xdr_callmsg.3n xdr_char.3n \
xdr_complex.3n xdr_create.3n xdr_destroy.3n xdr_double.3n xdr_enum.3n \
xdr_float.3n xdr_free.3n xdr_getpos.3n xdr_inline.3n xdr_int.3n \
xdr_long.3n xdr_opaque.3n xdr_opaque_auth.3n xdr_pamp.3n \
xdr_pmaplist.3n xdr_pointer.3n xdr_reference.3n xdr_rejected_reply.3n \
xdr_replymsg.3n xdr_setpos.3n xdr_short.3n xdr_simple.3n xdr_string.3n \
xdr_u_char.3n xdr_u_int.3n xdr_u_long.3n xdr_u_short.3n xdr_union.3n \
xdr_vector.3n xdr_void.3n xdr_wrapstring.3n xdrmem_create.3n \
xdrrec_create.3n xdrrec_endofrecord.3n xdrrec_eof.3n \
xdrrec_readbytes.3n xdrrec_skiprecord.3n xdrstdio_create.3n xencrypt.3r \
xprt_register.3n xprt_unregister.3n xtom.3x y0.3m y1.3m yn.3m yp.3r \
yp_all.3n yp_bind.3n yp_first.3n yp_get_default_domain.3n yp_master.3n \
yp_match.3n yp_next.3n yp_order.3n yp_unbind.3n yp_update.3n ypclnt.3n \
yperr_string.3n yppasswd.3r ypprot_err.3n ypupdate.3n

# --------------------------------------------------------------- #

include ../Makefile.master
