.\" @(#)psignal.3 1.1 92/07/30 SMI; from UCB 4.2
.TH PSIGNAL 3 "22 November 1987"
.SH NAME
psignal, sys_siglist \- system signal messages
.SH SYNOPSIS
.nf
.B psignal(sig, s)
.B unsigned sig;
.B char *s;
.LP
.B char *sys_siglist[\|];
.fi
.IX  "psignal()"  ""  "\fLpsignal()\fP \(em system signal messages"
.IX  "sys_siglist()"  ""  "\fLsys_siglist()\fP \(em system signal messages"
.IX  "system signal messages"  psignal()  ""  "\fLpsignal()\fP"
.IX  "system signal messages"  sys_siglist()  ""  "\fLsys_siglist()\fP"
.IX  "signal messages"  psignal()  "" "\fLpsignal()\fP"
.IX  "signal messages"  sys_siglist() "" "\fLsys_siglist()\fP"
.IX  messages  "system signal"
.SH DESCRIPTION
.LP
.B psignal(\|)
produces a short message
on the standard error file
describing the indicated signal.
First the argument string
.I s
is printed, then a colon, then the name of the signal
and a
.SM NEWLINE\s0.
Most usefully, the argument string is the name
of the program which incurred the signal.
The signal number should be from among those found
in
.BR <signal.h> .
.LP
To simplify variant formatting
of signal names, the vector of message strings
.B sys_siglist(\|)
is provided;
the signal number
can be used as an index in this table to get the
signal name without the newline.
The define
.SB NSIG
defined in
.B <signal.h>
is the number of messages provided for in the table;
it should be checked because new
signals may be added to the system before
they are added to the table.
.SH "SEE ALSO"
.BR perror (3),
.BR signal (3V)
