.\" @(#)putpwent.3 1.1 92/07/30 SMI; from S5
.TH PUTPWENT 3 "6 October 1987"
.SH NAME
putpwent \- write password file entry
.SH SYNOPSIS
.nf
.B #include <pwd.h>
.LP
.B int putpwent(p, f)
.B struct passwd \(**p;
.B \s-1FILE\s+1 \(**f;
.fi
.SH DESCRIPTION
.IX  "putpwent()"  ""  "\fLputpwent()\fP \(em add password file entry"
.IX  "add password file entry \(em \fLputpwent()\fP"
.IX  "password file"  "add entry putpwent()"  ""  "add entry \(em \fLputpwent()\fP"
.B putpwent(\|)
is the inverse of
.BR getpwent (3V).
Given a pointer to a passwd
structure created by
.B getpwent(\|)
(or
.B getpwuid(\|)
or
.BR getpwnam ),
.B putpwent(\|)
writes a line on the stream
.IR f ,
which matches the format of lines in the password file
.BR /etc/passwd .
.SH FILES
.PD 0
.TP 20
.B /etc/passwd
.PD
.SH "SEE ALSO"
.BR getpwent (3V)
.SH DIAGNOSTICS
.LP
.B putpwent(\|)
returns non-zero if an error was
detected during its operation,
otherwise zero.
.SH WARNING
.LP
The above routine uses
.BR <stdio.h> ,
which increases the size of programs,
not otherwise using standard I/O, more
than might be expected.
.SH BUGS
.LP
This routine is of limited utility, 
since most password files are maintained as 
Network Information Service
(\s-1NIS\s0)
files, and cannot be updated with this routine.
.SH NOTES
.LP
The Network Information Service
(\s-1NIS\s0)
was formerly known as Sun Yellow Pages
(\s-1YP\s0). 
The functionality of the two remains the same;
only the name has changed.
