.\" @(#)ac.8 1.1 92/07/30 SMI; from UCB 4.1
.TH AC 8 "9 September 1987"
.SH NAME
ac \- login accounting
.SH SYNOPSIS
.B /usr/etc/ac
[
.B \-w
.I wtmp
] [
.B \-p
] [
.B \-d
] [
.I username
] .\|.\|.
.SH DESCRIPTION
.IX  "ac command"  ""  "\fLac\fP \(em login accounting"
.IX  "login accounting"  ""  "login accounting, display login record \(em \fLac\fP"
.IX  "accounting"  ""  "accounting, display login record \(em \fLac\fP"
.LP
.B ac
produces a printout giving connect time for each user who has logged
in during the life of the current
.I wtmp
file.  A total is also produced.
.LP
The accounting file
.B /var/adm/wtmp
is maintained by
.BR init (8)
and
.BR login (1).
Neither of these programs creates the file,
so if it does not exist no connect-time accounting is done.
To start accounting, it should be created with length 0.
On the other hand if the file is left undisturbed it will
grow without bound, so periodically any information
desired should be collected and the file truncated.
.SH OPTIONS
.TP
.BI \-w " wtmp"
Specify an alternate
.I wtmp 
file.
.TP
.B \-p
Print individual totals; without this option, only totals are printed.
.TP
.B \-d
Printout for each midnight to midnight period.  Any
.I people
will limit the printout to only the specified login names.  If no
.I wtmp
file is given,
.B /var/adm/wtmp
is used.
.SH FILES
.PD 0
.TP 20
.B /var/adm/wtmp
.PD
.SH "SEE ALSO"
.BR login (1),
.BR utmp (5V),
.BR init (8),
.BR sa (8)
