.\" @(#)acctmerg.8 1.1 92/07/30 SMI; from S5R2
.TH ACCTMERG 8 "17 January 1990"
.SH NAME
acctmerg \- merge or add total accounting files
.SH SYNOPSIS
.B /usr/lib/acct/acctmerg
[
.B \-aiptuv
] [
.IR filename \&.\|.\|.
]
.SH DESCRIPTION
.IX "acctmerg" "" "\fLacctmerg\fP \(em merge or add total accounting files" ""
.IX "accounting" "acctmerg" "accounting" "\fLacctmerg\fP"
.LP
.B acctmerg
reads its standard input and up to nine additional files,
all in the
.B tacct
format (see
.BR acct (5))
or an
.SM ASCII
version thereof.
It merges these inputs by adding records whose keys (normally user
.SM ID
and name)
are identical, and expects the inputs to be sorted on those keys.
.SH OPTIONS
.TP
.B \-a
Produce output in
.SM ASCII
version of
.BR tacct .
.TP
.B \-i
Input files are in
.SM ASCII
version of
.BR tacct .
.TP
.B \-p
Print input with no processing.
.TP
.B \-t
Produce a single record that totals all input.
.TP
.B \-u
Summarize by user
.SM ID\s0,
rather than user
.SM ID
and name.
.TP
.B \-v
Produce output in verbose
.SM ASCII
format,
with more precise notation for floating point numbers.
.SH EXAMPLES
.LP
The following sequence is useful for making \*(lqrepairs\*(rq
to any file kept in this format:
.LP
.RS
.nf
.ft B
acctmerg \|\-v \|<filename1 \|>filename2
	\fIedit file2 as desired\fR .\|.\|.
.ft B
acctmerg \|\-i \|<filename2 \|>filename1
.ft R
.fi
.RE
.SH SEE ALSO
.BR acctcom (1),
.BR acct (2V),
.BR acct (5),
.BR utmp (5V),
.BR acct (8),
.BR acctcms (8),
.BR acctcon (8),
.BR acctprc (8),
.BR acctsh (8),
.BR fwtmp (8),
.BR runacct (8)
