.\" @(#)add_services.8 1.1 92/07/30 SMI;
.TH ADD_SERVICES 8 "5 October 1990"
.SH NAME
add_services \- provide software installation services for any architecture
.SH SYNOPSIS
.B /usr/etc/install/add_services
.SH DESCRIPTION
.IX "add_services command" "" "\fLadd_services\fP command"
.LP
.B add_services
is a menu-based program to setup a system as a server and/or
to add additional software categories or other architecture releases.
It is used to provide support to diskless clients, dataless clients,
or just to act as a file server.
.B add_services
can only be run by the super-user.
.LP
.B add_services
updates the
.B /etc/exports
file
(see
.BR exports (5)
and
.BR exportfs (8))
to export the necessary file systems to become a file server.
After running 
.BR add_services ,
the system administrator should verify this file to make sure
that the new services have been exported to the correct groups.
.SH FILES
.PD 0
.TP 20
.B /etc/hosts
hosts database, host must be in this database or in the
Network Information Service
(\s-1NIS\s0)
hosts map
.TP
.B /etc/exports
database of exported file systems,
service related directories must be exported
.TP
.B /tftpboot
add_services sets up this directory in order to provide boot service to clients
.PD
.SH "SEE ALSO"
.BR exports (5),
.BR add_client (8),
.BR exportfs (8),
.BR rm_client (8),
.BR suninstall (8)
.LP
.TX INSTALL
.SH NOTES
.LP
The Network Information Service
(\s-1NIS\s0)
was formerly known as Sun Yellow Pages
(\s-1YP\s0). 
The functionality of the two remains the same;
only the name has changed.
