.\" @(#)bootparamd.8 1.1 92/07/30 SMI
.TH BOOTPARAMD 8 "14 December 1987"
.SH NAME
bootparamd \- boot parameter server
.SH SYNOPSIS
.B /usr/etc/rpc.bootparamd
[
.B \-d
]
.SH DESCRIPTION
.IX "bootparamd daemon" "" "\fLbootparamd\fP daemon"
.LP
.B bootparamd
is a server process that provides information to diskless clients
necessary for booting.
It first consults the local
.B /etc/bootparams
file for a client entry.
If the local bootparams file does not exist,
.B bootparamd
consults the corresponding
Network Information Service
(\s-1NIS\s0)
map.
.LP
.B bootparamd
can be invoked either by
.BR inetd (8C)
or by the user.
.SH OPTIONS
.TP
.B \-d
Display the debugging information.
.SH FILES
.PD 0
.TP 20
.B /etc/bootparams
.PD
.SH SEE ALSO
.BR inetd (8C)
.SH NOTES
.LP
The Network Information Service
(\s-1NIS\s0)
was formerly known as Sun Yellow Pages
(\s-1YP\s0). 
The functionality of the two remains the same;
only the name has changed.
