.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\" @(#)chown.8 1.1 92/07/30 SMI; from UCB 6.2 5/22/86
.TH CHOWN 8 "9 September 1987"
.SH NAME
chown \- change owner
.SH SYNOPSIS
.B /usr/etc/chown
[
.B \-fHR
] 
.IR owner [. group ] " filename " .\|.\|.
.SH DESCRIPTION
.IX  "chown command"  ""  "\fLchown\fP \(em change owner of file"
.IX  file  "change ownership"  file  "change ownership \(em \fLchown\fP"
.IX  "owner of file, change \(em \fLchown\fP"
.IX change "owner of file \(em \fLchown\fR"
.IX  "user ID"  "\fLchown\fR \(em change user ID of file"
.LP
.B chown
changes the owner of the
.IR filename s
to
.IR owner .
The owner may be either a decimal user
.SM ID
(\s-1UID\s0)
or
a login name found in the password file.
An optional
.I group
may also be specified.
The group may be either a decimal group
.SM ID
(\s-1GID\s0)
or a group name found in the \s-1GID\s0 file.
.LP
Only the super-user can change owner,
in order to simplify accounting procedures.
.SH OPTIONS
.TP
.B \-f
Do not report errors.
.TP
.B \-R
Recursively descend into directories
setting the ownership of all files in
each directory encountered.
When symbolic links are encountered, their ownership is changed,
but they are not traversed.
.SH FILES
.PD 0
.TP 20
.B /etc/passwd
password file
.PD
.SH "SEE ALSO"
.BR chgrp (1),
.BR chown (2V),
.BR group (5),
.BR passwd (5)
