.\" @(#)copy_home.8 1.1 92/07/30 SMI;
.TH COPY_HOME 8 "6 October 1989"
.SH NAME
copy_home \- fetch default startup files for new home directories
.SH SYNOPSIS
.BI /home/ groupname /copy_home\ 
.BI /home/ groupname\ 
.BI /home/ username 
.SH AVAILABILITY
.LP
Available only on Sun 386i systems running a SunOS 4.0.\fIx\fR
release or earlier.  Not a SunOS 4.1 release feature.
.SH DESCRIPTION
.IX "copy_home" "" "\fLcopy_home\fP\(em fetch default startup files for new home directories" ""
.LP
Whenever
.BR snap (1)
is used to add a new user account, the
.B copy_home
script in the selected primary group's home directory is executed
to copy the default files to the new user's home directory, and also
perform any additional custom setup.
.LP
.B copy_home
copies default environment files, such as
.BR \&.cshrc ,
.BR \&.login ,
and
.BR \&.orgrc ,
from a group's
.B defaults
directory to a new user's home directory.
It is started by
.BR user_agentd (8)
when
.BR snap (1)
is used to create new home directories on a Sun386i home directory server.
.LP
Every new group created by
.BR snap (1)
has a home directory, which
can be accessed using
.BI /home/ groupname\fR.
.BR user_agentd (8)
copies the contents of the Sun386i's default group,
.BR /home/users ,
into the home directory of the new group.
This includes the
.B Welcome.txt
file, the
.B copy_home
script, and the
.B defaults
directory .
.B copy_home
can be modified to customize the default setup
environment for new users in the group.
.SH SEE ALSO
.BR snap (1),
.BR user_agentd (8)
.LP
.I Sun386i SNAP Administration
.br
.I Sun386i Advanced Administration
