.\"@(#)dbconfig.8 1.1 92/07/30 SMI;
.TH DBCONFIG 8 "28 March 1989"
.SH NAME
dbconfig \- initializes the dial box
.SH SYOPNSIS
.B /usr/etc/dbconfig
.I serial-device
.SH DESCRIPTION
.IX "DB, initialize dial box\(em \fLdbconfig\fR"
.LP
.B dbconfig
opens the designated serial port and sets its baud, parity and
transmission rates.
It also removes all
.SM STREAMS
modules already pushed upon it 
(such as
.BR ttcompat (4M)
and
.BR ldterm (4M))
and pushes the dial box
.SM STREAMS
module \*(lqdb\*(rq onto the device.
.B db
then holds the stream open to
maintain this configuration.
.LP
If the device 
.B /dev/dialbox
has not been created and linked to the serial port,
.B dbconfig 
will fail.
.PD
.SH FILES
.PD 0
.TP 20
.B /dev/dialbox
.PD
.SH "SEE ALSO"
.BR db (4M),
.BR ldterm (4M),
.BR ttcompat (4M),
.BR dialtest (6)
