.\" @(#)dmesg.8 1.1 92/07/30 SMI; from UCB 4.3
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.TH DMESG 8 "9 September 1987"
.SH NAME
dmesg \- collect system diagnostic messages to form error log
.SH SYNOPSIS
.B /usr/etc/dmesg
[
.B  \-
]
.SH DESCRIPTION
.IX  "dmesg command"  ""  "\fLdmesg\fP \(em create error log"
.IX  "create" "error log \(em \fLdmesg\fP"
.LP
Note:
.B dmesg
is obsoleted by
.BR syslogd (8)
for maintenance of the system error log.
.LP
.B dmesg
looks in a system buffer for recently printed diagnostic messages
and prints them on the standard output.
The messages are those printed or logged
by the system when errors occur.
If the
.RB ` \- '
flag is given, then
.B dmesg
computes (incrementally) the new messages since the last time it
was run and places these on the standard output.
.SH FILES
.PD 0
.TP 20
.B /var/adm/msgbuf
scratch file for memory of
.RB ` \- '
option
.PD
.SH SEE ALSO
.BR syslogd (8)
