.\" @(#)dumpfs.8 1.1 92/07/30 SMI; from UCB 4.2
.TH DUMPFS 8 "9 September 1987"
.SH NAME
dumpfs \- dump file system information
.SH SYNOPSIS
.B /usr/etc/dumpfs
.I device
.SH DESCRIPTION
.IX  "dumpfs command"  ""  "\fLdumpfs\fP \(em dump file system information"
.IX  "file system"  "dump information"  ""  "dump information \(em \fLdumpfs\fP"
.B dumpfs
prints out the super block and cylinder group information
for the file system or special device specified.
The listing is very long and detailed.  This
command is useful mostly for finding out certain file system
information such as the file system block size and minimum
free space percentage.
.SH "SEE ALSO"
.BR fs (5),
.BR fsck (8),
.BR newfs (8),
.BR tunefs (8)
