.\" @(#)extract_unbundled.8 1.1 92/07/30 SMI; from UCB 4.3 BSD
.TH EXTRACT_UNBUNDLED 8 "1 July 1990"
.SH NAME
extract_unbundled \- extract and execute unbundled-product installation scripts
.SH SYNOPSIS
.B extract_unbundled
.RB [ " \-d\c"
.I device
.RB [ " \-r\c"
.IR remote-host " ] ]"
[
.SB \-DEFAULT
]
.SH DESCRIPTION
.IX "extract_unbundled command" "" "\fLextract_unbundled\fP command"
.LP
.B extract_unbundled
extracts and executes the installation
scripts from release tapes and diskettes
for Sun unbundled software products.
If no options are
specifed, it prompts for input as to the tape device, or remote
hostname from which to the software is to be installed.
For information about installing a specific product, refer to the
installation manual that accompanies that product.
.SH OPTIONS
.TP
.BI \-d device
Install from the indicated tape drive, such as
.B st0 
.BR mt0 ,
or
.BR fd0c .
.TP
.BI \-r remote_host
Install from the device given in the 
.BR \-d
option on the indicated remote host.
.TP
.SB \-DEFAULT
Execute the installation script using all default values.
Otherwise the installation script prompts for any optional values.
.SH BUGS
.LP
The
.B \-r
option cannot be used with floppy diskettes.
