.\" @(#)fastboot.8 1.1 92/07/30 SMI; from UCB 4.2
.TH FASTBOOT 8 "3 July 1990"
.SH NAME
fastboot, fasthalt \- reboot/halt the system while disabling disk checking
.SH SYNOPSIS
.B /usr/etc/fastboot
[
.I boot-options
]
.LP
.B /usr/etc/fasthalt
[
.I halt-options
]
.SH DESCRIPTION
.IX  "fastboot command"  ""  "\fLfastboot\fP \(em reboot system"
.IX  "reboot system"  ""  "reboot system \(em \fLfastboot\fP"
.IX  "fasthalt command"  ""  "\fLfasthalt\fP \(em halt system"
.IX  "halt system"  ""  "halt system \(em \fLfasthalt\fP"
.LP
.B fasthalt
halts the system (like
.BR halt (8))
and
.B fastboot 
reboots the system (like
.BR reboot (8)).
Both these programs disable subsequent checking 
of the file systems on the next reboot.  This is done by creating a file
.BR /fastboot .
The system startup script
.B /etc/rc
looks for this file and, if present, skips the normal invocation of
.BR fsck (8).
.SH FILES
.PD 0
.TP 20
.B /usr/etc/fastboot
.TP
.B /etc/rc
.TP
.B /fastboot
.PD
.SH "SEE ALSO"
.BR fsck (8),
.BR halt (8),
.BR init (8),
.BR rc (8),
.BR reboot (8)
