.\" @(#)fontflip.8 1.1 92/07/30 SMI;
.TH FONTFLIP 8 "15 September 1988"
.SH NAME
fonftlip \- create Sun386i-style vfont file
.SH SYNOPSIS
.B fontflip fontname
[
.B \-o 
.I newfontname
]
.SH AVAILABILITY
.LP
Available only on Sun 386i systems running a SunOS 4.0.\fIx\fR
release or earlier.  Not a SunOS 4.1 release feature.
.SH DESCRIPTION
.IX "fontflip command" "" "\fLfontflip\fR command"
.LP
.B fontflip 
takes as input a vfont file (Sun-3 fixedwidthfont)
and creates a Sun386i system vfont.
This new font is a bitflipped version of its input. 
The new font is named
.IB oldfont .flip
unless otherwise specified.
.SH OPTIONS
.TP 18
.BI \-o " newfontname"
Specify the name of the new flipped font.  
.SH FILES
.PD 0
.TP 20
.B /usr/lib/fonts/fixedwidthfonts 
.PD
.SH SEE ALSO
.BR vfont (5)
