.\" @(#)fpurel.8 1.1 92/07/30 SMI;
.TH FPUREL 8 "6 October 1988"
.SH NAME
fpurel \- perform tests the Sun Floating Point Co-processor.
.SH SYNOPSIS
.B fpurel
[
.B \-v
]
[
.BR \-p [\c
.IR count ]
]
[
.B \-r
]
.SH DESCRIPTION
.IX "fpurel command"  ""  "\fLfpurel\fP \(em Test Numeric Co-processor"
.B fpurel
performs a series of functional and computational tests for the Sun Floating
Point Co-processor to verify that it is operational and accurate.
With no options,
.B fpurel
runs one pass silently in the 
foreground and only reports errors if any are found.
.SH OPTIONS
.TP
.B \-v
Verbose.  Display the name and results of each
test on the console.  The default is to run silently.
.HP
.BR \-p [\c
.IR count ]
.br
Passcount.  Specify the number of times to run the test suite.
The default is to run one pass.
.TP
.B \-r
Disable stop on error.  Continue to run if errors are 
detected.  The default is to display the error message and to stop testing
when an error is detected.
.SH EXAMPLE
.LP
This example uses
.B fpurel
from the
.B /usr/diag
directory.  If no errors are detected, then no information is
displayed.
.IP
.B
% /usr/diag/fpurel
