.\" @(#)fusage.8 1.1 92/07/30 SMI; from S5R3
.TH FUSAGE 8 "30 June 1988"
.SH NAME
fusage \- RFS disk access profiler
.SH SYNOPSIS
.B fusage
[ [
.I mount_point
] | [
.I advertised_resource
] | [
.I block_special_device
] [\|.\|.\|.\|] ]
.SH AVAILABILITY
.LP
This program is available with the
.I \s-1RFS\s0
software installation option.
Refer to
.TX INSTALL
for information on how to install optional software.
.SH DESCRIPTION
.IX "fusage disk" "" "\fLfusage\fP \(em disk access profiler"
.IX disk "access profiler"
.IX "profile" "disk access"
.IX report "disk access"
.IX access "report, for disk"
.IX "file system" "report access"
.IX RFS "RFS disk access profiler" "\s-1RFS\s0" "RFS disk access profiler"
.LP
When used with no options,
.B fusage
reports block
I/O transfers, in kilobytes, to and from all locally mounted file systems
and advertised Remote File Sharing resources on a per client basis.
The count data are cumulative since the time of the mount.
When used with an option,
.B fusage
reports on the
named file system, advertised resource, or block special device.
.LP
The report includes one section for each file system and advertised
resource and has one entry for each machine that has the directory
remotely mounted,
ordered by decreasing usage.
Sections are ordered by device name; advertised resources that are not
complete file systems will immediately follow the sections for the file systems
they are in.
.SH "SEE ALSO"
.BR df (1V),
.BR adv (8),
.BR crash (8),
.BR mount (8)
