.\" @(#)gt_lpconfig.8 1.1 92/07/30 SMI;
.TH GT_LPCONFIG 8 "3 July 1991"
.SH NAME
gt_lpconfig \- Configure the GT lightpen device parameters.
.SH SYNOPSIS
.B /usr/etc/gt_lpconfig
.SH DESCRIPTION
It is a window based tool for setting up the calibration and smoothening parameters in the lightpen driver. A help function provided to guide the user with the actual specifics of this tool.
.LP
This tool should be run only after the GT has been initialized through gtconfig.
.SH OPTIONS
.TP
.BI NONE
.SH FILES
.PD 0
.TP 30
.BI /dev/gt0
GT Graphics Accelerator file
.TP
.B /dev/lightpen
Lightpen file
.PD
.SH "SEE ALSO"
.BR gt (4S),
.BR gtconfig (8),
