.\" @(#)halt.8 1.1 92/07/30 SMI; from UCB 4.3
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.TH HALT 8 "9 September 1987"
.SH NAME
halt \- stop the processor
.SH SYNOPSIS
.B /usr/etc/halt
[
.B \-nqy
]
.SH DESCRIPTION
.IX  "halt command"  ""  "\fLhalt\fP \(em stop processor"
.IX  "stop processor halt"  ""  "stop processor \(em \fLhalt\fP"
.B halt
writes out any information pending to the disks and then
stops the processor.
.LP
.B halt
normally logs the system shutdown to the system log daemon,
.BR syslogd (8),
and places a shutdown record in the login accounting file
.BR /var/adm/wtmp .
These actions are inhibited if the
.B \-n
or
.B \-q
options are present.
.SH OPTIONS
.TP
.B \-n
Prevent the
.I sync
before stopping.
.TP
.B \-q
Do a quick halt. No graceful shutdown is attempted.
.TP
.B \-y
Halt the system, even from a dialup terminal.
.SH FILES
.PD 0
.TP 20
.B /var/adm/wtmp
login accounting file
.PD
.SH SEE ALSO
.BR reboot (8),
.BR shutdown (8),
.BR syslogd (8)
