.\" @(#)ldconfig.8 1.1 92/07/30 SMI
.TH LDCONFIG 8 "28 November 1987"
.SH NAME
ldconfig \- link-editor configuration
.SH SYNOPSIS
.B /usr/etc/ldconfig
[
.I directory 
\ ... ]
.SH DESCRIPTION
.IX "ldconfig command" "" "\fLldconfig\fP \(em configure link-editor"
.IX "ldconfig command" "" "shared library cache"
.B ldconfig
is used to configure a performance-enhancing cache for the run-time
link-editor,
.BR ld.so .
It is run from
.B /etc/rc.local
and periodically via
.B cron
to avoid linking with stale libraries.  It should be also be run manually
when a new shared object (e.g., a shared library) is installed on the system.
.LP
When invoked with no arguments, a default set of directories are built
into the cache \- these are the directories searched by default by the
link editors.  Additional directories may be specified on the command
line.
.SH FILES
.PD 0
.TP 20
.B /etc/ld.so.cache
holds the cached data.
.PD
.SH SEE ALSO
.BR ld (1)
