.\" @(#)logintool.8 1.1 92/07/30 SMI; 
.TH LOGINTOOL 8 "19 February 1988"
.SH NAME
logintool \- graphic login interface
.SH AVAILABILITY
.LP
Available only on Sun 386i systems running a SunOS 4.0.\fIx\fR
release or earlier.  Not a SunOS 4.1 release feature.
.SH DESCRIPTION
.IX "logintool command"  ""  "\fLlogintool\fP \(em graphic login interface"
.IX "commands"  "logintool command"  ""  "\fLlogintool\fP \(em graphic login interface"
.LP
.B logintool
is started by
.BR getty (8)
to display a full screen window for logging in.
It cannot be run from the shell.
It is more attractive than the
traditional
.RB ` "login: " '
prompt, and also provides help for the person without a 
username and information about the workstation.
.LP
.B logintool
is normally invoked on the console by
.BR getty (8),
and works only on a frame buffer.
.LP
If the
.B newlogin
policy in the
.B policies
Network Information Service
(\s-1NIS\s0)
map is set to
.BR unrestricted ,
then 
.B logintool
may create new user accounts in the 
.SM NIS
service.
The account resides on the
local system if it is diskful, or on the system's boot server if the 
local system is diskless.
.SH FILES
.B /usr/share/lib/ez/login
.br
.SH SEE ALSO
.BR getty (8)
.SH NOTES
.LP
The Network Information Service
(\s-1NIS\s0)
was formerly known as Sun Yellow Pages
(\s-1YP\s0). 
The functionality of the two remains the same;
only the name has changed.
