.\" @(#)mconnect.8 1.1 92/07/30 SMI;
.TH MCONNECT 8 "9 September 1987"
.SH NAME
mconnect \- connect to SMTP mail server socket
.SH SYNOPSIS
.B /usr/etc/mconnect
[
.BI \-p " port"
] [
.B \-r
] [
.I hostname
]
.SH DESCRIPTION
.IX mconnect "" "\fLmconnect\fR \(em open connection to remote mail server"
.B mconnect
opens a connection to the mail server on a given host, so that it
can be tested independently of all other mail software.
If no host is given, the connection is made to the local host.
Servers expect to speak the Simple Mail
Transfer Protocol (\s-1SMTP\s0) on this connection.
Exit by typing the
.B quit
command.  Typing
.SM EOF
will send an end of file to the server.
An interrupt closes the connection immediately and exits.
.SH OPTIONS
.TP
.BI \-p " port"
Specify the port number instead of the default
.SM SMTP
port (number 25) as the next argument.
.TP
.B \-r
``Raw'' mode: disable the default line buffering and input handling.
This gives you a similar  effect as
.B telnet
to port number 25, not very useful.
.SH FILES
.PD 0
.TP 20
.B /usr/lib/sendmail.hf
help file for
.SM SMTP
commands
.PD
.SH SEE\ ALSO
.BR sendmail (8)
.LP
Postel, Jonathan B
.IR "Simple Mail Transfer Protocol" ,
.SM RFC\s0821
August 1982,
.SM SRI
Network Information Center
