.\" @(#)mkfile.8 1.1 92/07/30 SMI;
.TH MKFILE 8 "1 March 1988"
.SH NAME
mkfile \- create a file
.SH SYNOPSIS
.B mkfile
.RB [ " \-nv " ]
.I size\c
[\c
.BR k \||\| b \||\| m\c
]
.IR filename " .\|.\|."
.SH DESCRIPTION
.IX "mkfile command" "" "\fLmkfile\fP command"
.B mkfile
creates one or more files that are suitable for use as
.SM NFS-\s0mounted
swap areas, or as local swap areas.
The sticky bit is set, and
the file is padded with zeroes by default.  The
default
.I size 
is in bytes, but it
can be flagged as kilobytes, blocks, or megabytes, with the
.BR k ,
.BR b  ,
or
.BR m
suffixes, respectively.
.SH OPTIONS
.TP
.B \-n
Create an empty
.IR filename .
The size is noted, but disk blocks aren't allocated until data is
written to them.
.TP
.B \-v
Verbose.  Report the names and sizes of created files.
.SH SEE ALSO
.BR swapon (2),
.BR fstab (5),
.BR swapon (8)
