.\" @(#)mknod.8 1.1 92/07/30 SMI; from UCB 4.2
.TH MKNOD 8  "9 September 1987"
.SH NAME
mknod \- build special file
.SH SYNOPSIS
.B /usr/etc/mknod
.I filename
[
.B c
] [
.B b
]
.I major minor
.LP
.B /usr/etc/mknod
.I filename
.B p
.SH DESCRIPTION
.IX  "mknod command"  ""  "\fLmknod\fP \(em make special file"
.IX  make "special file \(em \fLmknod\fP"
.IX  "create" "special file \(em \fLmknod\fP"
.IX  "special file"  "make mknod"  "special file"  "make \(em \fLmknod\fP"
.IX  make "fifo \(em \fLmknod\fP"
.IX  "create" "fifo \(em \fLmknod\fP"
.IX  "fifo, make \(em \fLmknod\fP"
.IX  make "named pipe \(em \fLmknod\fP"
.IX  "create" "named pipe \(em \fLmknod\fP"
.IX  "named pipe, make \(em \fLmknod\fP"
.B mknod
makes a special file.  The first argument is the
.I filename
of the entry.  In the first form, the second argument is
.B b
if the special file is block-type (disks, tape) or
.B c
if it is character-type (other devices).  The last two arguments are
numbers specifying the
.I major
device type and the
.I minor
device (for example, unit, drive, or line number).
Only the super-user is permitted to invoke this form of the
.B mknod
command.
.LP
In the second form,
.B mknod
makes a named pipe (\s-1FIFO\s0).
.LP
The first form of
.B mknod
is only for use by system configuration
people.  Normally
you should use
.B /dev/\s-1MAKEDEV\s0
instead when making special files.
.SH "SEE ALSO"
.BR mknod (2V),
.BR makedev (8)
