.\" @(#)modstat.8	1.1 92/07/30 SMI
.TH MODSTAT 8 "3 July 1990"
.SH NAME
modstat \- display status of loaded kernel modules
.SH SYNOPSIS
.B modstat
[
.BI \-id " module_id"
]
.SH DESCRIPTION
.IX "modstat command" "" "\fLmodstat\fP command"
.LP
.B modstat
displays the status of the loaded modules.
.SH OPTIONS
.TP 15
.BI \-id " module_id"
Display the status of only this module.
.SH SEE ALSO
.BR modload (8),
.BR modunload (8)
