.\" @(#)modunload.8	1.1 92/07/30 SMI;
.TH MODUNLOAD 8 "20 January 1990"
.SH NAME
modunload \- unload a module
.SH SYNOPSIS
.B modunload
.BI \-id " module_id"
[
.B \-exec " exec_file"
]
.SH DESCRIPTION
.IX "modunload command" "" "\fLmodunload\fP command"
.LP
.B modunload
unloads a loadable module from a running system.  The 
.I module_id
is the
.SM ID
of the module as shown by 
.BR modstat (8).
.SH OPTIONS
.TP
.BI \-exec " exec_file"
This is the name of a shell script or executable image file that will be 
executed before the module is unloaded. 
It is always passed the module 
.SM ID
and module type as the first two arguments.
For loadable drivers, the third and fourth arguments are
the block major and character major numbers respectively.
For a loadable system call, the third argument 
is the system call number.
.SH SEE ALSO
.BR modload (8),
.BR modstat (8)
