.\" @(#)newaliases.8 1.1 92/07/30 SMI; from UCB 4.1
.TH NEWALIASES 8 "9 September 1987"
.SH NAME
newaliases \- rebuild the data base for the mail aliases file
.SH SYNOPSIS
.B newaliases
.SH DESCRIPTION
.IX  "newaliases command"  ""  "\fLnewaliases\fP \(em make mail aliases database"
.IX  "create" "mail aliases database \(em \fLnewaliases\fP"
.IX  "mail utilities" "create aliases database \(em \fLnewaliases\fP" "\fLmail\fR utilities"
.B newaliases
rebuilds the random access data base for the mail aliases file
.BR /etc/aliases .
It is run automatically by
.BR sendmail (8)
(in the default configuration) whenever a message is sent.
.\" It must be run each time \fI/etc/aliases\fP is changed in order
.\" for the change to take effect.
.SH FILES
.PD 0
.TP 20
.B /etc/aliases
.PD
.SH SEE ALSO
.BR aliases (5),
.BR sendmail (8)
