.\" @(#)repquota.8 1.1 92/07/30 SMI; from UCB 4.2
.TH REPQUOTA 8 "9 September 1987"
.UC 4
.SH NAME
repquota \- summarize quotas for a file system
.SH SYNOPSIS
.B /usr/etc/repquota
[
.B \-v
]
.IR filesystem .\|.\|.
.LP
.B /usr/etc/repquota
[
.B \-av
]
.SH DESCRIPTION
.IX  "repquota command"  ""  "\fLrepquota\fP \(em summarize quotas"
.IX  "user quotas"  "repquota command"  ""  "\fLrepquota\fP \(em summarize quotas"
.IX  "disk quotas"  "repquota command"  ""  "\fLrepquota\fP \(em summarize quotas"
.IX  "quotas"  "repquota command"  ""  "\fLrepquota\fP \(em summarize quotas"
.IX  "file system"  "repquota command"  ""  "\fLrepquota\fP \(em summarize quotas"
.IX  "summarize file system quotas repquota"  ""  "summarize file system quotas \(em \fLrepquota\fP"
.IX  "report file system quotas repquota"  ""  "report file system quotas \(em \fLrepquota\fP"
.IX  display "file system quotas \(em \fLrepquota\fP"
.LP
.B repquota
prints a summary of the disc usage and quotas for the specified file
systems.  For each user the current number of files and amount of space
(in kilobytes) is printed, along with any quotas created with
.BR edquota (8).
.SH OPTIONS
.TP
.B \-a
Report on all file systems indicated in
.B /etc/fstab
to be read-write with quotas.
.TP
.B \-v
Report all quotas, even if there is no usage.
.LP
Only the super-user may view quotas which are not their own.
.SH FILES
.PD 0
.TP 20
.B quotas
quota file at the file system
root
.TP
.B /etc/fstab
default file systems
.PD
.SH SEE ALSO
.BR quota (1),
.BR quotactl (2),
.BR edquota (8),
.BR quotacheck (8),
.BR quotaon (8)
