.\" @(#)rm_client.8 1.1 92/07/30 SMI;
.TH RM_CLIENT 8 "20 October 1988"
.SH NAME
rm_client \- remove an NFS client
.SH SYNOPSIS
.B rm_client 
[
.B \-y
]
.I clients
.SH DESCRIPTION
.IX "rm_client command" "" "\fLrm_client\fP command"
.LP
.B rm_client
removes an
.SM NFS
client from a server.
By default, 
.B rm_client
asks if you want to remove the client's root directory,
swap file, hosts entry, and
.B /tftpboot
file and whether to delete the client's entry in
.BR /etc/bootparams . 
.B rm_client
can be run only by the super-user on the server,
while in multiuser mode, or while not in the miniroot.
.SH OPTIONS
.TP 15
.B \-y
Supply \*(lqyes\*(rq answers to all questions
about what to remove.
.SH FILES
.PD 0
.TP
.B /etc/bootparams
.TP
.BI /tftpboot/ machine_addr
.TP
.BI /export/root/ client
.TP
.BI /export/swap/ client
.PD
.SH "SEE ALSO"
.BR add_client (8),
.BR add_services (8),
.BR suninstall (8)
.LP
.TX INSTALL
.SH DIAGNOSTICS
.TP
.B "must be run as root (super-user)."
You must be root to run
.BR rm_client .
