.\" @(#)showmount.8 1.1 92/07/30 SMI;
.TH SHOWMOUNT 8 "17 December 1987"
.SH NAME
showmount \- show all remote mounts
.SH SYNOPSIS
.B /usr/etc/showmount
[
.B \-ade
] [
.I hostname
]
.SH AVAILABILITY
This program is available with the
.I Networking
software installation option.  Refer to
.TX INSTALL
for information on how to install optional software.
.SH DESCRIPTION
.IX  "showmount command"  ""  "\fLshowmount\fP \(em display remote mounts"
.LP
.B showmount
lists all the clients
that have remotely mounted a filesystem from
.IR host .
This information is maintained by the
.BR mountd (8C)
server on
.IR host ,
and is saved across crashes in the file
.BR /etc/rmtab .
The default value for
.I host
is the value returned by
.BR hostname (1).
.SH OPTIONS
.TP
.B \-a
Print all remote mounts in the format:
.IP
.RS
.RS
.IB hostname : directory
.RE
.RE
.IP
where
.I hostname
is the name of the client, and
.B directory
is the root of the file system that has been mounted.
.TP
.B \-d
List directories that have been remotely mounted by clients.
.TP
.B \-e
Print the list of exported file systems.
.SH FILES
.PD 0
.TP 20
.B /etc/rmtab
.PD
.SH "SEE ALSO"
.BR hostname (1),
.BR exports (5),
.BR exports (5),
.BR exportfs (8),
.BR mountd (8C)
.SH BUGS
If a client crashes, its entry will not be removed from the list
until it reboots and executes
.RB ` "umount \-a" '.
