.\" @(#)user_agentd.8 1.1 92/07/30 SMI;
.TH USER_AGENTD 8C "6 October 1989"
.SH NAME
user_agentd \- user agent daemon
.SH SYNOPSIS
.B /usr/etc/rpc.user_agentd
.SH AVAILABILITY
.LP
Available only on Sun 386i systems running a SunOS 4.0.\fIx\fR
release or earlier.  Not a SunOS 4.1 release feature.
.SH DESCRIPTION
.IX "user_agentd" "" "\fLuser_agentd\fP\(em user agent daemon" ""
.LP
.B rpc.user_agentd
is the remote service used by
.BR snap (1) 
to create, move, or delete home directories, and by the New User Accounts
feature of
.BR logintool (8)
to create new home directories.
The user_agent daemon is normally invoked by
.BR inetd (8C),
and runs on all non-diskless systems.
.LP
When creating a new home directory, the user_agent daemon executes the
.BR copy_home (8)
script which resides in the home directory of the primary group to which a
new user will be added.
.SH SEE ALSO
.BR snap (1),
.BR copy_home (8),
.BR inetd (8C),
.BR logintool (8)
