.\" @(#)vipw.8 1.1 92/07/30 SMI; from UCB 4.2
.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.TH VIPW 8 "9 September 1987"
.SH NAME
vipw \- edit the password file
.SH SYNOPSIS
.B /usr/etc/vipw
.SH DESCRIPTION
.IX  "vipw command"  ""  "\fLvipw\fP \(em edit password file"
.IX  edit "password file \(em \fLvipw\fP"
.IX  "password file"  "edit"  "password file"  "edit \(em \fLvipw\fP"
.B vipw
edits the password file while setting the appropriate locks,
and does any necessary processing after the password file is unlocked.
If the password file is already being edited, then you will be told
to try again later.  The
.BR vi (1)
editor will be used unless the environment variable
.SB VISUAL
or
.SB EDITOR
indicates an alternate editor.
.LP
.B vipw
performs a number of consistency checks on the password entry for
root,
and will not allow a password file with a \*(lqmangled\*(rq root entry
to be installed.  It also checks the
.B /etc/shells
file to verify the login shell for root.
.SH FILES
.PD 0
.TP 20
.B /etc/ptmp
.TP
.B /etc/shells
.PD
.SH SEE ALSO
.BR passwd (1),
.BR vi (1),
.BR passwd (5),
.BR adduser (8)
