.\" @(#)yppoll.8 1.1 92/07/30 SMI
.TH YPPOLL 8 "14 December 1987"
.SH NAME
yppoll \- version of NIS map at NIS server
.SH SYNOPSIS
.B /usr/etc/yp/yppoll
[
.B \-h
.I host
] [
.B \-d
.I domain
]
.I mapname
.SH DESCRIPTION
.IX yppoll "" "\fLyppoll\fR \(em NIS version inquiry"
.LP
.B yppoll
asks a
.BR ypserv (8)
process what the order number is, and which host
is the
Network Information Service
(\s-1NIS\s0)
master server for the named map.
If the server is a
v.1
.SM NIS
protocol server,
.B yppoll
uses the older protocol to communicate with
it. 
In this case, it also uses the older diagnostic messages in
case of failure.
.SH OPTIONS
.TP
.BI \-h " host"
Ask the
.B ypserv
process at
.I host
about the map parameters.  If
.I host
is not specified, the
.SM NIS
server for the local host is used.
That is, the default host is the one returned by
.BR ypwhich (8).
.TP
.BI \-d " domain"
Use
.I domain
instead of the default domain.
.SH "SEE ALSO"
.BR ypfiles (5),
.BR ypserv (8),
.BR ypwhich (8)
.SH NOTES
.LP 
The Network Information Service
(\s-1NIS\s0)
was formerly known as Sun Yellow Pages
(\s-1YP\s0).
The functionality of the two remains the same;
only the name has changed.  The name Yellow Pages is a registered
trademark in the United Kingdom of British Telecommunications plc,
and may not be used without permission.

