.\" @(#)gp_demos.6 1.1 88/03/04 SMI;
.TH GP_DEMOS 6 "4 March 1988"
.SH NAME
gp_demos, flight, rotobj \- demonstration programs for the Graphics Processor
.SH SYNOPSIS
.B /usr/demo/flight
.LP
.B /usr/demo/rotobj
.RI [ " object " ]
.SH AVAILABILITY
These demos are available with the
.I Demos
software installation option.  Refer to
.TX INSTALL
for information on how to install optional software.
.SH DESCRIPTION
.IX demos "graphics processor"
.IX demos flight "" "\fLflight\fR \(em graphics processor demo"
.IX flight "" "\fLflight\fR \(em graphics processor demo"
.IX demos rotobj "" "\fLrotobj\fR \(em graphics processor demo"
.IX rotobj "" "\fLrotobj\fR \(em graphics processor demo"
.LP
These demos only run in windows running on a Graphics Processor
surface.
.SS Flight
.I flight
is a mouse-driven flight simulator.
.LP
.I Interactive Commands
.TP 15n
.B Middle-Button
Restart the program.
.TP
.B Right-Button
Increase speed.
.TP
.B Left-Button
Decrease speed.
.TP
.B Move-Mouse-Forward
The airplane dives.
.TP
.B Move-Mouse-Backward
The airplane climbs.
.TP
.B Move-Mouse-Left/Right
The airplane banks.
.TP
.B Left/Right-With-Right-Button
The airplane rolls without banking.
.SS Rotobj
.B rotobj
rotates an
.I object.
Object files
are located in
.B /usr/demo/\s-1DATA\s0
and have the suffix
.BR .vecs .
.SH FILES
.PD 0
.TP 20
.B /usr/demo\s-1DATA\s0
.PD
.SH SEE ALSO
.BR graphics_demos (6)
