.\" @(#)iso_8859_1.7 1.1 92/07/30 SMI; from UCB 4.2
.TH ISO_8859_1 7 "5 October 1989"
.SH NAME
iso_8859_1 \- map of character set
.SH SYNOPSIS
.B cat /usr/share/lib/locale/LC_CTYPE/iso_8859_1
.IX  "ascii file"  ""  "\fLascii\fP \(em ASCII character set"
.SH DESCRIPTION
.LP
.B /usr/share/lib/locale/LC_CTYPE/iso_8859_1
is a map of the
.SM ISO_8859/1
character set, to be printed as needed.
.LP
This character set is available if
.B setlocale (3V)
is declared as:
.IP
.B setlocale(LC_CTYPE, iso_8859_1)
.LP
or:
.IP
.B setlocale(LC_ALL, iso_8859_1)
see
.BR setlocale (3V)
for more information about declaring categories and locales.
.SS "ISO Latin 1 Character Set"
.LP
The following table displays the
.SM ISO
8859/1 character set. 
.LP
.if n .ig IG
.\" ============  Begin troff version of table  ===============
.TN "ISO Latin 1"
.TS
box tab(;) ;
c s s s s
c c c c l
l l l | l | lp-1 .
ISO Latin 1
_
Row/Col;Decimal;Octal; ;Name
_
.ps -2
.vs -2
02/00;032;040;SP;SPACE
02/01;033;041;!;EXCLAMATION POINT
02/02;034;042;";QUOTATION MARK
02/03;035;043;#;NUMBER SIGN
02/04;036;044;$;DOLLAR SIGN
02/05;037;045;%;PERCENT SIGN
02/06;038;046;&;AMPERSAND
02/07;039;047;';APOSTROPHE
02/08;040;050;(;LEFT PARENTHESIS                     
02/09;041;051;);RIGHT PARENTHESIS                          
02/10;042;052;*;ASTERISK
02/11;043;053;+;PLUS SIGN
02/12;044;054;,;COMMA
02/13;045;055;-;HYPHEN, MINUS SIGN                                   
02/14;046;056;.;FULL STOP (U.S.: PERIOD, DECIMAL POINT)
02/15;047;057;/;SOLIDUS   (U.S.: SLASH)
.sp .5
03/00;048;060;0;DIGIT ZERO                                   
03/01;049;061;1;DIGIT ONE                                    
03/02;050;062;2;DIGIT TWO                                    
03/03;051;063;3;DIGIT THREE                                  
03/04;052;064;4;DIGIT FOUR                                   
03/05;053;065;5;DIGIT FIVE                                   
03/06;054;066;6;DIGIT SIX                                    
03/07;055;067;7;DIGIT SEVEN                                  
03/08;056;070;8;DIGIT EIGHT                                  
03/09;057;071;9;DIGIT NINE                                   
03/10;058;072;:;COLON
03/11;059;073;\;;SEMICOLON
03/12;060;074;<;LESS-THAN SIGN                               
03/13;061;075;\\=;EQUALS SIGN
03/14;062;076;>;GREATER-THAN SIGN                            
03/15;063;077;?;QUESTION MARK
.ps
.vs
.TE
.TS
box tab(;) ;
c s s s s
c c c c l
l l l | l | lp-1 .
ISO Latin 1 (continued)
_
Row/Col;Decimal;Octal; ;Name
_
.ps -2
.vs -2
04/00;064;100;@;COMMERCIAL AT
04/01;065;101;A;LATIN CAPITAL LETTER A
04/02;066;102;B;LATIN CAPITAL LETTER B
04/03;067;103;C;LATIN CAPITAL LETTER C
04/04;068;104;D;LATIN CAPITAL LETTER D
04/05;069;105;E;LATIN CAPITAL LETTER E
04/06;070;106;F;LATIN CAPITAL LETTER F
04/07;071;107;G;LATIN CAPITAL LETTER G
04/08;072;110;H;LATIN CAPITAL LETTER H
04/09;073;111;I;LATIN CAPITAL LETTER I
04/10;074;112;J;LATIN CAPITAL LETTER J
04/11;075;113;K;LATIN CAPITAL LETTER K
04/12;076;114;L;LATIN CAPITAL LETTER L
04/13;077;115;M;LATIN CAPITAL LETTER M
04/14;078;116;N;LATIN CAPITAL LETTER N
04/15;079;117;O;LATIN CAPITAL LETTER O
.sp .5
05/00;080;120;P;LATIN CAPITAL LETTER P
05/01;081;121;Q;LATIN CAPITAL LETTER Q
05/02;082;122;R;LATIN CAPITAL LETTER R
05/03;083;123;S;LATIN CAPITAL LETTER S
05/04;084;124;T;LATIN CAPITAL LETTER T
05/05;085;125;U;LATIN CAPITAL LETTER U
05/06;086;126;V;LATIN CAPITAL LETTER V
05/07;087;127;W;LATIN CAPITAL LETTER W
05/08;088;130;X;LATIN CAPITAL LETTER X
05/09;089;131;Y;LATIN CAPITAL LETTER Y
05/10;090;132;Z;LATIN CAPITAL LETTER Z
05/11;091;133;[;LEFT SQUARE BRACKET                        
05/12;092;134;\e;REVERSE SOLIDUS  (U.S.: BACK SLASH)
05/13;093;135;];RIGHT SQUARE BRACKET                        
05/14;094;136;^;CIRCUMFLEX ACCENT
05/15;095;137;\\_;LOW LINE (U.S.: UNDERSCORE)
.sp .5
06/00;096;140;`;GRAVE ACCENT       
06/01;097;141;a;LATIN SMALL LETTER a
06/02;098;142;b;LATIN SMALL LETTER b
06/03;099;143;c;LATIN SMALL LETTER c
06/04;100;144;d;LATIN SMALL LETTER d
06/05;101;145;e;LATIN SMALL LETTER e
06/06;102;146;f;LATIN SMALL LETTER f
06/07;103;147;g;LATIN SMALL LETTER g
06/08;104;150;h;LATIN SMALL LETTER h
06/09;105;151;i;LATIN SMALL LETTER i
06/10;106;152;j;LATIN SMALL LETTER j
06/11;107;153;k;LATIN SMALL LETTER k
06/12;108;154;l;LATIN SMALL LETTER l
06/13;109;155;m;LATIN SMALL LETTER m
06/14;110;156;n;LATIN SMALL LETTER n
06/15;111;157;o;LATIN SMALL LETTER o
.ps
.vs
.TE
.TS
box tab(;) ;
c s s s s
c c c c l
l l l | l | lp-1 .
ISO Latin 1 (continued)
_
Row/Col;Decimal;Octal; ;Name
_
.ps -2
.vs -2
.sp .5
07/00;112;160;p;LATIN SMALL LETTER p
07/01;113;161;q;LATIN SMALL LETTER q
07/02;114;162;r;LATIN SMALL LETTER r
07/03;115;163;s;LATIN SMALL LETTER s
07/04;116;164;t;LATIN SMALL LETTER t
07/05;117;165;u;LATIN SMALL LETTER u
07/06;118;166;v;LATIN SMALL LETTER v
07/07;119;167;w;LATIN SMALL LETTER w
07/08;120;170;x;LATIN SMALL LETTER x
07/09;121;171;y;LATIN SMALL LETTER y
07/10;122;172;z;LATIN SMALL LETTER z
07/11;123;173;{;LEFT CURLY BRACKET                         
07/12;124;174;|;VERTICAL LINE
07/13;125;175;};RIGHT CURLY BRACKET                         
07/14;126;176;~;TILDE
.sp .5
10/00;160;240;;NO-BREAK SPACE 
10/01;161;241;;INVERTED EXCLAMATION MARK
10/02;162;242;;CENT SIGN
10/03;163;243;;POUND SIGN
10/04;164;244;;CURRENCY SIGN                                
10/05;165;245;;YEN SIGN
10/06;166;246;;BROKEN BAR                                   
10/07;167;247;;PARAGRAPH SIGN, (U.S.: SECTION SIGN)
10/08;168;250;;DIAERESIS                                    
10/09;169;251;;COPYRIGHT SIGN
10/10;170;252;;FEMININE ORDINAL INDICATOR
10/11;171;253;;LEFT ANGLE QUOTATION MARK
10/12;172;254;;NOT SIGN                                     
10/13;173;255;;SHY  SOFT HYPHEN                            
10/14;174;256;;REGISTERED TRADEMARK SIGN                   
10/15;175;257;;MACRON                                       
.sp .5
11/00;176;260;;RING ABOVE, DEGREE SIGN
11/01;177;261;;PLUS-MINUS SIGN
11/02;178;262;;SUPERSCRIPT TWO
11/03;179;263;;SUPERSCRIPT THREE
11/04;180;264;;ACUTE ACCENT                                 
11/05;181;265;;MICRO SIGN
11/06;182;266;;PILCROW SIGN, (U.S.: PARAGRAPH)
11/07;183;267;;MIDDLE DOT                      
11/08;184;270;;CEDILLA
11/09;185;271;;SUPERSCRIPT ONE
11/10;186;272;;MASCULINE ORDINAL INDICATOR
11/11;187;273;;RIGHT ANGLE QUOTATION MARK
11/12;188;274;;VULGAR FRACTION ONE QUARTER
11/13;189;275;;VULGAR FRACTION ONE HALF
11/14;190;276;;VULGAR FRACTION THREE QUARTERS               
11/15;191;277;;INVERTED QUESTION MARK
.ps
.vs
.TE
.TS
box tab(;) ;
c s s s s
c c c c l
l l l | l | lp-1 .
ISO Latin 1 (continued)
_
Row/Col;Decimal;Octal; ;Name
_
.ps -2
.vs -2
.sp .5
12/00;192;300;;LATIN CAPITAL LETTER A WITH GRAVE ACCENT
12/01;193;301;;LATIN CAPITAL LETTER A WITH ACUTE ACCENT
12/02;194;302;;LATIN CAPITAL LETTER A WITH CIRCUMFLEX ACCENT
12/03;195;303;;LATIN CAPITAL LETTER A WITH TILDE
12/04;196;304;;LATIN CAPITAL LETTER A WITH DIAERESIS
12/05;197;305;;LATIN CAPITAL LETTER A WITH RING ABOVE
12/06;198;306;;CAPITAL DIPHTHONG AE
12/07;199;307;;LATIN CAPITAL LETTER C WITH CEDILLA
12/08;200;310;;LATIN CAPITAL LETTER E WITH GRAVE ACCENT 
12/09;201;311;;LATIN CAPITAL LETTER E WITH ACUTE ACCENT 
12/10;202;312;;LATIN CAPITAL LETTER E WITH CIRCUMFLEX ACCENT
12/11;203;313;;LATIN CAPITAL LETTER E WITH DIAERESIS
12/12;204;314;;LATIN CAPITAL LETTER I WITH GRAVE ACCENT 
12/13;205;315;;LATIN CAPITAL LETTER I WITH ACUTE ACCENT 
12/14;206;316;;LATIN CAPITAL LETTER I WITH CIRCUMFLEX ACCENT
12/15;207;317;;LATIN CAPITAL LETTER I WITH DIAERESIS
.sp .5
13/00;208;320;;CAPITAL ICELANDIC LETTER ETH                 
13/01;209;321;;LATIN CAPITAL LETTER N WITH TILDE
13/02;210;322;;LATIN CAPITAL LETTER O WITH GRAVE ACCENT 
13/03;211;323;;LATIN CAPITAL LETTER O WITH ACUTE ACCENT 
13/04;212;324;;LATIN CAPITAL LETTER O WITH CIRCUMFLEX ACCENT
13/05;213;325;;LATIN CAPITAL LETTER O WITH TILDE
13/06;214;326;;LATIN CAPITAL LETTER O WITH DIAERESIS
13/07;215;327;;MULTIPLICATION SIGN                          
13/08;216;330;;LATIN CAPITAL LETTER O WITH OBLIQUE STROKE
13/09;217;331;;LATIN CAPITAL LETTER U WITH GRAVE ACCENT 
13/10;218;332;;LATIN CAPITAL LETTER U WITH ACUTE ACCENT 
13/11;219;333;;LATIN CAPITAL LETTER U WITH CIRCUMFLEX
13/12;220;334;;LATIN CAPITAL LETTER U WITH DIAERESIS
13/13;221;335;;LATIN CAPITAL LETTER Y WITH ACUTE ACCENT  
13/14;222;336;;CAPITAL ICELANDIC LETTER THORN               
13/15;223;337;;SMALL GERMAN LETTER SHARP s
.sp .5
14/00;224;340;;LATIN SMALL LETTER a WITH GRAVE ACCENT
14/01;225;341;;LATIN SMALL LETTER a WITH ACUTE ACCENT
14/02;226;342;;LATIN SMALL LETTER a WITH CIRCUMFLEX ACCENT
14/03;227;343;;LATIN SMALL LETTER a WITH TILDE
14/04;228;344;;LATIN SMALL LETTER a WITH DIAERESIS
14/05;229;345;;LATIN SMALL LETTER a WITH RING ABOVE
14/06;230;346;;SMALL DIPHTHONG ae
14/07;231;347;;LATIN SMALL LETTER c WITH CEDILLA
14/08;232;350;;LATIN SMALL LETTER e WITH GRAVE ACCENT
14/09;233;351;;LATIN SMALL LETTER e WITH ACUTE ACCENT
14/10;234;352;;LATIN SMALL LETTER e WITH CIRCUMFLEX ACCENT
14/11;235;353;;LATIN SMALL LETTER e WITH DIAERESIS
14/12;236;354;;LATIN SMALL LETTER i WITH GRAVE ACCENT
14/13;237;355;;LATIN SMALL LETTER i WITH ACUTE ACCENT
14/14;238;356;;LATIN SMALL LETTER i WITH CIRCUMFLEX ACCENT
14/15;239;357;;LATIN SMALL LETTER i WITH DIAERESIS
.ps
.vs
.TE
.TS
box tab(;) ;
c s s s s
c c c c l
l l l | l | lp-1 .
ISO Latin 1 (continued)
_
Row/Col;Decimal;Octal; ;Name
_
.ps -2
.vs -2
.sp .5
15/00;240;360;;SMALL ICELANDIC LETTER ETH                   
15/01;241;361;;LATIN SMALL LETTER n WITH TILDE
15/02;242;362;;LATIN SMALL LETTER o WITH GRAVE ACCENT
15/03;243;363;;LATIN SMALL LETTER o WITH ACUTE ACCENT
15/04;244;364;;LATIN SMALL LETTER o WITH CIRCUMFLEX ACCENT
15/05;245;365;;LATIN SMALL LETTER o WITH TILDE
15/06;246;366;;LATIN SMALL LETTER o WITH DIAERESIS
15/07;247;367;;DIVISION SIGN                                
15/08;248;370;;LATIN SMALL LETTER o WITH OBLIQUE STROKE
15/09;249;371;;LATIN SMALL LETTER u WITH GRAVE ACCENT
15/10;250;372;;LATIN SMALL LETTER u WITH ACUTE ACCENT
15/11;251;373;;LATIN SMALL LETTER u WITH CIRCUMFLEX ACCENT
15/12;252;374;;LATIN SMALL LETTER u WITH DIAERESIS
15/13;253;375;;LATIN SMALL LETTER y WITH ACUTE ACCENT       
15/14;254;376;;SMALL ICELANDIC LETTER THORN                 
15/15;255;377;;LATIN SMALL LETTER y WITH DIAERESIS          
.ps
.vs
.TE
.\" ============  End troff version of table  ===============
.IG
.if t .ig IG
.\" ============  Begin nroff version of table  ===============
.LP
This character set is not currently available on-line,
please refer to the printed version of this manual page.
.\" ============  End nroff version of table  ===============
.IG
.SH SEE ALSO
.BR setlocale (3V)
