#  @(#)Makefile 1.1 92/07/30 SMI;
#
#  Description file for making the section 7 manual page sources.
#
#  NOTE that the list of filenames in the description file must be
#  kept up to date with the actual manual pages, including ".so" files.
 
HERE=man7

# --------------------------------------------------------------- #

FILES= \
Intro.7 intro.7 List.7 list.7 \
SunOS.7 ansic.7v ascii.7 bsd.7 eqnchar.7 filesystem.7 hier.7 \
iso_8859_1.7 man.7 me.7 misc.7 ms.7 posix.7v sunos.7 svid2.7v svid3.7v \
svidii.7v svidiii.7v xopen.7v

# --------------------------------------------------------------- #

include ../Makefile.master
