.\" @(#)drum.4 1.1 92/07/30 SMI; from UCB 4.2
.TH DRUM 4 "24 November 1987"
.SH NAME
drum \- paging device
.SH CONFIG
None; included with standard system.
.SH SYNOPSIS
.ft B
.nf
#include <fcntl.h>

open("/dev/drum", \fImode\fB);
.ft R
.fi
.SH DESCRIPTION
.IX  "drum device"  ""  "\fLdrum\fP \(em paging device"  ""  PAGE START
.IX  "paging device"  ""  "paging device \(em \fLdrum\fP"  ""  PAGE START
.LP
This file refers to the paging device in use
by the system.  This may actually be a subdevice
of one of the disk drivers, but in a system with
paging interleaved across multiple disk drives
it provides an indirect driver for the multiple drives.
.SH FILES
.PD 0
.TP 20
.B /dev/drum
.PD
.SH BUGS
.LP
Reads from the drum are not allowed across
the interleaving boundaries.
Since these only occur every .5Mbytes or so,
and since the system never allocates blocks
across the boundary, this is usually not a problem.
.IX  "drum device"  ""  "\fLdrum\fP \(em paging device"  ""  PAGE END
.IX  "paging device"  ""  "paging device \(em \fLdrum\fP"  ""  PAGE END
