#  @(#)Makefile 1.1 92/07/30 SMI;
#
#  Description file for making the section 4 manual page sources.
#
#  NOTE that the list of filenames in the description file must be
#  kept up to date with the actual manual pages, including ".so" files.

HERE=man4

# --------------------------------------------------------------- #

FILES=	\
Intro.4 List.4 intro.4 list.4 \
NFS.4p TFS.4s alm.4s ar.4s arp.4p atbus.4s audio.4 audioamd.4 bpp.4s bwtwo.4s \
cdromio.4 cgeight.4s cgfour.4s cgnine.4s cgsix.4s cgthree.4s cgtwelve.4s \
cgtwo.4s \
clone.4 cons.4s console.4s db.4m dbri.4 dkio.4s drum.4 eeprom.4s fb.4s \
fbio.4s fd.4s filio.4 fpa.4s gpone.4s gt.4s icmp.4p id.4s \
ie.4s if.4n inet.4f ip.4p ipi.4s is.4s kb.4m kbd.4s \
kmem.4 kmem.4s ldterm.4m le.4s lo.4 lofs.4s mbio.4s \
mbmem.4s mcp.4s mem.4s mouse.4s ms.4m ms3.4s mti.4s mtio.4 nfs.4p \
nif_pf.4m nit.4p nit_buf.4m nit_if.4m nit_pf.4m null.4 openprom.4s pcfs.4s \
pp.4 pty.4 rfs.4 root.4s routing.4n sbus.4s sd.4s sockio.4 sr.4s st.4s \
streamio.4 taac.4s tcp.4p tcptli.4p termio.4 termios.4 tfs.4s timod.4 \
tirdwr.4 tm.4s tmpfs.4s ttcompat.4m tty.4 udp.4p unix.4f vd.4s \
vme16d16.4s vme16d32.4s vme24d16.4s vme24d32.4s vme32d16.4s vme32d32.4s \
vpc.4s vx.4s win.4s xd.4s xt.4s xy.4s zero.4s zs.4s

# --------------------------------------------------------------- #

include ../Makefile.master
