.\" @(#)null.4 1.1 92/07/30 SMI; from UCB 4.1
.TH NULL 4 "24 November 1987"
.SH NAME
null \- data sink
.SH CONFIG
None; included with standard system.
.SH SYNOPSIS
.ft B
.nf
#include <fcntl.h>

open("/dev/null", \fImode\fB);
.ft R
.fi
.SH DESCRIPTION
.IX  "null device"  ""  "\fLnull\fP \(em null device"
Data written on the
.B null
special file is discarded.
.LP
Reads from the
.B null
special file always return an end-of-file indication.
.SH FILES
.PD 0
.TP 20
.B /dev/null
.PD
