.\" @(#)pp.4	1.1 92/07/30 SMI; from Matt Lennon
.TH PP 4  "19 February 1988"
.SH NAME
pp \- Centronics-compatible parallel printer port
.SH "CONFIG \(em Sun386i SYSTEMS"
.ft B
.nf
device pp0 at obio ? csr 0x378 irq 15 priority 2
.fi
.ft R
.SH "CONFIG \(em SUN-3x SYSTEMS"
.ft B
.nf
device pp0 at obio ? csr 0x6f000000 priority 1
.fi
.ft R
.LP
This synopsis line should be used to generate a kernel
for Sun-3/80 systems only.
.SH AVAILABILITY
Sun386i and Sun-3/80 systems only.
.SH DESCRIPTION
.IX "pp device" "" "\fLpp\fP, Centronics-compatible parallel printer port" 
.LP
This device driver provides an interface to the Sun386i
and Sun-3/80 systems'
on-board Centronics-compatible parallel printer port. 
It supports most standard
PC printers with Centronics interfaces.
.SH FILES
.B /dev/pp0
.SH DIAGNOSTICS
.B pp*: printer not online
.br
.B pp*: printer out of paper
