/* @(#)prop_ui.h 1.1 92/07/30 1989, 1990 Sun Microsystem, Inc. */
#ifndef	prop_HEADER
#define	prop_HEADER

/*
 * prop_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `prop.G'.
 * DO NOT EDIT BY HAND.
 */

extern Attr_attribute	INSTANCE;
typedef struct {
	Xv_opaque	prop;
	Xv_opaque	panel1;
	Xv_opaque	track_list;
	Xv_opaque	mem_list;
	Xv_opaque	mode_choice;
	Xv_opaque	track_label;
	Xv_opaque	track_mess;
	Xv_opaque	time_label;
	Xv_opaque	time_mess;
	Xv_opaque	guage1;
	Xv_opaque	guage_choice;
	Xv_opaque	mess1;
	Xv_opaque	leftbal_slider;
	Xv_opaque	rightbal_slider;
	Xv_opaque	idle_choice;
	Xv_opaque	idle_item;
} prop_prop_objects;
extern prop_prop_objects	*prop_prop_objects_initialize();
extern Xv_opaque	prop_prop_prop_create();

extern Xv_opaque	prop_prop_panel1_create();

extern Xv_opaque	prop_prop_track_list_create();

extern Xv_opaque	prop_prop_mem_list_create();

extern Xv_opaque	prop_prop_mode_choice_create();

extern Xv_opaque	prop_prop_track_label_create();

extern Xv_opaque	prop_prop_track_mess_create();

extern Xv_opaque	prop_prop_time_label_create();

extern Xv_opaque	prop_prop_time_mess_create();

extern Xv_opaque	prop_prop_guage1_create();

extern Xv_opaque	prop_prop_guage_choice_create();

extern Xv_opaque	prop_prop_mess1_create();

extern Xv_opaque	prop_prop_leftbal_slider_create();

extern Xv_opaque	prop_prop_rightbal_slider_create();

extern Xv_opaque	prop_prop_idle_choice_create();

extern Xv_opaque	prop_prop_idle_item_create();

#endif
