#
# @(#)Makefile 1.1 92/07/30 SMI
#
# This makefile creates the distributed kernel objects and
# configuration files.

ARCH=	sun3
MACH=	mc68020
CONFDIR= ../../conf.common
MACHINES= DL DL50 DL60 DL75 DL110 SDST50 SDST60 SDST110 SDST160 SDST260 XYMT160 XYMT260 XDMT160 XDMT260 GENERIC_SMALL
include ../../conf.common/Makefile.install
