.\" @(#)asa.1 1.1 92/07/30 SMI; from S5R2 6.2
.TH ASA 1 "21 February 1986"
.SH NAME
asa \- interpret ASA carriage control characters
.SH SYNOPSIS
.B asa
.I filename .\|.\|.
.SH DESCRIPTION
.IX asa "" "\fLasa\fP" \(em convert ASA files for printing
.IX "formatting ASA files" "" 
.I asa
interprets the output of
.SM FORTRAN
programs that
utilize 
.SM ASA 
carriage control characters.
If no 
.I filename
is supplied as an argument, the standard input is used.
.SS ASA Control Characters
.LP
The first character of each input line is assumed to be
a control character:
.PP
.TP 8
.B \(fm\0\(fm
Blank.  Print a single newline before printing (start a new line).
.TP
.B 0
Print a double newline before printing (skip a line).
.TP
.B 1
Start a new page before printing.
.TP
.B +
Overstrike previous line.
.PP
Lines beginning with other characters are treated as if
they began with a blank.
.\"If any such lines appear, an appropriate diagnostic will appear on standard
error.
The first character of a line is
.IR not
printed.
This program forces the first line of each input file to start on
a new page.
.SH EXAMPLE
.I asa
can be used as a filter to display the output of 
.SM FORTRAN
programs that use
.SM ASA
carriage control characters.  The pipeline:
.IP
\fLa.out | asa | lp\fR
.LP
directs formatted 
.SM FORTRAN
output 
to the line printer.
.SH SEE ALSO
f77(1), fsplit(1), ratfor(1).
