.\" @(#)atof.3 1.1 92/07/30 SMI; from UCB 4.2
.TH ATOF 3 "19 March 1984"
.SH NAME
atof, atoi, atol \- convert ASCII to numbers
.SH SYNOPSIS
.nf
.B double atof(nptr)
.B char *nptr;
.PP
.B atoi(nptr)
.B char *nptr;
.PP
.B long atol(nptr)
.B char *nptr;
.fi
.IX  "atof function"  ""  "\fLatof\fP \(em ASCII to float"
.IX  "ASCII to float \(em \fLatof\fP"
.IX  "convert strings to numbers"  atof  ""  \fLatof\fP
.IX  "atoi function"  ""  "\fLatoi\fP \(em ASCII to integer"
.IX  "convert strings to numbers"  atoi  ""  \fLatoi\fP
.IX  "ASCII to integer \(em \fLatoi\fP"
.IX  "atol function"  ""  "\fLatol\fP \(em ASCII to long"
.IX  "convert strings to numbers"  atol  ""  \fLatol\fP
.IX  "ASCII to long \(em \fLatol\fP"
.IX  "strings"  "convert to numbers"
.IX  "numbers"  "convert from strings"
.SH DESCRIPTION
These functions convert a string pointed to by
.I nptr
to floating, integer, and long integer representation respectively.
The first unrecognized character ends the string.
.PP
.I Atof
recognizes an optional string of spaces, then an optional sign, then
a string of digits optionally containing a decimal
point, then an optional `e' or `E' followed by an optionally signed integer.
.PP
.I Atoi
and
.I atol
recognize an optional string of spaces, then an optional sign, then a
string of
digits.
.SH SEE ALSO
scanf(3S)
.SH BUGS
There are no provisions for overflow.
.LP
Currently, \fIatof\fP performs highly inaccurate conversions of very
large or very small numbers \(em on the order of 10**32 or its reciprocal.
