.\" @(#)bsuncube.6 1.1 92/07/30 SMI
.TH BSUNCUBE 6  "11 January 1984"
.SH NAME
bsuncube \- view 3-D Sun logo
.SH SYNOPSIS
.B /usr/demo/bsuncube
.SH DESCRIPTION
.IX  "bsuncube command"  ""  "\fLbsuncube\fP \(em display 3-D Sun logo"
.I Bsuncube
allows the user to view a cube
from various positions with hidden faces removed.
The faces of the cube consist of the Sun logo.
The viewing position is selected using the mouse.
Using the SunCore Graphics Package, a 3-D projection
is drawn on the Sun Monochrome Bitmap Display.
.LP
The program operates in two modes: DisplayObject mode and SelectView mode.
The program starts in DisplayObject mode.
.LP
.BR DisplayObject :
The cube is displayed in 3-D perspective with hidden faces removed.
Type "q" while in this mode to exit the program.  Hit mouse button 3 to
switch to SelectView mode.
.LP
.BR SelectView :
Schematic projections of the outline of the cube are shown and the mouse
is used to select a viewing position.  Use button 1 to set x and button 2
to set y in the
.IR "Front View" .
Use button 2 to set z in the
.IR "Top View" .
Hit button 3 to switch to DisplayObject mode.
.LP
The view shown in DisplayObject mode is drawn using the conventions that the
viewer is always looking from the viewing position toward the center of
the cube and that the positive y axis on the screen is the projection of
the positive y axis in 3-D cube coordinates.
