.\" @(#)chase.6 1.1 92/07/30 SMI; from UCB 4.2
.TH CHASE 6 "16 February 1988"
.SH NAME
chase \- try to escape to killer robots
.SH SYNOPSIS
.B /usr/games/chase
[
.I nrobots
] [
.I nfences
]
.SH DESCRIPTION
.IX  "chase command"  ""  "\fLchase\fP \(em escape killer robots"
.LP
The object of the game 
.B chase 
is to move around inside of the box on the
screen without getting eaten by the robots chasing and without running
into anything.
.LP
If a robot runs into another robot while chasing you,
they crash and leave
a junk heap.  If a robot runs into a fence, it is destroyed.
.LP
If you can survive until all the robots are destroyed, you have won!
.LP
If you do not specify either
.I nrobots
or
.I nfences,
chase will prompt you for them.
