.\" @(#)colordemos.6 1.1 92/07/30 SMI
.TH COLORDEMOS 6 "10 January 1984"
.SH NAME
colordemos \- demonstrate Sun Color Graphics Display
.SH SYNOPSIS
.B /usr/demo/cballs
.br
.B /usr/demo/cdraw
.br
.BI /usr/demo/cphoto "  file"
.br
.B /usr/demo/cpipes
.br
.BI /usr/demo/cshowmap "  file"
.br
.B /usr/demo/csnow
.br
.B /usr/demo/csuncube
.br
.B /usr/demo/csunlogo
.br
.B /usr/demo/cvlsi
.SH DESCRIPTION
.IX  "cballs command"  ""  "\fLcballs\fP \(em color demo"
.IX  "cdraw command"  ""  "\fLcdraw\fP \(em color demo"
.IX  "cphoto command"  ""  "\fLcphoto\fP \(em color demo"
.IX  "cpipes command"  ""  "\fLcpipes\fP \(em color demo"
.IX  "cshowmap command"  ""  "\fLcshowmap\fP \(em color demo"
.IX  "csnow command"  ""  "\fLcsnow\fP \(em color demo"
.IX  "csuncube command"  ""  "\fLcsuncube\fP \(em color demo"
.IX  "csunlogo command"  ""  "\fLcsunlogo\fP \(em color demo"
.IX  "cvlsi command"  ""  "\fLcvlsi\fP \(em color demo"
.IX  "color demo"  "cballs command"  ""  "\fLcballs\fP"
.IX  "color demo"  "cdraw command"  ""  "\fLcdraw\fP"
.IX  "color demo"  "cphoto command"  ""  "\fLcphoto\fP"
.IX  "color demo"  "cpipes command"  ""  "\fLcpipes\fP"
.IX  "color demo"  "cshowmap command"  ""  "\fLcshowmap\fP"
.IX  "color demo"  "csnow command"  ""  "\fLcsnow\fP"
.IX  "color demo"  "csuncube command"  ""  "\fLcsuncube\fP"
.IX  "color demo"  "csunlogo command"  ""  "\fLcsunlogo\fP"
.IX  "color demo"  "cvlsi command"  ""  "\fLcvlsi\fP"
.I Colordemos
is a collection of simple demonstration programs for the Sun Color
Graphics Display.  Each program is briefly described below.
To exit each program,
send an interrupt signal by typing the appropriate key
(usually \s-2CONTROL C\s0).
.IP "\fBcballs\fP" 10
colliding balls on color display
.IP "\fBcdraw\fP" 10
draw on the color display; see \fIdraw\fP\|(6) for an explanation of how
to use \fIcdraw\fP.
.IP "\fBcphoto \fIfile\fR" 10
display dithered color file on color display.
Files suitable for display are in \fI/usr/demo/colorpix\fP.
.IP "\fBcpipes\fP" 10
colliding pipes on color display
.IP "\fBcshowmap\fP \fIfile\fP" 10
display maps.  Files suitable for display are in \fI/usr/demo/segments\fP.
.IP "\fBcsnow\fP" 10
color kaleidoscope
.IP "\fBcsuncube\fP" 10
multicolored Sun logo
.IP "\fBcsunlogo\fP" 10
shaded Sun logo
.IP "\fBcvlsi\fP" 10
color vlsi layout demo
.SH FILES 
/usr/demo/colorpix
.br
/usr/demo/segments
