.\" @(#)cribbage.6 1.1 92/07/30 SMI; from UCB 4.2
.TH CRIBBAGE 6 "7 March 1984"
.SH NAME
cribbage \- the card game cribbage
.SH SYNOPSIS
.B /usr/games/cribbage
[
.B \-req
]
.I name ...
.SH DESCRIPTION
.IX  "cribbage command"  ""  "\fLcribbage\fP \(em cribbage card game"
.I Cribbage
plays the card game cribbage, with
.I cribbage
playing one hand and the user the other.
.I Cribbage
initially asks the user if the rules of the game are needed \- if
so, 
.I cribbage
displays the appropriate section from
.I According to Hoyle
with
.IR more (1).
.SH OPTIONS
.TP
.B \-e
Provide an explanation of the correct score when the player makes mistakes
scoring his hand or crib.  This is especially useful for beginning players.
.TP
.B \-q
Print a shorter form of all messages \- this is only recommended for
users who have played the game without specifying this option.
.TP
.B \-r
Instead of asking the player to cut the deck,
.I cribbage
will randomly
cut the deck.
.SH "PLAYING CRIBBAGE"
.LP
.I Cribbage
first asks the player whether he wishes to play a short game
(\*(lqonce around\*(rq, to 61) or a long game (\*(lqtwice around\*(rq, to
121).  A response of `s' results in a short game, any other response
plays a long game.
.LP
At the start of the first game,
.I cribbage
asks the player to cut the deck to determine who gets the
first crib.  The user should respond with a number between 0 and
51, indicating how many cards down the deck is to be cut.  The player
who cuts the lower ranked card gets the first crib.
If more than one game is played, the
loser of the previous game gets the first crib in the current game.
.LP
For each hand,
.I cribbage
first prints the player's hand,
whose crib it is, and then asks the player
to discard two cards into the crib.  The cards are prompted for
one per line, and are typed as explained below.
.LP
After discarding,
.I cribbage
cuts the deck (if it is the player's
crib) or asks the player to cut the deck (if it's its crib); in the later
case, the appropriate response is a number from 0 to 39 indicating
how far down the remaining 40 cards are to be cut.
.LP
After cutting the deck, play starts with the non-dealer (the person
who doesn't have the crib) leading the first card.
Play continues, as per cribbage, until all cards are exhausted.
.I Cribbage
keeps track of the scoring of all points and the total of
the cards on the table.
.LP
After play, the hands are scored.
.I Cribbage
requests the player to
score his hand (and the crib, if it is his) by printing out the
appropriate cards (and the cut card enclosed in brackets).
Play continues until one player reaches the game limit (61 or 121).
.LP
A carriage return when a numeric input is expected is equivalent
to typing the lowest legal value; when cutting the deck this
is equivalent to choosing the top card.
.SH "SPECIFYING CARDS"
.LP
Cards are specified as
.I rank
followed by
.IR suit .
The
.IR rank s
may be specified as one of \fBa\fP, \fB2\fP, \fB3\fP, \fB4\fP, \fB5\fP,
\fB6\fP, \fB7\fP, \fB8\fP, \fB9\fP, \fBt\fP, \fBj\fP, \fBq\fP, and
\fBk\fP, or alternatively, one of \fBace\fP, \fBtwo\fP, \fBthree\fP,
\fBfour\fP, \fBfive\fP, \fBsix\fP, \fBseven\fP, \fBeight\fP,
\fBnine\fP, \fBten\fP, \fBjack\fP, \fBqueen\fP, and \fBking\fP.
.IR Suit s
may be specified as \fBs\fP, \fBh\fP, \fBd\fP, and \fBc\fP, or
alternatively as \fBspades\fP, \fBhearts\fP, \fBdiamonds\fP, and
\fBclubs\fP.  A card may be specified as
.IR "rank\ \ suit" ,
or
.IR rank "\ of\ " suit .
If the single letter
.I rank
and
.I suit
designations
are used, the space separating the
.I suit
and
.I rank
may be left out.
Also, if only one card of the desired
.I rank
is playable, typing the
.I rank
is sufficient.  For example, if your hand was \fB2h\fP, \fB4d\fP,
\fB5c\fP, \fB6h\fP, \fBjc\fP, \fBkd\fP and you wanted to discard
the king of diamonds, you could type any of \fBk\fP,
\fBking\fP, \fBkd\fP, \fBk\ d\fP, \fBk\ of\ d\fP, \fBking\ d\fP,
\fBking\ of\ d\fP, \fBk\ diamonds\fP, \fBk\ of\ diamonds\fP,
\fBking\ diamonds\fP, or \fBking\ of\ diamonds\fP.
.SH FILES
.ta 2i
/usr/games/cribbage
