.\"@(#)dbconfig.8 1.15 88/03/14 SMI;
.TH DBCONFIG 8 "27 March 1989"
.SH NAME
dbconfig \- initializes the dial box and the button box
.SH SYNOPSIS
.B /usr/etc/dbconfig
.SH DESCRIPTION
.IX "DB, initialize dial box and button box\(em \fLdbconfig\fR"
.B dbconfig
opens the designated serial port and sets its baud, parity and
transmission rates.
It also removes all stream modules already pushed upon it 
(such as
.BR ttcompat (4M)
and
.BR ldterm (4M))
and pushes the dial box and button box
stream module \*(lqdb\*(rq onto the device.
.B db
then holds the stream open to
maintain this configuration.
If the device 
.B /dev/dialbox
has not been created and linked to the serial port,
.B dbconfig 
will fail.
.PD
.SH "SEE ALSO"
.BR db (4M),
.BR ldterm (4M),
.BR ttcompat (4M),
.BR dialtest (6),
.BR buttontest (6)
