.\" @(#)defaults.5 1.1 92/07/30 SMI;
.TH DEFAULTS 5 "2 September 1987"
.SH NAME
defaults \- default specifications for SunView
.SH SYNOPSIS
.B ~/.defaults
.br
.B /usr/lib/defaults
.SH DESCRIPTION
.IX "defaults default" "" "\fLdefaults\fP \(em default specifications for SunView" ""
.IX SunView "default specifications for"
.IX default "specifications for SunView"
.IX specifications "default, for SunView"
To be supplied.
