.\" @(#)factor.6 1.1 92/07/30 SMI; from V7
.TH FACTOR 6 "17 March 1987"
.SH NAME
factor, primes \- factor a number, generate large primes
.SH SYNOPSIS
.B /usr/games/factor
[
.I number
]
.PP
.B /usr/games/primes
[
.I number
]
.SH DESCRIPTION
.I factor
reads lines from its standard input.
If it reads a positive number,
.I factor
will factor the number and print its prime
factors, printing each one the proper number of times.
.I factor
exits when it reads zero, a negative number, or something other than a
number.
If a
.I number
is given,
.I factor
will factor the number, print its prime factors, and exit.
.PP
.I primes
reads a number from the standard input and
prints all primes larger than the given number and smaller than
2\u\s832\s10\d (about 4.3\(mu10\u\s89\s10\d).  If a
.I number
is given,
.I primes
will use that number rather than reading one from the standard input.
.SH DIAGNOSTICS
`Ouch.' for input out of range or for garbage input.
