.\" @(#)hyphen.1 1.1 92/07/30 SMI; from S5R2 6.2
.TH HYPHEN 1 "28 March 1986"
.SH NAME
hyphen \- find hyphenated words
.SH SYNOPSIS
.B hyphen
[ 
.I filename 
]
.SH DESCRIPTION
.I hyphen\^
finds all the hyphenated words
ending lines in
.I filename
and prints them on the standard output.
If no arguments are given, the standard input
is used.
.SH EXAMPLE
The following will allow the proofreading of
.I nroff
hyphenation in
.IR textfile .
.PP
.RS
.ft L
nroff -ms textfile | hyphen
.ft R
.RE
.SH "SEE ALSO"
nroff(1)
.SH BUGS
.I hyphen
cannot cope with hyphenated
.I italic
(i.e., underlined) words;
it will often miss them completely, or mangle them.
.br
.I hyphen
occasionally gets confused, but with no ill effects other than
spurious extra output.
