.\" @(#)oldeyacc.1 1.1 92/07/30 SMI; from UCB 4.2
.TH OLDEYACC 1 "31 March 1987"
.SH NAME
eyacc \- modified yacc allowing much improved error recovery
.SH SYNOPSIS
.B /usr/old/eyacc
[
.B \-v
]
[
.I grammar
]
.SH DESCRIPTION
.IX "eyacc command"  ""  "\fLeyacc\fP \(em compiler generator"
.IX "programming tools"  "compiler generator"
.IX "compiler generator"
.TP
.B Note:
This program is considered to be obsolete, and will not be
distributed or supported in future Sun releases.
.LP
.I Eyacc
is a version of
.IR yacc (1),
that produces tables used by the Pascal system and its error recovery
routines.
.I Eyacc
fully enumerates test actions in its parser when an error token
is in the look-ahead set.
This prevents the parser from making undesirable reductions
when an error occurs before the error is detected.
The table format is different in
.I eyacc
than it was in the old
.I yacc,
as minor changes had been made for efficiency reasons.
.SH "SEE ALSO"
yacc(1)
.br
\fIPractical LR Error Recovery\fP by Susan L. Graham, Charles B. Haley
and W. N. Joy; SIGPLAN Conference on Compiler Construction, August 1979.
.SH BUGS
.I Pc
and its error recovery routines should be made into a library
of routines for the new
.I yacc.
