.\" @(#)recnews.1 1.1 92/07/30 SMI;
.TH RECNEWS 8 "6 January 1984"
.SH NAME
recnews \- receive unprocessed articles via mail
.SH SYNOPSIS
.BR /usr/lib/news/recnews " [ "
.IR newsgroup " [ " sender " ] ] "
.SH DESCRIPTION
.IX  "recnews command"  ""  "\fLrecnews\fP \(em receive unprocessed articles"
.IX  "receive unprocessed articles"  ""  "receive unprocessed articles \(em \fLrecnews\fP"
.IX  "network news"  "receive unprocessed articles"  ""  "receive unprocessed articles \(em \fLrecnews\fP"
.IX  news  "receive unprocessed articles"  ""  "receive unprocessed articles \(em \fLrecnews\fP"
.I Recnews
reads a letter from the standard input; determines the article title,
sender, and newsgroup; and gives the body to inews with the right
arguments for insertion.
.LP
If
.I newsgroup
is omitted, the to line of the letter is used.  If
.I sender
is omitted, the sender is determined from the from line of the letter.
The title is determined from the subject line.
.SH SEE ALSO
inews(1),
uurec(8),
sendnews(8),
readnews(1),
checknews(1)
