.TH RWALL 1 "1 February 1985"
.\" @(#)rwall.1 1.1 92/07/30 SMI;
.SH NAME
rwall \- write to all users over a network
.SH SYNOPSIS
.B rwall
host1 host2 ...
.br
.B rwall
.B \-n
netgroup1 netgroup2 ...
.br
.B rwall
.B \-h
host
.B \-n
netgroup
.SH DESCRIPTION
.IX  "write to all users on network"  ""  "write to all users on network \(em \fLrwall\fP"
.IX  network  rwall  ""  "\fLrwall\fP \(em write to all users"
.IX  "broadcast messages"  "rwall"  ""  "\fLrwall\fP \(em to all users on network"
.I Rwall
reads a message from standard input until end-of-file.
It then sends this message,
preceded by the line ``Broadcast Message ...'',
to all users logged in on the specified host machines.
With the
.B -n
option,
it sends to the specified network groups,
which are defined in
.IR netgroup (5).
.PP
A machine can only receive such a message if it is running
.IR rwalld (8),
which is normally started up from
.I /etc/servers
by the daemon
.IR inetd (8).
.SH FILES
/etc/servers
.SH "SEE ALSO"
wall(1), netgroup(5), rwalld(8), shutdown(8)
.SH BUGS
The timeout is fairly short in order to be able to send to
a large group of machines (some of which may be down)
in a reasonable amount of time.
Thus the message may not get thru to a heavily loaded machine.
