.\" @(#)suncoredemos.6 1.1 92/07/30 SMI
.TH SUNCOREDEMOS 6 "28 October 1983"
.SH NAME
suncoredemos \- demonstrate SunCore Graphics Package
.SH SYNOPSIS
.B /usr/demo/cproduct
.br
.B /usr/demo/cshademo
.br
.B /usr/demo/cvlsi
.SH DESCRIPTION
.I Suncoredemos
is a collection of simple programs demonstrating the SunCore
Graphics Package.  Each program is briefly described below.
These programs generate all graphics output using subroutine calls
to SunCore.  To exit each program,
generate an interrupt signal by typing the appropriate key (usually <DELETE>).
.IP cproduct 12
color Sun architecture demo
.IP
Requires Sun Color Graphics Display.
.IP cshademo 12
shaded surface polygons demo
.IP
Requires Sun Color Graphics Display.
.IP cvlsi 12
color vlsi layout demo
.IP
Requires Sun Color Graphics Display.
