.\" @(#)textswrc.5 1.1 92/07/30 SMI;
.TH TEXTSWRC 5 "2 September 1987"
.SH NAME
textswrc \- initialization file for SunView text windows
.SH SYNOPSIS
.B ~/.textswrc
.br
.B /usr/lib/textswrc
.SH DESCRIPTION
.IX "textswrc init" "" "\fLtextswrc\fP \(em initialization file for SunView text windows" ""
.IX SunView "initialization file for text windows"
.IX initial "SunView text window initialization file"
.IX start "SunView text window initialization file"
To be supplied.
