.\" @(#)uurec.8 1.1 92/07/30 SMI
.TH UUREC 8 "6 January 1984"
.SH NAME
uurec \- receive processed news articles via mail
.SH SYNOPSIS
uurec
.SH DESCRIPTION
.IX  "uurec command"  ""  "\fLuurec\fP \(em receive news articles"
.I uurec
reads news articles on the standard input sent by
.IR sendnews (8),
decodes them, and gives them to
.IR inews (1)
for insertion.
.SH SEE ALSO
inews(1),
readnews(1),
recnews(8),
sendnews(8),
newscheck(1)
