.\" @(#)ypcat.1 1.1 92/07/30 SMI; 
.TH YPCAT 1 "8 July 1985"
.SH NAME
ypcat - print values in a YP data base
.SH SYNOPSIS
.B ypcat
[
.B \-k
] 
[
.B \-t
] 
[
.B \-d
.I  domainname 
]
.I  mname
.br
.B ypcat
.B \-x
.IX  "ypcat command"  ""  "\fLypcat\fP \(em print values from YP database"
.IX  print "values from YP database \(em \fLypcat\fP"
.IX  "yellow pages"  "print values from database"  ""  "print values from database \(em \fLypcat\fP"
.SH DESCRIPTION
.I ypcat
prints out values in a yellow pages (YP) map specified by 
.IR mname ,
which may be either a
.I mapname
or a map 
.IR nickname .
Since
.I ypcat
uses the YP network services, no YP server is specified.
.LP
To look at the network-wide password database, 
.IR passwd.byname ,
(with the nickname
.IR passwd ).
type in:
.IP
.ft L
ypcat passwd
.ft P
.LP
Refer to ypfiles(5) and ypserv(8) for an overview of the yellow pages.
.SH OPTIONS
.IP \fB\-k\fR
Display the keys for those maps in which the values are null
or the key is not part of the value.
(None of the maps derived from files that have an ASCII version in
.I /etc
fall into this class.)
.IP \fB\-t\fR
Inhibit translation of 
.I mname 
to 
.I mapname.
For example,
.I "ypcat \-t passwd"
will fail because there is no map named
.IR passwd ,
whereas
.I "ypcat passwd"
will be translated to
.IR "ypcat passwd.byname" .
.IP \fB\-d\fR
Specify a domain other that the default domain.
The default domain is returned by
.IR domainname.
.IP \fB\-x\fR
Display the map nickname table.  
This lists the nicknames (\fImnames\fR\|)
the command knows of, and indicates the
.I mapname
associated with each
nickname.
.SH "SEE ALSO"
ypfiles(5), ypserv(8), ypmatch(1), domainname(8)
