#
# @(#)Makefile 1.1 92/07/30; SMI
#
# Copyright (c) 1987 by Sun Microsystems, Inc.
#

CPPFLAGS=-I../common/$(ARCH)

ASSRC = _getpgrp.s _kill.s _lseek.s _mknod.s _mount.s _setpgrp.s umount.s
MD_ASSRC = $(ASSRC:%.s=$(ARCH)/%.s)

