CHOWN=/etc/chown
INSTALLDIR=$(DESTDIR)/usr/demo/$(DIR)

.DEFAULT:
	sccs get -G$< $@

all: $(FILES)

install: all
	-mkdir $(INSTALLDIR) && $(CHOWN) bin $(INSTALLDIR)
	@set -x; for i in $(FILES); do \
		install $$i $(INSTALLDIR); done

clean:
