#
# @(#)Makefile 1.1 92/07/30 SMI; from S5R2 1.7
#

TARGET= SPARC
PCC=	../../pcc/sparc

include ../src/Makefile.common

# DO NOT DELETE THIS LINE -- make depend uses it

dag: ../src/dag.c
dag: /usr/include/stdio.h
dag: /usr/include/ctype.h
nmf: ../src/nmf.c
nmf: /usr/include/stdio.h
flip: ../src/flip.c
flip: /usr/include/stdio.h
flip: /usr/include/ctype.h
lpfx: ../src/lpfx.c
lpfx: /usr/include/stdio.h
lpfx: /usr/include/ctype.h
lpfx: $(LINT)/lerror.h
lpfx: $(MIP)/mip.h
lpfx: /usr/include/stdio.h
lpfx: ./ops.h
lpfx: $(MIP)/pcc_ops.h
lpfx: ./types.h
lpfx: $(MIP)/pcc_types.h
lpfx: ./node.h
lpfx: $(MIP)/pcc_node.h
lpfx: $(LINT)/machdep.h
lpfx: $(PCC)/align.h
lpfx: $(MIP)/pcc_types.h
lpfx: $(LINT)/lmanifest.h
lpfx: $(LINT)/lpass2.h
# DEPENDENCIES MUST END AT END OF FILE
# IF YOU PUT STUFF HERE IT WILL GO AWAY
# see make depend above
