.\" @(#)apropos.1 1.1 92/07/30 SMI; new for 4.1 from BSD
.TH APROPOS 1 "June 5, 1986"
.SH NAME
apropos \- locate commands by keyword lookup
.SH SYNOPSIS
.B apropos
.IR keyword .\|.\|.
.SH DESCRIPTION
.IX "apropos" "" "\fLapropos\fP \(em locate commands by keyword" ""
.LP
.B apropos
displays the man page name, section number,
and a short description for each man page whose
.SM NAME 
line contains
.IR keyword .
This information is contained in the
.B /usr/man/whatis
database created by
.BR catman (8). 
If 
.BR catman (8)
was not run, or was run with the 
.B \-n
option,
.B apropos
fails.
Each word is considered separately and the case of letters is ignored.
Words which are part of other words are considered;
for example, when looking for `compile',
.B apropos
finds all instances of `compiler' also.
.LP
.B apropos
is actually just the
.B \-k
option to the
.BR man (1)
command.
.LP
Try
.IP
.B example%  apropos password
.LP
and
.IP
.B example%  apropos editor
.LP
If the line starts
.RI ` filename ( section ") .\|.\|.'"
you can do
.RB ` "man \fIsection filename\fP" '
to display the man page for
.IR filename .
Try
.IP
.B example%  apropos format
.LP
and then
.IP
.B example%  man 3s printf
.LP
to get the manual page on the subroutine
.BR printf(\|) .
.SH FILES
.PD 0
.TP 20
.B /usr/man/whatis
data base
.PD
.SH "SEE ALSO"
.BR man (1),
.BR whatis (1),
.BR catman (8)
.SH DIAGNOSTICS
.TP
.B "/usr/man/whatis: No such file or directory"
This database does not exist.
.BR catman (8)
must be run to create it.
