.\"	@(#)cb.1 1.1 92/07/30 SMI; from 4.2 BSD and S5R2 6.2 9/2/83
.TH CB 1 "9 September 1987"
.SH NAME
cb \- a simple C program beautifier
.SH SYNOPSIS
.B cb
[
.B \-js
]
[
.B \-l
.I leng
]
[
.IR filename .\|.\|.
]
.SH DESCRIPTION
.IX "code formatter" "\fLcb\fR \(em C source format filter"
.IX  cb  ""  "\fLcb\fP \(em format filter for C source files"
.IX  "languages"  "cb"  ""  "\fLcb\fP \(em format filter for C sources"
.LP
.B cb
reads C programs either from its arguments or from the standard input
and writes them on the standard output with spacing and indentation
that displays the structure of the code.  
.LP
.BR indent (1)
is preferred.
.SH OPTIONS
With no options, 
.B cb
preserves all user 
.SM NEWLINE
characters.  
.TP
.B \-j
Join.
Split lines are put back together.
.TP
.B \-s
Standard C style.  Formats the code to the style of
Kernighan and Ritchie in
.IR "The C Programming Language" .
.TP
.BI \-l " leng"
Split lines longer than
.IR leng .
.SH "SEE ALSO"
.BR indent (1)
.LP
B.W. Kernighan and D.M. Ritchie,
.IR "The C Programming Language" ,
Prentice-Hall, 1978
.SH BUGS
.LP
Punctuation hidden in preprocessor statements can cause indentation 
errors. 
