.\" @(#)chkey.1 1.1 92/07/30 SMI;
.TH CHKEY 1 "18 January 1987"
.SH NAME
chkey \- create or change encryption key
.SH SYNOPSIS
.B chkey
.SH DESCRIPTION
.IX  "chkey"  ""  "\fLchkey\fP \(em create or change encryption key"
.IX  "encryption key, change, \fLchkey\fR commmand"
.LP
.B chkey
prompts the user for their login password, and uses it to encrypt
a new encryption key for the user to be stored in the
.BR publickey (5)
database.
.LP
If the entry for
.B nobody
in the
.B /etc/publickey
database has not been commented out,
.B chkey
can be used to create new entries.
If this entry has been commented out,
.B chkey
can only be used to change an existing entry.
.SH "SEE ALSO"
.BR keylogin (1),
.BR publickey (5),
.BR keyserv (8C),
.BR newkey (8)
