.\" @(#)clear_functions.1 1.1 92/07/30 SMI;
.TH CLEAR_FUNCTIONS 1 "24 September 1987"
.SH NAME
clear_functions \- reset the selection service to clear stuck function keys
.SH SYNOPSIS
.B clear_functions
.SH DESCRIPTION
.IX clear_functions "" "\fLclear_functions\fR \(em reset SunView selection service"
.LP
.B clear_functions 
instructs the selection service that no function keys are
currently depressed.  It is useful in cases where erroneous
programs have
reported a key press but not the corresponding release.
The usual symptom
for this situation is that all selections are secondary
(underscored rather
than inverted), even though no function keys are down.
.SH FILES
.LP
.B /usr/bin/selection_svc
.SH "SEE ALSO"
.LP
.TX SVBG
