.\" @(#)cluster.1 1.1 92/07/30 SMI;
.TH CLUSTER 1 "19 February 1988"
.SH NAME
cluster \- find the Application SunOS or Developer's Toolkit optional cluster containing a file
.SH SYNOPSIS
.B cluster
[
.I filename
] 
.SH AVAILABILITY
.LP
Available only on Sun 386i systems running a SunOS 4.0.\fIx\fR
release or earlier.  Not a SunOS 4.1 release feature.
.SH DESCRIPTION
.IX "cluster command" "" "\fLcluster\fP command"
.LP
.B cluster
finds the optional software cluster that contains a specified file.  If
the specified file is contained in one of the clusters in Application
Sun\s-1OS\s0 or Developer's Toolkit, the name of the cluster will be
printed on standard output.
.LP
Without arguments,
.B cluster
displays a summary of the clusters in Application Sun\s-1OS\s0 and Developers
Toolkit, including the load state and size of each cluster.
.SH EXAMPLES
.LP
To find the name of the cluster that contains the 
.B spell 
command:
.RS
.sp .5
.nf
.ft B
example% cluster spell
spellcheck
example%
.ft R
.fi
.RE
.LP
To display a summary of the clusters in Application Sun\s-1OS\s0 and
Developer's Toolkit:
.LP
.RS
.nf
.ta \w'    available 'u +\w'advanced_admin   'u +\w'diskette  'u
.ft B
.nf
% cluster
Application SunOS Clusters:
\&      available	cluster	size (bytes)
\&      ---------	-------	----
\&      yes	accounting	265K
\&      no	advanced_admin	501K
\&      \&.\|.\|.
.sp
Developer's Toolkit Clusters:
\&    available	cluster	size (bytes)
\&    ---------	-------	----
\&      no	base_devel	6907K
\&      \&.\|.\|.
.sp
space used by clusters: 6021K bytes
total space remaining: 20432K bytes
.RE
.fi
.fi
.LP
A cluster is available if it has been \*(lqloaded\*(rq using 
.BR load (1)
or if it has been \*(lqmounted\*(rq across the network.
.SH FILES
.PD 0
.TP 20
.B /usr/lib/load/*
data files
.PD
.SH "SEE ALSO"
.BR load (1),
.BR unload (1),
.BR toc (5)
.LP
.I "Sun386i System Setup and Maintenance"
.SH DIAGNOSTICS
.TP
.BI "The file " filename "is not in any of the optional software clusters."
The specified file is not part of the Application Sun\s-1OS\s0
or Developer's Toolkit.
