.\" @(#)colrm.1 1.1 92/07/30 SMI; from UCB 4.1
.TH COLRM 1 "9 September 1987"
.SH NAME
colrm \- remove characters from specified columns within each line
.SH SYNOPSIS
.B colrm
[
.I startcol
[
.I endcol
] ]
.SH DESCRIPTION
.IX  colrm  ""  "\fLcolrm\fP \(em remove columns from file"
.IX  files  "colrm command"  files  "\fLcolrm\fP \(em remove columns from"
.IX  columns  "remove from file \(em \fLcolrm\fP"
.IX  remove  "columns from file \(em \fLcolrm\fP"
.IX  delete  "columns from file \(em \fLcolrm\fP"
.LP
.B colrm
removes selected columns from a text file.  The text is
taken from standard input and copied to the standard output with the
specified columns removed.
.LP
If only
.I startcol
is specified, the columns of each line are removed
starting with
.I startcol
and extending to the end of the line.
If both
.I startcol
and
.I endcol
are specified, all columns between
.I startcol
and
.IR endcol ,
inclusive, are removed.
.LP
Column numbering starts with column 1.
.SH "SEE ALSO"
.BR expand (1)
