.\" @(#)comm.1 1.1 92/07/30 SMI; from S5R2 6.2 83/09/02
.TH COMM 1 "9 September 1987"
.SH NAME
comm \- display lines in common, and lines not in common, between two sorted lists
.SH SYNOPSIS
.B comm
.RB "[ " \-1 \||
.BR \-2 \||
.BR \-3 \||
.BR \-12 \||
.BR \-13 \||
.BR \-23 " ]"
.I filename1
.I filename2
.SH DESCRIPTION
.IX  comm  ""  "\fLcomm\fP \(em display common lines"
.IX  commands  "comm command"  files  "\fLcomm\fP \(em display common lines"
.LP
.B comm
reads
.I filename1
and 
.IR filename2 ,
which should be ordered in
.SM ASCII
collating sequence (see
.BR sort (1V)),
and produces three-column output when no options are specified:
.RS
.TP 3
\(bu
Column 1 contains lines that occur only in
.IR filename1 .
.TP
\(bu
Column 2 contains lines only in
.IR filename2 .
.TP
\(bu
Column 3 contains lines common to both files.
.RE
.LP
The filename
.RB ` \- '
means the standard input.
.SH OPTIONS
.LP
The following options can be used to suppress the indicated columns
from display.  You can specify 
.RB ` \-123 ',
but doing so suppresses all output.
.TP
.B \-1
Suppress column 1; omit lines only in
.IR filename1 .
.TP
.B \-2
Suppress column 2; omit lines only in
.IR filename2 .
.TP
.B \-3
Suppress column 3; omit lines common to both files.
.TP
.B \-12
Suppress columns 1 and 2; only show lines common to both files.
.TP
.B \-13
Suppress columns 1 and 3; only show lines in 
.IR filename2 .
.TP
.B \-23
Suppress columns 2 and 3; only show lines in 
.IR filename1 .
.SH "SEE ALSO"
.BR cmp (1),
.BR diff (1), 
.BR sort (1V),
.BR uniq (1)
.SH BUGS
.LP
The options
.IR suppress ,
rather than
.I select
the columns you indicate.
