.\" @(#)csh_builtins.1 1.1 92/07/30 SMI; 
.\" This is a hack to force csh builtins into the whatis database
.\" and to get the list of builtins to come up with the man command.
.TH CSH_BUILTINS 1
.SH NAME
csh, %, @, alias, bg, break, breaksw, case, continue, default, dirs, else, end, endif, endsw, eval, exec, exit, fg, foreach, glob, goto, hashstat, history, if, jobs, label, limit, logout, notify, onintr, popd, pushd, rehash, repeat, set, setenv, shift, source, stop, suspend, switch, then, umask, unalias, unhash, unlimit, unset, unsetenv, while \- C shell built-in commands, see \fBcsh\fR(1)
.SH C-SHELL BUILTIN COMMANDS
.nr zZ 1
.so man1/csh.1
.SH SEE ALSO
csh(1), sh(1)
