.\" @(#)domainname.1 1.1 92/07/30 SMI;
.TH DOMAINNAME 1 "16 November 1987"
.SH NAME
domainname \- set or display name of the current NIS domain
.SH SYNOPSIS
.B domainname
[ 
.I name-of-domain
]
.SH DESCRIPTION
.IX "domainname command"  ""  "\fLdomainname\fP \(em set/display domain name"
.IX "current domain, set or display name \(em \fLdomainname\fR"
.IX display  "current domain name \(em \fLdomainname\fR"
.IX set  "current domain name \(em \fLdomainname\fR"
.LP
Without an argument,
.B domainname
displays the name of the current domain, which typically
encompasses a group of hosts under the same administration.
As such, the name of a 
Network Information Service
(\s-1NIS\s0)
domain is normally also a valid Internet
domain name, and can be used in conjunction with the 
.BR sendmail (8)
and the name server
.BR named (8C).
.LP
Only the super-user can set the name of the domain, by giving
.B domainname
an argument; this can be done only in the startup script
.BR /etc/rc.local .
.SH SEE ALSO
.BR named (8C), 
.BR sendmail (8),
.BR ypinit (8)
.SH NOTES
.LP
The Network Information Service
(\s-1NIS\s0)
was formerly known as Sun Yellow Pages
(\s-1YP\s0). 
The functionality of the two remains the same;
only the name has changed.
