.\" @(#)enablenumlock.1 1.1 92/07/30 SMI;
.TH ENABLENUMLOCK 1 "6 October 1989"
.SH NAME
enablenumlock, disablenumlock \- enable or disable the numlock key
.SH SYNOPSIS
.B enablenumlock
.LP
.B disablenumlock
.SH AVAILABILITY
.LP
Available only on Sun 386i systems running a SunOS 4.0.\fIx\fR
release or earlier.  Not a SunOS 4.1 release feature.
.SH DESCRIPTION
.IX  "enablenumlock command"  ""  "\fLenablenumlock\fP \(em enable the NumLock key"
.IX  "disablenumlock command"  ""  "\fLdisablenumlock\fP \(em disable the NumLock key"
.LP
When you press the \*(lqNum Lock\*(rq key and then press one of the keys
numbered R1 through R15 on the right keypad,
the character on the upper part
of the key is generated rather than the key's function.
.LP
In previous releases, \*(lqNum Lock\*(rq was enabled only in
.SM DOS
windows and in some third-party UNIX applications.
Currently, \*(lqNum Lock\*(rq
is enabled by default for the right keypad in all SunView windows.
.LP
.B enablenumlock
re-enables \*(lqNum Lock\*(rq for applications that expect it to be enabled.
.SH SEE ALSO
.I Sun386i User's Guide
.SH BUGS
.LP
The default enabling of the
\*(lqNum Lock\*(rq key is incompatible with
some applications with special work around code to
enable the \*(lqNum Lock\*(rq key.
These applications require the use of
.BR disablenumlock .
.SM DOS
applications are not affected.
