.\" @(#)expand.1 1.1 92/07/30 SMI;
.TH EXPAND 1 "9 September 1987"
.SH NAME
expand, unexpand \- expand TAB characters to SPACE characters, and vice versa
.SH SYNOPSIS
.B expand
[
.I \-tabstop
] [
.I \-tab1,\|tab2,.\|.\|.,\|tabn
] [
\fIfilename\fR .\|.\|.
]
.br
.LP
.B unexpand
[
.B \-a
] [
\fIfilename\fR .\|.\|.
]
.SH DESCRIPTION
.IX "expand command"  ""  "\fLexpand\fP \(em expand tabs"
.IX "tabs, expand to spaces \(em \fLexpand\fR"
.IX "unexpand command"  ""  "\fLunexpand\fP \(em spaces to tabs"
.IX "spaces, to tabs \(em \fLunexpand\fR"
.IX convert  "tabs to spaces \fLexpand\fR"
.IX convert  "spaces to tabs \fLunexpand\fR"
.B expand
copies
.IR filename s
(or the standard input) to the standard
output, with 
.SM TAB
characters expanded to
.SM SPACE 
characters.
.SM BACKSPACE
characters are preserved into the output and decrement
the column count for 
.SM TAB
calculations.
.B expand
is useful for pre-processing character files (before sorting, looking at
specific columns, etc.) that contain 
.SM TAB
characters.
.LP
.B unexpand
copies
.IR filename s
(or the standard input) to the standard output,
putting 
.SM TAB
characters back into the data.
By default, only leading
.SM SPACE
and
.SM TAB
characters are converted to strings of
tabs, but this can be overridden by the 
.B \-a
option (see the 
.SM OPTIONS
section below).
.SH OPTIONS
.SS expand
.TP
.I \-tabstop
Specify as a single argument, sets
.SM TAB 
characters 
.I tabstop
.SM SPACE 
characters apart instead of the default 8.
.TP
.I \-tab1,\|tab2,.\|.\|.,\|tabn
Set 
.SM TAB
characters at the columns specified by 
.I tab1\fP\fB.\|.\|.
.SS unexpand
.TP
.B \-a
Insert 
.SM TAB
characters when replacing a run of
two or more
.SM SPACE
characters would produce a
smaller output file.  
