.\" @(#)fold.1 1.1 92/07/30 SMI; from UCB 4.1
.TH FOLD 1 "9 September 1987"
.SH NAME
fold \- fold long lines for display on an output device of a given width
.SH SYNOPSIS
.B fold
[
.BI \- width
] [
file 
\fB.\|.\|.\fP
]
.SH DESCRIPTION
.IX "fold command"  ""  "\fLfold\fP \(em fold long lines"
Fold the contents of the specified 
\fIfile\fPs,
or the standard input if no files are specified,
breaking the lines to have maximum width
.IR width .
The default for
.I width
is 80.
.I Width
should be a multiple of 8 if tabs are present, or the tabs should
be expanded using
.BR expand (1)
before using
.I fold.
.SH SEE\ ALSO
.BR expand (1)
.SH BUGS
Folding may not work correctly if underlining is present.
