.\" @(#)from.1 1.1 92/07/30 SMI; from UCB 4.1
.TH FROM 1 "9 September 1987"
.SH NAME
from \- display the sender and date of newly-arrived mail messages
.SH SYNOPSIS
.B from
[
.BI \-s " sender"
] [
.I username
]
.SH DESCRIPTION
.IX "from command"  ""  "\fLfrom\fP \(em who is mail from"
.IX "mail services"  "who is mail from \(em \fLfrom\fR"
.LP
.B from
prints out the mail header lines in your mailbox file to show you
who your mail is from.  If 
.I username
is specified, then 
.IR username 's
mailbox is examined instead of your own.
.SH OPTIONS
.TP 15
.BI \-s " sender"
Only display headers for mail sent by 
.IR sender .
.SH FILES
.PD 0
.TP 20
.B /var/spool/mail/*
.PD
.SH "SEE ALSO"
.BR biff (1),
.BR mail (1),
.BR old-prmail (1)
