.\" @(#)generic_args.1 1.1 92/07/30 SMI; 
.\" This is a hack to add SunView generic args to the man pages.
.TH GENERIC_ARGS 1
.SH NAME
generic_args \- generic options for SunView applications, see sunview(1)
.SH GENERIC SUNVIEW APPLICATION ARGUMENTS
.nr zZ 1
.so man1/sunview.1
.SH SEE ALSO
sunview(1)
