.TH HOSTNAME 1 "9 September 1987"
.\" @(#)hostname.1 1.1 92/07/30 SMI; from UCB 4.1
.SH NAME
hostname \- set or print name of current host system
.SH SYNOPSIS
.B hostname
[
.I name-of-host
]
.SH DESCRIPTION
.IX "hostname command"  ""  "\fLhostname\fP \(em display host name"
.IX display  "name of current host"
.IX display  "current host name"
.IX set  "name of current host"
.IX set  "current host name"
.LP
The
.B hostname
command prints the name of the current host, as given before the
\*(lqlogin\*(rq prompt.
The super-user can set the hostname by giving an argument; this
is usually done in the startup script
.BR /etc/rc.local .
.SH FILES
.PD 0
.TP 20
.B /etc/rc.local
.PD
.SH SEE ALSO
.BR gethostname (2)
