.\" @(#)hostid.1 1.1 92/07/30 SMI; from UCB 1 Apr 83
.TH HOSTID 1 "9 September 1987"
.SH NAME
hostid \- print the numeric identifier of the current host
.SH SYNOPSIS
.B hostid
.SH DESCRIPTION
.IX "hostid command"  ""  "\fLhostid\fP \(em display host ID"
.IX display  "identifier of current host"
.IX display  "current host identifier"
The
.B hostid
command prints the identifier of the current
host in hexadecimal.  This numeric
value is unique across all Sun hosts.
.SH SEE ALSO
.BR gethostid (2)
