.\" @(#)line.1 1.1 92/07/30 SMI; from S5R2 6.2
.TH LINE 1 "9 September 1987"
.SH NAME
line \- read one line
.SH SYNOPSIS
.B line
.SH DESCRIPTION
.IX line "" "\fLline\fR \(em read one line"
.B line
copies one line (up to a
.SM NEWLINE\s0)
from the standard
input and writes it on the standard output.  It
returns an exit code of 1 on
.SM EOF
and always prints a
.SM NEWLINE
at least.
It is often used within shell scripts to
read a line from the terminal.
.SH "SEE ALSO"
.BR sh (1),
.BR read (2V)
