.\" @(#)look.1 1.1 92/07/30 SMI; 
.TH LOOK 1 "17 August 1987"
.SH NAME
look \- find words in the system dictionary or lines in a sorted list
.SH SYNOPSIS
.B look
.RB [ " \-df " ]
.RB [ " \-t\fIc\fP " ]"
.I string
.RI [ " filename " ]
.SH DESCRIPTION
.IX  "look command"  ""  "\fLlook\fP \(em find lines in a sorted file"
.IX  find "lines in sorted file"  ""  "find lines in sorted file \(em \fLlook\fP"
.IX  file  "find lines in sorted"  ""  "find lines in sorted \(em \fLlook\fP"
.IX  "sorted file"  "find lines in"  ""  "find lines in \(em \fLlook\fP"
.IX  lines  "find, in sorted file"  ""  "find, in sorted file \(em \fLlook\fP"
.B look
consults a sorted
.I filename
and prints all lines that begin with
.IR string .
.LP
If no 
.IR filename
is specified,
.B look
uses
.B /usr/dict/words
with collating sequence
.BR \-df .
.SH OPTIONS
.TP 
.B \-d
Dictionary order.  Only letters, digits, 
.SM TAB
and
.SM SPACE
characters are used in comparisons.
.TP
.B \-f
Fold case.  Upper case letters aren't distinguished from lower case
in comparisons.
.TP
.BI \-t c
Set termination character.  All characters to the right of
.I c
in 
.I string
are ignored.
.SH FILES
.PD 0
.TP 20
.B /usr/dict/words
.PD
.SH "SEE ALSO"
.BR grep (1V),
.BR sort (1V)
