.\" @(#)mach.1 1.1 92/07/30 SMI; from UCB 4.1
.TH MACH 1 "9 September 1987"
.SH NAME
mach \- display the processor type of the current host
.SH SYNOPSIS
.B mach
.SH DESCRIPTION
.IX "mach command"  ""  "\fLmach\fP \(em display Sun processor"
.IX display  "processor of current Sun host"
The
.B mach
command displays the processor-type of the current Sun host.
.SH SEE ALSO
.BR arch (1),
.BR machid (1)
