#  @(#)Makefile 1.1 92/07/30 SMI;
#
#  Description file for making the section 1 manual page sources.
#
#  NOTE that the list of filenames in the description file must be
#  kept up to date with the actual manual pages, including ".so" files.

HERE=man1

# --------------------------------------------------------------- #

FILES= \
Intro.1 intro.1 List.1 list.1 \
Mail.1 acctcom.1 adb.1 addbib.1 adjacentscreens.1 admin.1 aedplot.1g \
alias.1 align_equals.1 apropos.1 ar.1v arch.1 as.1 at.1 atq.1 atrm.1 \
awk.1 banner.1v bar.1 basename.1v batch.1 bc.1 bg.1 bgplot.1g biff.1 \
bin-mail.1 binmail.1 break.1 breaksw.1 cal.1 calendar.1 cancel.1 \
capitalize.1 case.1 cat.1v cb.1 cc.1v cd.1 cdc.1 cflow.1v chdir.1 \
checkeq.1 checknr.1 chfn.1 chgrp.1 chkey.1 chmod.1v chsh.1 clear.1 \
clear_colormap.1 clear_functions.1 click.1 clock.1 cluster.1 cmdtool.1 \
cmp.1 col.1v colcrt.1 coloredit.1 colrm.1 comb.1 comm.1 compress.1 \
continue.1 cp.1 cpio.1 cpp.1 crontab.1 crtplot.1g csh.1 \
csh_builtins.1 csplit.1v ctags.1 ctrace.1v cu.1c cut.1v cxref.1v \
date.1v dbx.1 dbxtool.1 dc.1 dd.1 default.1 defaultsedit.1 \
defaults_from_input.1 defaults_merge.1 defaults_to_indentpro.1 \
defaults_to_mailrc.1 delta.1 deroff.1 df.1v diff.1 diff3.1v diffmk.1 \
desktop.1 \
dircmp.1v dirname.1v dirs.1 dis.1 disablenumlock.1 domainname.1 dos.1 \
dos2unix.1 du.1v dumbplot.1g dumpkeys.1 e.1 echo.1v ed.1 edit.1 \
egrep.1v eject.1 else.1 enablenumlock.1 end.1 endif.1 endsw.1 enroll.1 \
env.1 eqn.1 error.1 eval.1 ex.1 exec.1 exit.1 expand.1 expr.1v false.1 \
fdformat.1 fg.1 fgrep.1v file.1 find.1 finger.1 fmt.1 fmt_mail.1 fold.1 \
fontedit.1 foption.1 foreach.1 from.1 ftp.1c gcore.1 generic_args.1 \
get.1 get_alarm.1 getopt.1v getoptcvt.1 getopts.1 get_selection.1 \
gfxtool.1 gigiplot.1g glob.1 goto.1 gprof.1 graph.1g grep.1v groups.1 \
hashcheck.1 hashmake.1 hashstat.1 head.1 help.1 help_open.1 \
help_viewer.1 history.1 hostid.1 hostname.1 hpplot.1g i386.1 iAPX286.1 \
iapx286.1 iconedit.1 id.1v if.1 implot.1g indent.1 \
indentpro_to_defaults.1 indxbib.1 inline.1 input_from_defaults.1 \
insert_brackets.1 install.1 ipcrm.1 ipcs.1 jobs.1 join.1 keylogin.1 \
keylogout.1 kill.1 label.1 last.1 lastcomm.1 ld.1 ld.so.1 ldd.1 leave.1 \
lex.1 limit.1 line.1 lint.1v ln.1v load.1 loadc.1 loadkeys.1 \
lockscreen.1 lockscreen_default.1 logger.1 login.1 logname.1 logout.1 \
look.1 lookbib.1 lorder.1 lp.1 lpq.1 lpr.1 lprm.1 lpstat.1 lptest.1 \
ls.1v lsw.1 m4.1v m68k.1 mach.1 machid.1 mail.1 mailrc_to_defaults.1 \
mailtool.1 make.1 man.1 mc68010.1 mc68020.1 mesg.1 mkdir.1 mkstr.1 \
more.1 mps.1 mpstat.1 \
mt.1 mv.1 nawk.1 neqn.1 newgrp.1 nice.1 nl.1v nm.1 nohup.1v \
notify.1 nroff.1 objdump.1 od.1v old-ccat.1 old-clocktool.1 \
old-compact.1 old-eyacc.1 old-filemerge.1 old-make.1 old-perfmon.1 \
old-prmail.1 old-pti.1 old-setkeys.1 old-sun3cvt.1 old-syslog.1 \
old-ttytool.1 old-uncompact.1 old-vc.1 on.1c onintr.1 organizer.1 \
othertools.1 overview.1 pack.1v page.1 pagesize.1 passwd.1 paste.1v \
pax.1v paxcpio.1v pcat.1v pdp11.1 perfmeter.1 pg.1v plot.1g popd.1 \
pr.1v printenv.1 prof.1 prs.1 prt.1 ps.1 ptx.1 pushd.1 pwd.1 quota.1 \
ranlib.1 rasfilter8to1.1 rastrepl.1 rcp.1c rdist.1 red.1 refer.1 \
rehash.1 remove_brackets.1 repeat.1 reset.1 rev.1 ring_alarm.1 \
rlogin.1c rm.1 rmdel.1 rmdir.1 roffbib.1 rpcgen.1 rsh.1c rup.1c \
ruptime.1c rusers.1c rwall.1c rwho.1c sact.1 sccs.1 sccs-admin.1 sccs-cdc.1 \
sccs-comb.1 sccs-delta.1 sccs-get.1 sccs-help.1 sccs-prs.1 sccs-prt.1 \
sccs-rmdel.1 sccs-sact.1 sccs-sccsdiff.1 sccs-unget.1 sccs-val.1 \
sccsdiff.1 screenblank.1 screendump.1 screenload.1 script.1 \
scrolldefaults.1 sdiff.1v sed.1v selection_svc.1 set.1 set_alarm.1 \
setenv.1 setkeys.1 sh.1 shelltool.1 shift.1 shift_lines.1 size.1 \
sleep.1 snap.1 soelim.1 sort.1v sortbib.1 source.1 sparc.1 spell.1 \
spellin.1 spellout.1 spline.1g split.1 stop.1 strings.1 strip.1 stty.1v \
stty_from_defaults.1 su.1v sum.1v sun.1 suntools.1 sunview.1 suspend.1 \
sv_acquire.1 sv_release.1 swin.1 switch.1 switcher.1 symorder.1 sync.1 \
sysex.1 syswait.1 t300.1g t300s.1g t4013.1g t450.1g tabs.1v tail.1 \
talk.1 tar.1 tbl.1 tcopy.1 tcov.1 tee.1 tek.1g tektool.1 telnet.1c \
test.1v textedit.1 textedit_filters.1 tftp.1c then.1 time.1v tip.1c \
toolplaces.1 touch.1v tput.1v tr.1v trace.1 traffic.1c troff.1 true.1 \
tset.1 tsort.1 tty.1 u370.1 u3b.1 u3b15.1 u3b2.1 u3b5.1 ul.1 umask.1 \
unalias.1 uname.1 uncompress.1 unexpand.1 unget.1 unhash.1 unifdef.1 \
uniq.1 units.1 unix2dos.1 unlimit.1 unload.1 unloadc.1 unpack.1v \
unset.1 unsetenv.1 unwhiteout.1 uptime.1 users.1 ustar.1v uucp.1c \
uudecode.1c uuencode.1c uulog.1c uuname.1c uupick.1c uusend.1c \
uustat.1c uuto.1c uux.1c vacation.1 val.1 vax.1 vedit.1 vfontinfo.1 \
vgrind.1 vi.1 view.1 vplot.1 vswap.1 vtroff.1 vwidth.1 w.1 wait.1 \
wall.1 wc.1 what.1 whatis.1 whereis.1 which.1 while.1 who.1 whoami.1 \
whois.1 write.1 xargs.1v xget.1 xsend.1 xstr.1 yacc.1 yes.1 ypcat.1 \
ypmatch.1 yppasswd.1 ypwhich.1 zcat.1

# --------------------------------------------------------------- #

include ../Makefile.master
