.\" @(#)mesg.1 1.1 92/07/30 SMI;
.TH MESG 1 "9 September 1987"
.SH NAME
mesg \- permit or deny messages on the terminal
.SH SYNOPSIS
.B mesg
[
.B n
] [
.B y
]
.SH DESCRIPTION
.IX  "mesg command"  ""  "\fLmesg\fP \(em permit or deny messages"
.IX  messages  "permit or deny"  ""  "permit or deny \(em \fLmesg\fP"
.IX  "permit messages"  ""  "permit messages \(em \fLmesg\fP"
.IX  "allow messages"  ""  "allow messages \(em \fLmesg\fP"
.IX  "deny messages"  ""  "deny messages \(em \fLmesg\fP"
.IX  "inhibit messages"  ""  "inhibit messages \(em \fLmesg\fP"
.IX  communications  "mesg"  ""  "\fLmesg\fR \(em permit or deny messages"
.B mesg
with argument
.B n
forbids messages with
.BR write (1)
by revoking non-user write permission on the user's terminal.
.B mesg
with argument
.B y
reinstates permission.  All by itself,
.B mesg
reports the current state without changing it.
.SH FILES
.PD 0
.TP 20
.B /dev/tty*
.PD
.SH "SEE ALSO"
.BR write (1),
.BR talk (1)
.SH DIAGNOSTICS
Exit status is 0 if messages are receivable, 1 if not, 2 on error.
