.\" @(#)mpstat.1 1.1 92/07/30 SMI
.TH MPSTAT 1 "6 March 1991"
.SH NAME
mpstat \- show multi-processor usage
.SH SYNOPSIS
.B /usr/kvm/mpstat
[
.I interval
[
.I count
] ]
.SH AVAILABILITY
.LP
This program is only available on sun4m architectures.
.SH DESCRIPTION
.IX  "mpstat command"  ""  "\fLmpstat\fP \(em show multi-processor usage"
.B mpstat
enters the system and shows average and per-processor
percentage usage data during a
particular time interval.   The first
group of data represents the average of all the processors in the
system while the second and subsequent data groups represent
particular processors, with their particular name designations above
each group.
.LP
Without an 
.I interval
or 
.I count 
option,
.B vmstat
displays a one-line summary of MP system activity
since the system has been booted.  If
.I interval
is specified,
.B vmstat
summarizes activity over the last
.I interval
seconds.  If a
.I count
is given, the statistics are repeated
.I count
times.
.LP
The particular fields of each data group give a breakdown of
percentage usage of CPU time:
.TP
.B us
user time for normal processes
.TP
.B ni
time for processes with an altered scheduling priority (\fInice(1)\fR)
.TP
.B sy
system time
.TP
.B id
.SM CPU
idle
.SH FILES
.PD 0
.TP 20
.B /dev/kmem
.TP
.B /vmunix
.PD
.SH "SEE ALSO"
.BR mps(1),
.BR nice(1),
.BR ps(1),
.BR vmstat(8)
