.\" @(#)old-sun3cvt.1 1.1 92/07/30 SMI; 
.TH OLD-SUN3CVT 1 "16 November 1987"
.SH NAME
old-sun3cvt \- convert large Sun-2 system executables to Sun-3 system executables
.SH SYNOPSIS
.B /usr/old/sun3cvt
[ 
.I oldfile 
[
.I newfile
] ]
.SH DESCRIPTION
.IX sun3cvt "" "\fLsun3cvt\fR \(em convert large Sun-2 executables to Sun-3"
.LP
Note: This program is considered to be obsolete, and will not be 
distributed or supported in future Sun releases. 
.LP 
.B sun3cvt
converts an old Sun-2 system program file (predating Sun release 3.0) into a 
Sun-3 system executable file.
.LP
The default 
.I oldfile 
is 
.BR a.out .  
The default 
.I newfile 
is 
.BR sun3.out .
.LP
.B sun3cvt 
attempts to create a file of the same type (magic number).  
However, for sharable-text files with less than 128kb
of text, the new file will not be sharable (since Sun-3 data
segments must begin on 128kb boundaries).  Also, most programs
have some text in the data segment as a consequence of
the new larger Sun-3 system page and segment sizes.
.LP
.BR execve (2V) 
executes an old Sun-2 system program file, but the
program's text is not sharable.  Old pure-text programs with text segments 
larger than 128kb can be made sharable on machines running release 
3.0 or subsequent releases by using 
.BR sun3cvt .
.SH FILES
.PD 0
.TP 20
.B a.out
.RI default " oldfile "
.TP
.B sun3.out
.RI default " newfile "
.PD
.SH SEE ALSO
.BR execve (2V)
