.\" @(#)old-pti.1 1.1 92/07/30 SMI; from UCB 4.1
.TH OLD-PTI 1 "16 November 1987"
.SH NAME
old-pti \- phototypesetter interpreter
.SH SYNOPSIS
.B /usr/old/pti
[
.I filename .\|.\|.
]
.SH DESCRIPTION
.IX  "pti command"  ""  "\fLpti\fP \(em (old) \fLtroff\fP interpreter"
.IX  "document production"  "pti command"  ""  "\fLpti\fP \(em (old) \fLtroff\fP interpreter"
.IX  "interpret (old) troff output pti"  ""  "interpret (old) \fLtroff\fP output \(em \fLpti\fP"
.IX  "CAT interpreter"  ""  "C/A/T interpreter \(em \fLpti\fP"
.LP
Note: This program is considered to be obsolete, and will not be 
distributed or supported in future Sun releases. 
.LP 
.B pti
shows the commands in a stream from the standard output of
.BR troff (1)
using
.BR troff 's
.B \-t
option, interpreting the  commands as they would act on the typesetter.
Horizontal motions show as counts in internal units and
are marked with 
.BR < " and " > 
indicating left and right motion.
Vertical space is called
.I leading
and is also indicated.
.LP
The output is really cryptic unless you are an experienced C/A/T
hardware person.  It is better to use 
.RB ` "troff\ \ \-a" '.
.SH SEE ALSO
.BR troff (1)
