.\" @(#)old-eyacc.1 1.1 92/07/30 SMI; from UCB 4.2
.TH OLD-EYACC 1 "24 September 1987"
.SH NAME
old-eyacc \- modified yacc allowing much improved error recovery
.SH SYNOPSIS
.B /usr/old/eyacc
[
.B \-v
]
.RI [ " grammar " ]
.SH DESCRIPTION
.IX "eyacc command"  ""  "\fLeyacc\fP \(em compiler generator"
.IX "programming tools"  "compiler generator"
.IX "compiler generator"
.B eyacc
is a version of
.BR yacc (1),
that produces tables used by the Pascal system and its error recovery
routines.
.B eyacc
fully enumerates test actions in its parser when an error token
is in the look-ahead set.
This prevents the parser from making undesirable reductions
when an error occurs before the error is detected.
The table format is different in
.B eyacc
than it was in the old
.BR yacc ,
as minor changes had been made for efficiency reasons.
.SH "SEE ALSO"
.BR yacc (1)
.LP
.I Practical \s-1LR\s0 Error Recovery
by Susan L. Graham, Charles B.
Haley
and W. N. Joy;
.SM SIGPLAN
Conference on Compiler Construction, August 1979.
.SH BUGS
.B pc
and its error recovery routines should be made into a library
of routines for the new
.BR yacc .
