.\" @(#)old-prmail.1 1.1 92/07/30 SMI; from UCB 4.1
.TH OLD-PRMAIL 1 "31 March 1987"
.SH NAME
old-prmail \- display waiting mail
.SH SYNOPSIS
.B /usr/old/prmail
.RI [ " user " "] .\|.\|."
.SH DESCRIPTION
.IX  "prmail command"  ""  "\fLprmail\fP \(em print waiting mail"
.IX  mail  "print waiting"  ""  "print waiting \(em \fLprmail\fP"
.IX  print "print waiting mail \(em \fLprmail\fP"
.IX  display "waiting mail \(em \fLprmail\fP"
.LP
Note: This program is considered to be obsolete, and will not be 
distributed or supported in future Sun releases. 
.LP 
.B prmail
displays waiting mail for you, or the specified
.IR user s.
The mail is not disturbed.
.SH FILES
.PD 0
.TP 20
.BR /var/spool/mail/ *	
waiting mail files
.PD
.SH SEE ALSO
.BR biff (1), 
.BR bin-mail (1),
.BR from (1),
.BR mail(1)
