.\" @(#)pagesize.1 1.1 92/07/30 SMI; from UCB 4.2
.TH PAGESIZE 1 "9 September 1987"
.SH NAME
pagesize \- display the size of a page of memory
.SH SYNOPSIS
.B pagesize
.SH DESCRIPTION
.IX  "pagesize command"  ""  "\fLpagesize\fP \(em display page size"
.IX  display "page size \(em \fLpagesize\fP"
.IX  "page size, display \(em \fLpagesize\fP"
.B pagesize
prints the size of a page of memory in bytes, as
returned by
.BR getpagesize (2).
This program is useful in constructing portable
shell scripts.
.SH SEE ALSO
.BR getpagesize (2)
