.\" @(#)printenv.1 1.1 92/07/30 SMI; from UCB 4.1
.TH PRINTENV 1 "9 September 1987"
.SH NAME
printenv \- display environment variables currently set
.SH SYNOPSIS
.B printenv
[
.I variable
]
.SH DESCRIPTION
.IX  "printenv command"  ""  "\fLprintenv\fP \(em display environment"
.IX  environment  "display variables"  ""  "display variables \(em \fLprintenv\fP"
.IX  "login environment"  "display variables"  ""  "display variables \(em \fLprintenv\fP"
.LP
.B printenv
prints out the values of the variables in the environment.  If a
.I variable
is specified, only its value is printed.
.SH SEE ALSO
.BR csh (1),
.BR sh (1),
.BR stty (1V),
.BR tset (1),
.BR environ (5V)
.SH DIAGNOSTICS
.LP
If a
.I variable
is specified and it is not defined in the environment,
.B printenv
returns an exit status of
.BR 1 .
