.\" @(#)quota.1 1.1 92/07/30 SMI; from UCB 4.2
.TH QUOTA 1 "9 September 1987"
.UC 4
.SH NAME
quota \- display a user's disk quota and usage
.SH SYNOPSIS
.B quota
[
.B \-v
] [
.I username
]
.SH DESCRIPTION
.IX "quota command"  ""  "\fLquota\fP \(em display disk usage and limits"
.IX "file system"  "display disk usage and limits quota" ""  "display disk usage and limits \(em \fLquota\fP"
.IX display  "disk usage and limits quota"  ""  "disk usage and limits \(em \fLquota\fP"
.IX  limits "disk space \(em \fLquota\fP"
.B quota
displays users' disk usage and limits.
Only the super-user may use the optional
.I username
argument to view the limits of users other than himself.
.LP
.B quota
without options displays only warnings
about mounted file systems where usage is over quota.
Remotely mounted file systems which are
mounted with the ``noquota'' option (see
.BR fstab (5))
are ignored.
.SH OPTIONS
.TP
.B \-v
Display user's quotas on all mounted file systems where quotas exist.
.SH FILES
.PD 0
.TP 20
.B quotas
quota file at the file system root
.TP
.B /etc/mtab
list of currently mounted filesystems
.PD
.SH "SEE ALSO"
.BR quotactl (2),
.BR fstab (5),
.BR edquota (8),
.BR quotaon (8),
.BR rquotad (8C)
