.\" @(#)rastrepl.1 1.1 92/07/30 SMI;
.TH RASTREPL 1 "24 September 1987"
.SH NAME
rastrepl \- magnify a raster image by a factor of two
.SH SYNOPSIS
.B rastrepl
.RI [ " input-file " [ " output-file " ]]
.SH DESCRIPTION
.IX  "rastrepl command"  ""  "\fLrastrepl\fP \(em magnify raster image"
.IX  "magnify raster image"  ""  "magnify raster image \(em \fLrastrepl\fP"
.LP
.B rastrepl
reads the rasterfile
.I input-file
(the standard input default) and converts it to
the rasterfile
.I output-file
(the standard output default) which is twice as large in width and height.
Pixel replication is used to magnify the image.
The output file has the same type as the input file.
.SH EXAMPLES
.LP
The following command:
.IP
.B
example% screendump  |  rastrepl  |  lpr \-Pversatec \-v
.LP
sends a rasterfile containing the current frame buffer contents to the
Versatec plotter, doubling the size of the image so that it fills a
single page.
.SH FILES
.PD 0
.TP 20
.B /usr/lib/rasfilters/*
filters for non-standard rasterfile formats
.PD
.SH SEE ALSO
.BR lpr (1),
.BR screendump (1),
.BR screenload (1)
.LP
.TX PIXRCT
