.\" @(#)rev.1 1.1 92/07/30 SMI;
.TH REV 1 "9 September 1987"
.SH NAME
rev \- reverse the order of characters in each line
.SH SYNOPSIS
.B rev
[
.I filename
] .\|.\|.
.SH DESCRIPTION
.IX  "rev command"  ""  "\fLrev\fP \(em reverse lines in file"
.IX  "reverse lines in file"  ""  "reverse lines in file \(em \fLrev\fP"
.IX  file  "reverse lines in"  ""  "reverse lines in \(em \fLrev\fP"
.IX  "text processing utilities"  "reverse lines in file"  ""  "reverse lines in file \(em \fLrev\fP"
.B rev
copies the named files to the standard output,
reversing the order of characters in every line.
If no file is specified, the standard input is copied.
