.\" @(#)sccs-sccsdiff.1 1.1 92/07/30 SMI;
.TH SCCS-SCCSDIFF 1 "30 June 1988"
.SH NAME
sccs-sccsdiff, sccsdiff \- compare two versions of an SCCS file
.SH SYNOPSIS
.B /usr/sccs/sccsdiff
[
.B \-p
]
.BI \-r sid
.BI \-r sid
[
.I diff-options
]
.I s.filename
.SH DESCRIPTION
.IX  "sccsdiff command"  ""  "\fLsccsdiff\fP \(em compare versions of SCCS file"
.IX  compare "versions of SCCS file \(em \fLsccsdiff\fP"
.IX  "SCCS commands"  sccsdiff  ""  "\fLsccsdiff\fP \(em compare versions of SCCS file"
.B sccsdiff
compares two versions of an
.SM SCCS
file and displays the differences between
the two versions.  Any number of
.SM SCCS
files may be specified; the options specified apply to all
named
.BR s. files.
.SH OPTIONS
.TP
.B \-p
Pipe output for each file through
.BR pr (1V).
.TP
.BI \-r sid
Specify a version corresponding to the indicated
.SM SCCS
delta
.SM ID\s0
(\s-1SID\s0)
for comparison.  Versions are passed to
.BR diff (1)
in the order given.
.TP
.I diff-options
Pass options to
.BR diff (1),
including:
.BR \-c ,
.BR \-e ,
.BR \-f ,
.BR \-h ,
.B \-b
and
.BR \-D .
.SH FILES
.TP 20
.B /tmp/get?????
temporary files
.SH "SEE ALSO"
.BR diff (1),
.BR sccs (1),
.BR sccs-delta (1),
.BR sccs-get (1),
.BR sccs-help (1),
.BR sccs-prs (1),
.BR sccs-prt (1),
.BR what (1),
.BR sccsfile (5)
.LP
.TX PUL
.SH DIAGNOSTICS
.PD 0
.TP 10
.IB filename ": No differences"
If the two versions are the same.
.LP
Use the
.SM SCCS
.B help
command for explanations of other messages (see
.BR sccs-help (1)).
