.\" @(#)sccs-help.1 1.1 92/07/30 SMI;
.TH SCCS-HELP 1 "28 June 1988"
.SH NAME
sccs-help, help \- ask for help regarding SCCS error or warning messages
.SH SYNOPSIS
.B /usr/sccs/help
[
.I argument
] .\|.\|.
.SH DESCRIPTION
.IX "help command"  ""  "\fLhelp\fP \(em get SCCS help"
.IX "SCCS commands"  "help command"  ""  "\fLhelp\fP \(em get SCCS help"
.B help
retrieves information to further explain errors messages and warnings
from
.SM SCCS
commands.  It also provides some information about
.SM SCCS
command usage.  If no arguments are given,
.B help
prompts for one.
.LP
An
.I argument
may be a message number (which normally appears
in parentheses following each
.SM SCCS
error or warning message), or an
.SM SCCS
command name.
.B help
responds with an explanation of the message or a usage line for
the command.
.LP
When all else fails, try
.RB ` "/usr/sccs/help\ \ stuck" '.
.SH FILES
.PD 0
.TP 20
.B /usr/lib/help
directory containing files of message text.
.TP
.B /usr/sccs/help
.PD
.SH SEE ALSO
.BR sccs (1),
.BR sccs-admin (1),
.BR sccs-cdc (1),
.BR sccs-comb (1),
.BR sccs-delta (1),
.BR sccs-get (1),
.BR sccs-prs (1),
.BR sccs-prt (1),
.BR sccs-rmdel (1),
.BR sccs-sact (1),
.BR sccs-sccsdiff (1),
.BR sccs-unget (1),
.BR sccs-val (1),
.BR what (1),
.BR sccsfile (5)
