.\" @(#)script.1 1.1 92/07/30 SMI; from UCB 4.1
.TH SCRIPT 1 "9 September 1987"
.SH NAME
script \- make typescript of a terminal session
.SH SYNOPSIS
.B script
[
.B \-a
] [
.I filename
]
.SH DESCRIPTION
.IX  "script command"  ""  "\fLscript\fP \(em make script of terminal session"
.IX  "create" "script of terminal session \(em \fLscript\fP"
.IX  login  "make script of session"  ""  "make script of session \(em \fLscript\fP"
.IX  terminal  "make script of session"  ""  "make script of session \(em \fLscript\fP"
.LP
.B script
makes a typescript of everything printed on your terminal.
The typescript is written to
.IR filename ,
or appended to
.IR filename
if the
.B \-a
option is given.  It can be sent to the line printer later with
.BR lpr (1).
If no file name is given, the typescript is saved in the file
.BR typescript .
.LP
The script ends when the forked shell exits.
.SH OPTIONS
.TP
.B \-a
Append the script to the specified file instead of writing over it.
.  \".LP
.  \"This program is useful when using a crt and a hard-copy
.  \"record of the dialog is desired, as for a student handing
.  \"in a program that was developed on a crt when hard-copy
.  \"terminals are in short supply.
.SH SEE ALSO
.BR lpr (1)
.SH BUGS
.LP
.B script
places
.I everything
in the log file.  This is not
what the naive user expects.
