.\" @(#)selection_svc.1 1.1 92/07/30 SMI;
.TH SELECTION_SVC 1 "21 December 1987"
.SH NAME
selection_svc \- SunView selection service
.SH SYNOPSIS
.B selection_svc
.RB [ " \-d " ]
.SH AVAILABILITY
This command is available with the
.TX SVBG 
software installation option.  Refer to
.TX INSTALL
for information on how to install optional software.
.SH DESCRIPTION
.IX "selection_svc" "" "\fLselection_svc\fR"
.LP
The SunView selection service handles the
state and rank of various selections
for its client programs.  A selection service
is started automatically by
.BR sunview (1).
However, you can also start one explicitly using the
.B selection_svc
command.
.SH OPTIONS
.TP
.B \-d
Debug a client program.  Use the alternate
socket provided for testing and
debugging a client program.   The second selection
service invoked with the
.B \-d
handles a different set of selections, and
can co-exist with one started in
the normal fashion.  Each service responds
only to requests directed to its
own socket.  The client to be debugged
can be directed to use the ``debugging''
service by using the
.B seln_use_test_service()
procedure, as described in the
.TX SVSPG .
.SH SEE ALSO
.TP
.BR sunview (1)
.LP
.TX SVBG
.LP
.TX SVSPG
