.\" @(#)sleep.1 1.1 92/07/30 SMI; from UCB 4.2
.TH SLEEP 1 "9 September 1987"
.SH NAME
sleep \- suspend execution for a specified interval
.SH SYNOPSIS
.B sleep
.I time
.IX  "sleep command"  ""  "\fLsleep\fP \(em suspend execution"
.IX  "suspend execution"  ""  "suspend execution \(em \fLsleep\fP"
.SH DESCRIPTION
.B sleep
suspends execution for
.I time
seconds.
It is used to execute a command after a certain amount of time as in:
.IP
.B (sleep 105; command)&
.LP
or to execute a command every so often, as in:
.RS
.nf
.ft B
while true
do
.RS
.ft B
command
sleep 37
.RE
.B done
.fi
.RE
.SH "SEE ALSO"
.BR sleep (3V)
.SH BUGS
.I time
must be less than 2,147,483,647 seconds.
