.\" @(#)soelim.1 1.1 92/07/30 SMI; from UCB 4.2
.TH SOELIM 1 "9 September 1987"
.SH NAME
soelim \- resolve and eliminate .so requests from nroff or troff input
.SH SYNOPSIS
.B soelim
[
.I filename
\&.\|.\|. ]
.SH AVAILABILITY
This command is available with the
.I Text
software installation option.  Refer to
.TX INSTALL
for information on how to install optional software.
.SH DESCRIPTION
.IX  "soelim command"  ""  "\fLsoelim\fP \(em eliminate \&.so's from nroff input"
.IX  "eliminate sos from nroff input"  ""  "eliminate \&.so's from nroff input \(em \fLsoelim\fP"
.IX  "document production"  soelim  ""  "\fLsoelim\fP \(em eliminate \&.so's from nroff input"
.IX "nroff utilities" soelim "\fLnroff\fR utilities" "\fLsoelim\fR \(em eliminate \fL.so\fR's, incorporate sourced-in files"
.IX "troff utilities" soelim "\fLtroff\fR utilities" "\fLsoelim\fR \(em eliminate \fL.so\fR's, incorporate sourced-in files"
.LP
.B soelim
reads the specified files or the standard input and
performs the textual inclusion implied by the
.BR nroff (1)
directives of the form
.IP
.BI \&.so " somefile"
.LP
when they appear at the beginning of input lines.
This is useful since programs such as
.BR tbl (1)
do not normally do this; it allows the placement of individual tables
in separate files to be run as a part of a large document.
.LP
An argument consisting of
.RB ` \- '
is taken to be a file name corresponding to the standard input.
.LP
Note: inclusion can be suppressed by using
.RB `\| \' \|'
instead of
`\|\fB\.\fP\|',
that is,
.IP
.B \' so /usr/share/lib/tmac/tmac.s
.SH EXAMPLE
.LP
A sample usage of
.B soelim
would be
.IP
.B soelim exum?.n | tbl | nroff \-ms | col | lpr
.SH SEE\ ALSO
.BR colcrt (1),
.BR more (1),
.BR nroff (1),
.BR tbl (1)
.\".SH BUGS
.\"The format of the source commands must involve no strangeness \-
.\"exactly one space must precede and no spaces follow the file name.
