.\" @(#)split.1 1.1 92/07/30 SMI;
.TH SPLIT 1 "9 September 1987"
.SH NAME
split \- split a file into pieces
.SH SYNOPSIS
.B split
[
.BI \- number
] [
.I infile
[
.I outfile
] ]
.SH DESCRIPTION
.IX  "split command"  ""  "\fLsplit\fP \(em split file into pieces"
.IX  file  "split into pieces"  ""  "split into pieces \(em \fLsplit\fP"
.IX  "text processing utilities"  split  ""  "\fLsplit\fP \(em split file into pieces"
.B split
reads
.I infile
and writes it in
.IR number -line
pieces (default 1000) onto a set of output files (as many files as
necessary).  The name of the first output file is
.I outfile
with
.B aa
appended, the second file is
.IB outfile \|ab ,
and so on lexicographically.
.LP
If no
.I outfile
is given,
.B x
is used
as default (output files will be called
.BR xaa ,
.BR xab ,
etc.).
.LP
If no
.I infile
is given, or if
.RB ` \- '
is given in its stead, then the standard input file is used.
.SH OPTIONS
.TP
.BI \- number
Number of lines in each piece.
