.\" @(#)strip.1 1.1 92/07/30 SMI; from UCB 4.2
.TH STRIP 1 "7 September 1988"
.SH NAME
strip \- remove symbols and relocation bits from an object file
.SH SYNOPSIS
.B strip
.IR filename .\|.\|.
.SH DESCRIPTION
.IX  "strip command"  ""  "\fLstrip\fP \(em strip symbols and relocation bits"
.IX  "programming tools"  strip  ""  "\fLstrip\fP \(em strip symbols and relocation bits"
.IX  "object file"  strip  ""  "\fLstrip\fP \(em strip symbols and relocation bits"
.LP
.B strip
removes the symbol
table and relocation bits ordinarily attached to the output
of the assembler and linker.
This is useful to save space after a program has been
debugged.
.LP
The effect of
.B strip
is the same as use of the
.B \-s
option of
.BR ld (1).
.SH SEE ALSO
.BR ld (1),
.BR a.out (5)
.SH BUGS
.LP
Unstripped 2.0 binary files will not run if stripped by the 3.0
version.  A message of the form:
.IP
.B pid
.IB xxx :
.B killed due to swap problems in getxfile:
.B
.SM I/O
.B error mapping page.
.LP
when attempting to run a program indicates that this is the problem.
