.\" @(#)strings.1 1.1 92/07/30 SMI; from UCB 4.1
.TH STRINGS 1 "9 September 1987"
.SH NAME
strings \- find printable strings in an object file or binary
.SH SYNOPSIS
.B strings
[
.B \-
] [
.B \-o
] [
.BI \- number
]
.I filename .\|.\|.
.SH DESCRIPTION
.IX  "strings command"  ""  "\fLstrings\fP \(em find printable strings in binary file"
.IX  find "printable strings in binary file"  ""  "find printable strings in binary file \(em \fLstrings\fP"
.IX  "programming tools"  strings  ""  "\fLstrings\fP \(em find printable strings in binary file"
.IX  "object file"  "find printable strings in"  ""  "find printable strings in \(em \fLstrings\fP"
.B strings
looks for
.SM ASCII
strings in a binary file.
A string is any sequence of 4 or more
printing characters ending with a
.SM NEWLINE
or a
null character.
.LP
.B strings
is useful for identifying random object files and many other things.
.SH OPTIONS
.TP
.B \-
Look everywhere in the file for strings.  If this flag is omitted,
.B strings
only looks in the initialized data space of object files.
.TP
.B \-o
Precede each string by its
offset in the file.
.TP
.BI \- number
Use
.I number
as the minimum string length rather than 4.
.SH "SEE ALSO"
.BR od (1V)
.SH NOTES
.B strings
is not 8-bit clean because it makes too many
mistakes when it is expected to look for strings
containing non-\s-1ASCII\s0 characters.
.SH BUGS
The algorithm for identifying strings is extremely primitive.
