.\" @(#)symorder.1 1.1 92/07/30 SMI;
.TH SYMORDER 1 "18 February 1988"
.SH NAME
symorder \- rearrange a list of symbols
.SH SYNOPSIS
.B symorder
[
.B \-s
]
.I orderlist symbolfile
.SH DESCRIPTION
.IX symorder "" "\fLsymorder\fR \(em update symbol table ordering"
.LP
.I sysmfile 
is a file containing symbols to be found in objectfile,
1 symbol per line.
.LP
.I objectfile
is updated in place to put the requested symbols first
in the symbol table, in the order specified.  This is done
by swapping the old symbols in the required spots with the
new ones.  If all of the order symbols are not found, an
error is generated.
.LP
This program was specifically designed to cut down on the
overhead of getting symbols from
.BR /vmunix .
.SH Sun386i DESCRIPTION
.LP
Symbols specified on the command
line are moved to the beginning of the output symbol table, not swapped.
Therefore, the symbols specified on the command line will appear in
order at the beginning of the output symbol table, followed by the
original symbol table with the gaps created by the moved symbols closed.
.SH OPTIONS
.TP
.B \-s
Work silently, that is, display nothing except error messages.
This is useful for checking the error status.
.SH FILES
.PD 0
.TP 20
.B /vmunix
.PD
.SH "SEE ALSO"
.BR nlist (3V)
