.\" @(#)syswait.1 1.1 92/07/30 SMI; 
.TH SYSWAIT 1 "19 February 1988"
.SH NAME
syswait \- execute a command, suspending termination until user input
.SH SYNOPSIS
.B syswait
.I message
.I command
.SH AVAILABILITY
.LP
Available only on Sun 386i systems running a SunOS 4.0.\fIx\fR
release or earlier.  Not a SunOS 4.1 release feature.
.SH DESCRIPTION
.IX syswait "" "\fLsyswait\fR \(em execute a command"
.LP
.B syswait
executes a specified command, suspending termination until the
user types any character.
.I message
is the message prompting the user to type a character to terminate the
command.  
.I command
is the command to be executed.
.SH EXAMPLE
.LP
The following example invokes a cmdtool and executes
.RB ` "ls *.c" ',
but waits for the user to type a character
before terminating the
.B ls
and closing the cmdtool window.
.IP
\fBcmdtool syswait "Press any key to quit\|.\|.\|." "ls *.c" &\fR
