.\" Copyright (c) 1985 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\" @(#)tcopy.1 1.1 92/07/30 SMI; from UCB 4.3 BSD 6.1
.\"
.TH TCOPY 1 "9 September 1987"
.SH NAME
tcopy \- copy a magnetic tape
.SH SYNOPSIS
.B tcopy
.I source
[
.I destination
]
.SH DESCRIPTION
.IX  "magnetic tape"  "copy"  ""    "copy \(em \fLtcopy\fP"
.IX  "magnetic tape"  "scan"  ""    "scan \(em \fLtcopy\fP"
.IX  tape  "copy, blocking preserved"  ""    "copy, blocking preserved \(em \fLtcopy\fP"
.IX  "tape"  "scan"  ""    "scan \(em \fLtcopy\fP"
.LP
.B tcopy
copies the magnetic tape mounted on the tape drive specified by the
.IR source
argument.  The only assumption made about the contents of a tape is
that there are two tape marks at the end.
.LP
When only a source drive is specified,
.B tcopy
scans the tape, and displays information about the sizes of records
and tape files.  If a destination is specified,
.B tcopy
makes a copies the source tape onto the
.I destination
tape, with blocking preserved.  As it copies,
.B tcopy
produces the same output as it does when only scanning a tape.
.SH "SEE ALSO"
.BR mt (1)
