.\" @(#)tee.1 1.1 92/07/30 SMI; from UCB 4.2
.TH TEE 1 "9 September 1987"
.SH NAME
tee \- replicate the standard output
.SH SYNOPSIS
.B tee
[
.B \-ai
] [
.I filename
] .\|.\|.
.IX  "tee command"  ""  "\fLtee\fP \(em copy standard output to many files"
.IX  "copy" "standard output to many files \(em \fLtee\fP"
.IX  "standard output, copy to many files"  ""  "standard output, copy to many files \(em \fLtee\fP"
.IX  files  "copy standard output to many"  ""  "copy standard output to many \(em \fLtee\fP"
.SH DESCRIPTION
.B tee
transcribes the standard input to the
standard output and makes copies in the
.IR filename s.
.SH OPTIONS
.TP
.B \-a
Append the output to the
.IR filename s
rather than overwriting them.
.TP
.B \-i
Ignore interrupts.
