.\" @(#)true.1 1.1 92/07/30 SMI; from UCB 4.2
.TH TRUE 1 "9 September 1987"
.SH NAME
true, false \- provide truth values
.SH SYNOPSIS
.B true
.LP
.B false
.IX  "true command"  ""  "\fLtrue\fP \(em provide truth values"
.IX  "provide truth values"  ""  "provide truth values \(em \fLtrue\fP"
.SH DESCRIPTION
.B true
and
.B false
are usually used in a Bourne shell script.
They test for the appropriate status \*(lqtrue\*(rq
or \*(lqfalse\*(rq before running
(or failing to run) a list of commands.
.SH EXAMPLE
.LP
The following Bourne shell script will
be executed while the case status is \*(lqtrue\*(rq.
.RS
.nf
.B while true
.B do
.RS
.B command list
.RE
.B done
.fi
.RE
.SH "SEE ALSO"
.BR csh (1),
.BR sh (1)
.SH EXIT STATUS
.LP
.B true
has exit status 0.
.LP
.B false
has exit status 1.
