.\" @(#)tsort.1 1.1 92/07/30 SMI; from UCB 4.2
.TH TSORT 1 "9 September 1987"
.SH NAME
tsort \- topological sort
.SH SYNOPSIS
.B tsort
[
.I filename
]
.IX  "tsort command"  ""  "\fLtsort\fP \(em topological sort"
.IX  "topological sort"  ""  "topological sort \(em \fLtsort\fP"
.IX  "sort topologically"  ""  "sort topologically \(em \fLtsort\fP"
.IX  "text processing utilities"  tsort  ""  "\fLtsort\fP \(em topological sort"
.SH DESCRIPTION
.B tsort
produces on the standard output a totally ordered list of items
consistent with a partial ordering of items
mentioned in the input
.IR filename .
If no
.I filename
is specified, the standard input is understood.
.LP
The input consists of pairs of items (nonempty strings)
separated by
.SM SPACE
characters.
Pairs of different items indicate ordering.
Pairs of identical items indicate presence, but not ordering.
.SH "SEE ALSO"
.BR lorder (1)
.SH BUGS
Uses a quadratic algorithm; not worth
fixing for the typical use of ordering
a library archive file.
