.\" @(#)tty.1 1.1 92/07/30 SMI; from UCB 4.2
.TH TTY 1 "9 September 1987"
.SH NAME
tty \- display the name of the terminal
.SH SYNOPSIS
.B tty
[
.B \-s
]
.IX  "tty command"  ""  "\fLtty\fP \(em get terminal name"
.IX  get "terminal name \(em \fLtty\fP"
.IX  terminal  "get name of"  ""  "get name of \(em \fLtty\fP"
.IX  "login environment"  tty  ""  "\fLtty\fP \(em get terminal name"
.SH DESCRIPTION
.B tty
prints the pathname of the user's terminal unless the
.B \-s
(silent) option is given. In either case, the
exit value is zero if the
standard input is a terminal, and one if it is not.
.SH OPTIONS
.TP
.B \-s
Silent. Does not print the pathname of the user's terminal.
