.\" @(#)unwhiteout.1 1.1 92/07/30 SMI;
.TH UNWHITEOUT 1 "23 November 1988"
.SH NAME
unwhiteout \- remove a TFS whiteout entry
.SH SYNOPSIS
.B unwhiteout
.IR filename \|.\|.\|.
.SH DESCRIPTION
.IX unwhiteout "" "\fLunwhiteout\fP\(emremove a TFS whiteout entry"
.IX TFS "remove a TFS whiteout entry"
.IX remove "TFS whiteout entry"
.IX "Translucent File Service" "remove whiteout entry"
.LP
For each
.I filename
that is a whiteout entry,
.B unwhiteout
removes that entry from the containing directory.
These whiteout entries
are created by the translucent file service.
See
.BR tfs (4S).
.SH "SEE ALSO"
.BR lsw (1),
.BR tfs (4S),
.BR mount_tfs (8),
.BR tfsd (8)
