.\" @(#)uptime.1 1.1 92/07/30 SMI; from UCB 4.2
.TH UPTIME 1 "9 September 1987"
.SH NAME
uptime \- show how long the system has been up
.SH SYNOPSIS
.B uptime
.IX  "uptime command"  ""  "\fLuptime\fP \(em display system up time"
.IX  display "system up time \(em \fLuptime\fP"
.SH DESCRIPTION
.LP
.B uptime
prints the current time, the length
of time the system has been up,
and the average number of jobs in
the run queue over the last 1, 5 and 15 minutes.
It is, essentially, the first line of a
.BR w (1)
command.
.SH EXAMPLE
.RS
.nf
.ft B
example% uptime
6:47am  up 6 days, 16:38,  1 users,  load average: 0.69, 0.28, 0.17
example%
.ft R
.fi
.RE
.SH FILES
.PD 0
.TP 20
.B /vmunix
system namelist
.PD
.SH SEE ALSO
.BR w (1)
