.\" @(#)users.1 1.1 92/07/30 SMI;
.TH USERS 1 "9 September 1987"
.SH NAME
users \- display a compact list of users logged in
.SH SYNOPSIS
.B users
.IX  "users command"  ""  "\fLusers\fP \(em display users on system"
.IX  display "users on system \(em \fLusers\fP"
.SH DESCRIPTION
.B users
lists the login names of the users
currently on the system in a compact,
one-line format:
.RS
.nf
.ft B
example% users
paul george ringo
example%
.ft R
.fi
.RE
.SH FILES
.PD 0
.TP 20
.B /etc/utmp
.PD
.SH SEE ALSO
.BR who (1)
