.\" @(#)wait.1 1.1 92/07/30 SMI; from UCB 4.1
.TH WAIT 1 "9 September 1987"
.SH NAME
wait \- wait for a process to finish
.SH SYNOPSIS
.B wait
.IX  "wait command"  ""  "\fLwait\fP \(em wait process completion"
.IX  process  wait  ""  "\fLwait\fP \(em wait process completion"
.SH DESCRIPTION
Wait until all processes started with
.B &
or
.B bg
have completed,
and report on abnormal terminations.
.LP
Because the
.BR wait (2V)
system call must be executed in the parent process,
the shell itself executes
.BR wait ,
without creating a new process.
.SH "SEE ALSO"
.BR csh (1),
.BR sh (1),
.BR wait (2V)
.SH BUGS
Not all the processes of a 3- or more-stage
pipeline are children of the shell, and thus cannot be waited for.
This bug does not apply to
.BR csh (1).
