.TH WALL 1 "9 September 1987"
.\" @(#)wall.1 1.1 92/07/30 SMI; from UCB 5.3
.SH NAME
wall \- write to all users logged in
.SH SYNOPSIS
.B wall
[
.B \-a
]
.RI [ " filename " ]
.IX  "wall command"  ""  "\fLwall\fP \(em write to all users"
.IX  "write to all users"  ""  "write to all users \(em \fLwall\fP"
.IX  users  "write to all"  ""  "write to all \(em \fLwall\fP"
.SH DESCRIPTION
.B wall
reads the standard input until an
.SM EOF\s0.
It then sends this message, preceded by
.RB ` "Broadcast Message .\|.\|." ',
to all logged in users.  If
.I filename
is given, then the message is read in from that file.
Normally, pseudo-terminals that do not correspond to
rlogin sessions are ignored.
Thus when in
.BR sunview (1),
the message appears only on the console window.  However,
.B \-a
will send the message even to such
pseudo-terminals.
.LP
The sender should be super-user to override
any protections the users may have invoked.
.SH FILES
.PD 0
.TP 20
.B /dev/tty?
.TP
.B /etc/utmp
.PD
.SH "SEE ALSO"
.BR mesg (1),
.BR sunview (1),
.BR write (1)
