.\" @(#)whatis.1 1.1 92/07/30 SMI; from UCB 4.2
.TH WHATIS 1 "9 September 1987"
.SH NAME
whatis \- display a one-line summary about a keyword
.SH SYNOPSIS
.B whatis
.IR command .\|.\|.
.IX  "whatis command"  ""  "\fLwhatis\fP \(em describe command"
.IX  "describe command"  ""  "describe command \(em \fLwhatis\fP"
.IX  command  describe  ""  "describe \(em \fLwhatis\fP"
.IX  "manual pages"  "describe command"  ""  "describe command \(em \fLwhatis\fP"
.SH DESCRIPTION
.LP
.B whatis
looks up a given
.I command
and displays the header line
from the manual section.
You can then run the
.BR man (1)
command to get more information.  If the line starts
.RB ` "name(\fIsection\fP)\ " .\|.\|.'
you can do
.RB ` "man\ \ \fIsection\fP\ \ name" '
to get the documentation for it.  Try
.RB ` "whatis\ \ ed" '
and then you should do
.RB ` "man\ \ 1\ \ ed" '
to get the manual page for
.BR ed (1).
.LP
.B whatis
is actually just the
.B \-f
option to the
.BR man (1)
command.
.LP
.B whatis
uses the
.B whatis
database.  This database can be created using the
.B \-w
option of
.BR catman (8).
.SH FILES
.PD 0
.TP 20
.B /usr/[share]/man/whatis
data base
.PD
.SH SEE ALSO
.BR apropos (1),
.BR man (1),
.BR catman (8)
.SH NOTES
.LP
.B whatis
uses the
.B /usr/man/whatis
database, which is created by
.BR catman (8).
