.\" @(#)what.1 1.1 92/07/30 SMI; from UCB 4.2
.TH WHAT 1 "30 June 1988"
.SH NAME
what \- extract SCCS version information from a file
.SH SYNOPSIS
.B what
[
.B \-s
]
.I filename .\|.\|.
.IX  "what command"  ""  "\fLwhat\fP \(em identify file version"
.IX  "identify file version"  ""  "identify file version \(em \fLwhat\fP"
.IX  file  "identify version"  ""  "identify version \(em \fLwhat\fP"
.IX  "version of file \(em \fLwhat\fP"
.SH DESCRIPTION
.B what
searches each
.IR filename
for occurrences of the pattern
.B @(#)
that the
.SM SCCS
.BR get
command (see
.BR sccs-get (1))
substitutes for the
.B %\&Z%
ID keyword, and
prints what follows up to a
\fB"\fP,
.BR > ,
.SM NEWLINE\s0,
.BR \e ,
or
null
character.
For instance, if the C program in file
.B program.c
contains
.IP
.ft B
char sccsid[\|] = "\|@(#)identification information\|";
.ft R
.LP
and
.B program.c
is compiled to yield
.B program.o
and
.BR a.out ,
the command:
.RS
.ft B
what program.c program.o a.out
.ft R
.RE
.LP
produces:
.RS
.TP
.BR program.c :
identification information
.TP
.BR program.o :
identification information
.TP
.BR a.out :
identification information
.RE
.SH OPTIONS
.TP
.B \-s
Stop after the first occurrence of the pattern.
.SH SEE ALSO
.BR sccs (1),
.BR sccs-admin (1),
.BR sccs-cdc (1),
.BR sccs-comb (1),
.BR sccs-delta (1),
.BR sccs-get (1),
.BR sccs-help (1),
.BR sccs-prs (1),
.BR sccs-prt (1),
.BR sccs-rmdel (1),
.BR sccs-sact (1),
.BR sccs-sccsdiff (1),
.BR sccs-unget (1),
.BR sccs-val (1),
.BR sccsfile (5)
.LP
.TX PUL
.SH DIAGNOSTICS
.LP
Use the
.SM SCCS
.B help
command for explanations (see
.BR sccs-help (1)).
.SH BUGS
.LP
There is a remote possibility that a spurious occurrence of the
.RB ` @(#) '
pattern could be found by
.BR what .
