.\" @(#)which.1 1.1 92/07/30 SMI; from UCB 4.2
.TH WHICH 1 "9 September 1987"
.SH NAME
which \- locate a command; display its pathname or alias
.SH SYNOPSIS
.B which
[
.I filename
] .\|.\|.
.IX  "which command"  ""  "\fLwhich\fP \(em find program file"
.SH DESCRIPTION
.B which
takes a list of names and looks for the files which would be
executed had these names been given as commands.
Each argument is expanded if it is aliased,
and searched for along the user's path.
Both aliases and path are taken from the user's
.B \&.cshrc
file.
.SH FILES
.PD 0
.TP 20
.B ~/\&.cshrc
source of aliases and path values
.PD
.SH SEE ALSO
.BR csh (1)
.SH DIAGNOSTICS
A diagnostic is given for names which
are aliased to more than a single word,
or if an executable file with the
argument name was not found in the path.
.SH BUGS
Only aliases and paths from
.B ~/\&.cshrc
are used; importing from the current
environment is not attempted.
Must be executed by
.BR csh (1),
since only
.B csh
knows about aliases.
.LP
To compensate for
.B ~/.cshrc
files in which aliases depend upon the
.B prompt
variable being set,
.B which
sets this variable.  If the
.B ~/.cshrc
produces output or prompts for input when
.B prompt
is set,
.B which
may produce some strange results.
