#
# @(#)Makefile.demo 1.1 92/07/30 SMI
#
 
OBJS= dialtest.o pw_circle.o diag.o dump.o
LIBS=	-lsuntool -lsunwindow -lpixrect -lm
XOBJS= x_diag.o x_dialtest.o x_pw_circle.c x_dump.o
XLIBS=  -L${OPENWINHOME}/lib -lxview -lpixrect -lm -lolgx -lX
CFLAGS=	-O

.KEEP_STATE:

all:		dialtest x_dialtest

dialtest.o:	dialtest.c dial_icon.h

dialtest:	$(OBJS)
		cc $(CFLAGS) -o $@ $(OBJS) $(LIBS)

x_dialtest.o:	x_dialtest.c dial_icon.h

x_dialtest:	$(XOBJS)
		cc $(CFLAGS) -o $@ $(XOBJS) $(XLIBS)
