# @(#)Makefile 1.1 92/07/30 SMI;

# stub for target to convert raw template to appendix form
tempalte.mex: template.sh template.header template.trailer
	cat template.header > $@
	sed ... >> $@
	cat template.trailer >> $@
	rm -f template.header template.trailer
